/*
 * undefined means data not obtained.
 */
function FoodDatabase()
{
    var start = new Date().getTime();
    var that = this;

    var foods = [
    // /////////////////////////////////////////////////////////////////////////
    // Basic.
    // /////////////////////////////////////////////////////////////////////////
    // Beverage.
    {
        type: FoodType.BEVERAGE,
        brand: "A&W",
        name: "Diet Root Beer",
        servingSize: "1 can",
        servingsPerContainer: 12,
        calories: 0,
        caloriesFromFat: 0,
        fat: 0,
        fatSaturated: undefined,
        fatTrans: undefined,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 0,
        sodium: 110,
        potassium: 0,
        carbs: 0,
        carbsDietaryFiber: 0,
        carbsSugars: 0,
        protein: 0
    },
    {
        type: FoodType.BEVERAGE,
        brand: "Coca Cola",
        name: "Caffeine Free Diet Coke",
        servingSize: "1 can",
        servingsPerContainer: 12,
        calories: 0,
        caloriesFromFat: 0,
        fat: 0,
        fatSaturated: 0,
        fatTrans: 0,
        fatPolyunsat: 0,
        fatMonounsat: 0,
        cholesterol: 0,
        sodium: 40,
        potassium: 0,
        carbs: 0,
        carbsDietaryFiber: 0,
        carbsSugars: 0,
        protein: 0
    },
    {
        type: FoodType.BEVERAGE,
        brand: "Coca Cola",
        name: "Caffeine Free Zero",
        servingSize: "1 can",
        servingsPerContainer: 12,
        calories: 0,
        caloriesFromFat: undefined,
        fat: 0,
        fatSaturated: undefined,
        fatTrans: undefined,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: undefined,
        sodium: 40,
        potassium: undefined,
        carbs: 0,
        carbsDietaryFiber: undefined,
        carbsSugars: undefined,
        protein: 0
    },
    {
        type: FoodType.BEVERAGE,
        brand: "Fresca",
        name: "Peach Citrus",
        servingSize: "1 can",
        servingsPerContainer: 12,
        calories: 0,
        caloriesFromFat: 0,
        fat: 0,
        fatSaturated: 0,
        fatTrans: 0,
        fatPolyunsat: 0,
        fatMonounsat: 0,
        cholesterol: 0,
        sodium: 35,
        potassium: 0,
        carbs: 0,
        carbsDietaryFiber: 0,
        carbsSugars: 0,
        protein: 0
    },
    {
        type: FoodType.BEVERAGE,
        brand: "Gold Standard",
        name: "Natural Whey chocolate",
        servingSize: "1 scoop",
        servingsPerContainer: 71,
        calories: 130,
        caloriesFromFat: 10,
        fat: 1,
        fatSaturated: 0.5,
        fatTrans: 0,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 30,
        sodium: 60,
        potassium: undefined,
        carbs: 5,
        carbsDietaryFiber: 1,
        carbsSugars: 2,
        protein: 24
    },
    // /////////////////////////////////////////////////////////////////////////
    // Cereal.
    {
        type: FoodType.CEREAL,
        brand: "King Soopers",
        name: "Hot Dog Buns",
        servingSize: "1 bun",
        servingsPerContainer: 8,
        calories: 130,
        caloriesFromFat: 15,
        fat: 2,
        fatSaturated: 0,
        fatTrans: 0,
        fatPolyunsat: 0.5,
        fatMonounsat: 0,
        cholesterol: 0,
        sodium: 230,
        potassium: undefined,
        carbs: 26,
        carbsDietaryFiber: 1,
        carbsSugars: 4,
        protein: 4
    },
    {
        type: FoodType.CEREAL,
        brand: "Kroger",
        name: "Hot Dog Buns",
        servingSize: "1 bun",
        servingsPerContainer: 8,
        calories: 130,
        caloriesFromFat: 15,
        fat: 2,
        fatSaturated: undefined,
        fatTrans: undefined,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: undefined,
        sodium: 230,
        potassium: 26,
        carbs: 1,
        carbsDietaryFiber: 4,
        carbsSugars: undefined,
        protein: 4
    },
    {
        type: FoodType.CEREAL,
        brand: "Kroger",
        name: "Saltines",
        servingSize: "5 crackers",
        servingsPerContainer: 32,
        calories: 60,
        caloriesFromFat: 15,
        fat: 1.5,
        fatSaturated: 0,
        fatTrans: 0,
        fatPolyunsat: 1,
        fatMonounsat: 0.5,
        cholesterol: 0,
        sodium: 115,
        potassium: undefined,
        carbs: 10,
        carbsDietaryFiber: 1,
        carbsSugars: 0,
        protein: 1
    },
    {
        type: FoodType.CEREAL,
        brand: "P$$t",
        name: "Saltines",
        servingSize: "5 crackers",
        servingsPerContainer: 32,
        calories: 60,
        caloriesFromFat: 10,
        fat: 1,
        fatSaturated: 0.5,
        fatTrans: 0,
        fatPolyunsat: 0.5,
        fatMonounsat: 0,
        cholesterol: 0,
        sodium: 115,
        potassium: 0,
        carbs: 10,
        carbsDietaryFiber: 1,
        carbsSugars: 0,
        protein: 1
    },
    {
        type: FoodType.CEREAL,
        brand: "Nabisco",
        name: "Balsamic Vinegar & Basil Triscuit",
        servingSize: "28 g",
        servingsPerContainer: 9,
        calories: 120,
        caloriesFromFat: 30,
        fat: 3.5,
        fatSaturated: 0.5,
        fatTrans: 0,
        fatPolyunsat: 2,
        fatMonounsat: 0.5,
        cholesterol: 0,
        sodium: 135,
        potassium: 115,
        carbs: 20,
        carbsDietaryFiber: 3,
        carbsSugars: 1,
        protein: 3,
    },
    {
        type: FoodType.CEREAL,
        brand: "Nabisco",
        name: "Cracked Pepper & Olive Oil Triscuit",
        servingSize: "28 g",
        servingsPerContainer: 9,
        calories: 120,
        caloriesFromFat: 35,
        fat: 4,
        fatSaturated: 0.5,
        fatTrans: 0,
        fatPolyunsat: 2,
        fatMonounsat: 1,
        cholesterol: 0,
        sodium: 140,
        potassium: 115,
        carbs: 20,
        carbsDietaryFiber: 3,
        carbsSugars: 0,
        protein: 3,
    },
    {
        type: FoodType.CEREAL,
        brand: "Nabisco",
        name: "Dill, Sea Salt & Olive Oil Triscuit",
        servingSize: "28 g",
        servingsPerContainer: 9,
        calories: 120,
        caloriesFromFat: 35,
        fat: 3.5,
        fatSaturated: 0.5,
        fatTrans: 0,
        fatPolyunsat: 2,
        fatMonounsat: 1,
        cholesterol: 0,
        sodium: 170,
        potassium: 115,
        carbs: 20,
        carbsDietaryFiber: 3,
        carbsSugars: 0,
        protein: 3,
    },
    {
        type: FoodType.CEREAL,
        brand: "Nabisco",
        name: "Fire Roasted Tomato & Olive Oil Triscuit",
        servingSize: "28 g",
        servingsPerContainer: 9,
        calories: 120,
        caloriesFromFat: 30,
        fat: 3.5,
        fatSaturated: 0.5,
        fatTrans: 0,
        fatPolyunsat: 2,
        fatMonounsat: 0.5,
        cholesterol: 0,
        sodium: 140,
        potassium: 120,
        carbs: 20,
        carbsDietaryFiber: 3,
        carbsSugars: 0,
        protein: 3,
    },
    {
        type: FoodType.CEREAL,
        brand: "Nabisco",
        name: "Ranch Wheat Thins",
        servingSize: "15 pieces",
        servingsPerContainer: 9,
        calories: 140,
        caloriesFromFat: 50,
        fat: 5,
        fatSaturated: 1,
        fatTrans: 0,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 0,
        sodium: 190,
        potassium: 90,
        carbs: 21,
        carbsDietaryFiber: 3,
        carbsSugars: 4,
        protein: 2
    },
    {
        type: FoodType.CEREAL,
        brand: "Nabisco",
        name: "Roasted Garlic Triscuit",
        servingSize: "28 g",
        servingsPerContainer: 9,
        calories: 120,
        caloriesFromFat: 35,
        fat: 4,
        fatSaturated: 0.5,
        fatTrans: 0,
        fatPolyunsat: 2,
        fatMonounsat: 1,
        cholesterol: 0,
        sodium: 135,
        potassium: 115,
        carbs: 20,
        carbsDietaryFiber: 3,
        carbsSugars: 0,
        protein: 3
    },
    {
        type: FoodType.CEREAL,
        brand: "Nabisco",
        name: "Rosemary & Olive Oil Triscuit",
        servingSize: "28 g",
        servingsPerContainer: 9,
        calories: 120,
        caloriesFromFat: 35,
        fat: 4,
        fatSaturated: 0.5,
        fatTrans: 0,
        fatPolyunsat: 2,
        fatMonounsat: 1,
        cholesterol: 0,
        sodium: 130,
        potassium: 110,
        carbs: 20,
        carbsDietaryFiber: 3,
        carbsSugars: 1,
        protein: 3
    },
    {
        type: FoodType.CEREAL,
        brand: "Nabisco",
        name: "Sundried Tomato & Basil Wheat Thins",
        servingSize: "15 pieces",
        servingsPerContainer: 9,
        calories: 140,
        caloriesFromFat: 45,
        fat: 5,
        fatSaturated: 1,
        fatTrans: 0,
        fatPolyunsat: 3,
        fatMonounsat: 1,
        cholesterol: 0,
        sodium: 170,
        potassium: 100,
        carbs: 21,
        carbsDietaryFiber: 3,
        carbsSugars: 4,
        protein: 2
    },
    {
        type: FoodType.CEREAL,
        brand: "Nabisco",
        name: "Sweet & Spicy Chipotle Wheat Thins",
        servingSize: "15 pieces",
        servingsPerContainer: 9,
        calories: 140,
        caloriesFromFat: 50,
        fat: 5,
        fatSaturated: 1,
        fatTrans: 0,
        fatPolyunsat: 3,
        fatMonounsat: 1,
        cholesterol: 0,
        sodium: 150,
        potassium: 90,
        carbs: 20,
        carbsDietaryFiber: 2,
        carbsSugars: 5,
        protein: 2
    },
    {
        type: FoodType.CEREAL,
        brand: "Nabisco",
        name: "Zesty Salsa Wheat Thins",
        servingSize: "31 g",
        servingsPerContainer: 8,
        calories: 140,
        caloriesFromFat: 50,
        fat: 5,
        fatSaturated: 1,
        fatTrans: 0,
        fatPolyunsat: 3,
        fatMonounsat: 1,
        cholesterol: 0,
        sodium: 190,
        potassium: 105,
        carbs: 22,
        carbsDietaryFiber: 3,
        carbsSugars: 5,
        protein: 2
    },
    {
        type: FoodType.CEREAL,
        brand: "Quaker Instant Oatmeal",
        name: "Apples & Cinnamon Lower Sugar",
        servingSize: "1 packet",
        servingsPerContainer: 4,
        calories: 110,
        caloriesFromFat: 15,
        fat: 1.5,
        fatSaturated: 0,
        fatTrans: 0,
        fatPolyunsat: 0.5,
        fatMonounsat: 0.5,
        cholesterol: 0,
        sodium: 170,
        potassium: 120,
        carbs: 22,
        carbsDietaryFiber: 3,
        carbsSugars: 6,
        protein: 3
    },
    {
        type: FoodType.CEREAL,
        brand: "Quaker Instant Oatmeal",
        name: "Banana Bread Weight Control",
        servingSize: "1 packet",
        servingsPerContainer: 2,
        calories: 160,
        caloriesFromFat: 25,
        fat: 3,
        fatSaturated: 0.5,
        fatTrans: 0,
        fatPolyunsat: 1,
        fatMonounsat: 1,
        cholesterol: 0,
        sodium: 280,
        potassium: 150,
        carbs: 29,
        carbsDietaryFiber: 6,
        carbsSugars: 1,
        protein: 7
    },
    {
        type: FoodType.CEREAL,
        brand: "Quaker Instant Oatmeal",
        name: "Cinnamon & Spice Lower Sugar",
        servingSize: "1 packet",
        servingsPerContainer: 2,
        calories: 120,
        caloriesFromFat: 20,
        fat: 2,
        fatSaturated: 0,
        fatTrans: 0,
        fatPolyunsat: 0.5,
        fatMonounsat: 0.5,
        cholesterol: 0,
        sodium: 260,
        potassium: 110,
        carbs: 24,
        carbsDietaryFiber: 3,
        carbsSugars: 4,
        protein: 4
    },
    {
        type: FoodType.CEREAL,
        brand: "Quaker Instant Oatmeal",
        name: "Cinnamon Weight Control",
        servingSize: "1 packet",
        servingsPerContainer: 2,
        calories: 160,
        caloriesFromFat: 25,
        fat: 3,
        fatSaturated: 0.5,
        fatTrans: 0,
        fatPolyunsat: 1,
        fatMonounsat: 1,
        cholesterol: 0,
        sodium: 280,
        potassium: 150,
        carbs: 29,
        carbsDietaryFiber: 6,
        carbsSugars: 1,
        protein: 7
    },
    {
        type: FoodType.CEREAL,
        brand: "Quaker Instant Oatmeal",
        name: "Maple & Brown Sugar High Fiber",
        servingSize: "1 packet",
        servingsPerContainer: 8,
        calories: 160,
        caloriesFromFat: 20,
        fat: 2,
        fatSaturated: 0,
        fatTrans: 0,
        fatPolyunsat: 0.5,
        fatMonounsat: 0.5,
        cholesterol: 0,
        sodium: 260,
        potassium: 115,
        carbs: 34,
        carbsDietaryFiber: 10,
        carbsSugars: 7,
        protein: 4
    },
    {
        type: FoodType.CEREAL,
        brand: "Quaker Instant Oatmeal",
        name: "Maple & Brown Sugar Lower Sugar",
        servingSize: "1 packet",
        servingsPerContainer: 4,
        calories: 120,
        caloriesFromFat: 20,
        fat: 2,
        fatSaturated: 0,
        fatTrans: 0,
        fatPolyunsat: 0.5,
        fatMonounsat: 0.5,
        cholesterol: 0,
        sodium: 290,
        potassium: 110,
        carbs: 24,
        carbsDietaryFiber: 3,
        carbsSugars: 4,
        protein: 4
    },
    {
        type: FoodType.CEREAL,
        brand: "Quaker Instant Oatmeal",
        name: "Maple & Brown Sugar Weight Control",
        servingSize: "1 packet",
        servingsPerContainer: 4,
        calories: 160,
        caloriesFromFat: 25,
        fat: 3,
        fatSaturated: 0.5,
        fatTrans: 0,
        fatPolyunsat: 1,
        fatMonounsat: 1,
        cholesterol: 0,
        sodium: 290,
        potassium: 150,
        carbs: 29,
        carbsDietaryFiber: 6,
        carbsSugars: 1,
        protein: 7
    },
    {
        type: FoodType.CEREAL,
        brand: "Quaker Instant Oatmeal",
        name: "Peaches & Cream",
        servingSize: "1 packet",
        servingsPerContainer: 10,
        calories: 130,
        caloriesFromFat: 20,
        fat: 2,
        fatSaturated: undefined,
        fatTrans: undefined,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: undefined,
        sodium: 180,
        potassium: undefined,
        carbs: 27,
        carbsDietaryFiber: 2,
        carbsSugars: 12,
        protein: 3
    },
    {
        type: FoodType.CEREAL,
        brand: "Quaker Instant Oatmeal",
        name: "Raisin, Date & Walnut",
        servingSize: "1 packet",
        servingsPerContainer: 10,
        calories: 140,
        caloriesFromFat: 25,
        fat: 2.5,
        fatSaturated: 0,
        fatTrans: 0,
        fatPolyunsat: 1,
        fatMonounsat: 0.5,
        cholesterol: 0,
        sodium: 190,
        potassium: 140,
        carbs: 27,
        carbsDietaryFiber: 3,
        carbsSugars: 11,
        protein: 3
    },
    {
        type: FoodType.CEREAL,
        brand: "Quaker Instant Oatmeal",
        name: "Strawberries & Cream",
        servingSize: "1 packet",
        servingsPerContainer: 10,
        calories: 130,
        caloriesFromFat: 20,
        fat: 2,
        fatSaturated: undefined,
        fatTrans: undefined,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 0,
        sodium: 180,
        potassium: 100,
        carbs: 27,
        carbsDietaryFiber: 2,
        carbsSugars: 12,
        protein: 3
    },
    // /////////////////////////////////////////////////////////////////////////
    // Dairy.
    {
        type: FoodType.DAIRY,
        brand: "Daisy",
        name: "Light Sour Cream",
        servingSize: "2 tbsp",
        servingsPerContainer: 15,
        calories: 40,
        caloriesFromFat: 25,
        fat: 2.5,
        fatSaturated: 2,
        fatTrans: 0,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 10,
        sodium: 25,
        potassium: undefined,
        carbs: 2,
        carbsDietaryFiber: 0,
        carbsSugars: 2,
        protein: 2
    },
    {
        type: FoodType.DAIRY,
        brand: "King Soopers",
        name: "Blended Blueberry Yogurt",
        servingSize: "1 container",
        servingsPerContainer: 1,
        calories: 190,
        caloriesFromFat: 15,
        fat: 2,
        fatSaturated: 1,
        fatTrans: 0,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 10,
        sodium: 120,
        potassium: 320,
        carbs: 35,
        carbsDietaryFiber: 0,
        carbsSugars: 33,
        protein: 7
    },
    {
        type: FoodType.DAIRY,
        brand: "King Soopers",
        name: "Blended Cherry Yogurt",
        servingSize: "1 container",
        servingsPerContainer: 1,
        calories: 190,
        caloriesFromFat: 20,
        fat: 2,
        fatSaturated: 1,
        fatTrans: 0,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 10,
        sodium: 120,
        potassium: 330,
        carbs: 36,
        carbsDietaryFiber: 0,
        carbsSugars: 33,
        protein: 7
    },
    {
        type: FoodType.DAIRY,
        brand: "King Soopers",
        name: "Blended Raspberry Yogurt",
        servingSize: "1 container",
        servingsPerContainer: 1,
        calories: 190,
        caloriesFromFat: 20,
        fat: 2,
        fatSaturated: 1,
        fatTrans: 0,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 10,
        sodium: 120,
        potassium: 320,
        carbs: 35,
        carbsDietaryFiber: 0,
        carbsSugars: 32,
        protein: 8
    },
    {
        type: FoodType.DAIRY,
        brand: "King Soopers",
        name: "Fruit Blueberry Yogurt",
        servingSize: "1 container",
        servingsPerContainer: 1,
        calories: 170,
        caloriesFromFat: 20,
        fat: 2,
        fatSaturated: 1.5,
        fatTrans: 0,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 10,
        sodium: 100,
        potassium: 260,
        carbs: 32,
        carbsDietaryFiber: 0,
        carbsSugars: 29,
        protein: 6
    },
    {
        type: FoodType.DAIRY,
        brand: "King Soopers",
        name: "Fruit Cherry Yogurt",
        servingSize: "1 container",
        servingsPerContainer: 1,
        calories: 170,
        caloriesFromFat: 20,
        fat: 2,
        fatSaturated: 1.5,
        fatTrans: 0,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 16,
        sodium: 100,
        potassium: 300,
        carbs: 31,
        carbsDietaryFiber: 0,
        carbsSugars: 28,
        protein: 6
    },
    {
        type: FoodType.DAIRY,
        brand: "King Soopers",
        name: "Fruit Raspberry Yogurt",
        servingSize: "1 container",
        servingsPerContainer: 1,
        calories: 170,
        caloriesFromFat: 20,
        fat: 2,
        fatSaturated: 1.5,
        fatTrans: 0,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 10,
        sodium: 100,
        potassium: 270,
        carbs: 31,
        carbsDietaryFiber: 0,
        carbsSugars: 28,
        protein: 6
    },
    {
        type: FoodType.DAIRY,
        brand: "Kroger",
        name: "3 Cheese Blend cheese singles",
        servingSize: "1 slice",
        servingsPerContainer: 16,
        calories: 70,
        caloriesFromFat: 45,
        fat: 5,
        fatSaturated: 3,
        fatTrans: 0,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 15,
        sodium: 250,
        potassium: undefined,
        carbs: 2,
        carbsDietaryFiber: 0,
        carbsSugars: 1,
        protein: 4
    },
    {
        type: FoodType.DAIRY,
        brand: "Kroger",
        name: "Cottage Cheese Lowfat",
        servingSize: "1/2 cup",
        servingsPerContainer: 6,
        calories: 100,
        caloriesFromFat: 25,
        fat: 2.5,
        fatSaturated: 1.5,
        fatTrans: 0,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 15,
        sodium: 470,
        potassium: undefined,
        carbs: 5,
        carbsDietaryFiber: 0,
        carbsSugars: 4,
        protein: 12
    },
    {
        type: FoodType.DAIRY,
        brand: "Kroger",
        name: "Grated Parmesan",
        servingSize: "2 tsp",
        servingsPerContainer: 45,
        calories: 25,
        caloriesFromFat: 15,
        fat: 1.5,
        fatSaturated: 1,
        fatTrans: 0,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 5,
        sodium: 100,
        potassium: undefined,
        carbs: 0,
        carbsDietaryFiber: 0,
        carbsSugars: 0,
        protein: 2
    },
    {
        type: FoodType.DAIRY,
        brand: "Kroger",
        name: "Grated Parmesan & Romano",
        servingSize: "2 tsp",
        servingsPerContainer: 45,
        calories: 25,
        caloriesFromFat: 15,
        fat: 2,
        fatSaturated: undefined,
        fatTrans: undefined,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 5,
        sodium: 100,
        potassium: 0,
        carbs: 0,
        carbsDietaryFiber: 0,
        carbsSugars: 0,
        protein: 2
    },
    {
        type: FoodType.DAIRY,
        brand: "Kroger",
        name: "Mozzarella String Cheese",
        servingSize: "1 piece",
        servingsPerContainer: 24,
        calories: 80,
        caloriesFromFat: 50,
        fat: 6,
        fatSaturated: 3.5,
        fatTrans: 0,
        fatPolyunsat: 0,
        fatMonounsat: 1.5,
        cholesterol: 15,
        sodium: 200,
        potassium: undefined,
        carbs: 1,
        carbsDietaryFiber: 0,
        carbsSugars: 0,
        protein: 6
    },
    {
        type: FoodType.DAIRY,
        brand: "Kroger",
        name: "Pepper Jack cheese singles",
        servingSize: "1 slice",
        servingsPerContainer: 16,
        calories: 60,
        caloriesFromFat: 35,
        fat: 4,
        fatSaturated: 2.5,
        fatTrans: 0,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 10,
        sodium: 300,
        potassium: undefined,
        carbs: 2,
        carbsDietaryFiber: 0,
        carbsSugars: 1,
        protein: 4
    },
    // /////////////////////////////////////////////////////////////////////////
    // Dessert.
    {
        type: FoodType.DESSERT,
        brand: "Cadbury",
        name: "Fingers Salted Peanut Crunch Cookies",
        servingSize: "6 cookies",
        servingsPerContainer: 4,
        calories: 160,
        caloriesFromFat: 70,
        fat: 8,
        fatSaturated: 4.5,
        fatTrans: 0,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 0,
        sodium: 75,
        potassium: undefined,
        carbs: 20,
        carbsDietaryFiber: 0,
        carbsSugars: 12,
        protein: 2
    },
    {
        type: FoodType.DESSERT,
        brand: "Cool Classics",
        name: "Ice Cream Sammies",
        servingSize: "1 sandwich",
        servingsPerContainer: 12,
        calories: 170,
        caloriesFromFat: 50,
        fat: 6,
        fatSaturated: undefined,
        fatTrans: undefined,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: undefined,
        sodium: 100,
        potassium: undefined,
        carbs: 28,
        carbsDietaryFiber: 0,
        carbsSugars: 13,
        protein: 3
    },
    {
        type: FoodType.DESSERT,
        brand: "Hershey",
        name: "Special Dark with Almonds Nuggets",
        servingSize: "4 pieces",
        servingsPerContainer: 9,
        calories: 180,
        caloriesFromFat: 110,
        fat: 13,
        fatSaturated: undefined,
        fatTrans: undefined,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: undefined,
        sodium: 10,
        potassium: undefined,
        carbs: 20,
        carbsDietaryFiber: 3,
        carbsSugars: 16,
        protein: 3
    },
    {
        type: FoodType.DESSERT,
        brand: "Kroger",
        name: "Fat Free Original Fig Bars",
        servingSize: "2 bars",
        servingsPerContainer: 12,
        calories: 90,
        caloriesFromFat: 0,
        fat: 0,
        fatSaturated: undefined,
        fatTrans: undefined,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: undefined,
        sodium: 90,
        potassium: undefined,
        carbs: 22,
        carbsDietaryFiber: 1,
        carbsSugars: 13,
        protein: 1
    },
    {
        type: FoodType.DESSERT,
        brand: "Market Pantry",
        name: "Ice Cream Sandwiches",
        servingSize: "1 sandwich",
        servingsPerContainer: 12,
        calories: 150,
        caloriesFromFat: 45,
        fat: 5,
        fatSaturated: 3,
        fatTrans: 0,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 15,
        sodium: 125,
        potassium: undefined,
        carbs: 24,
        carbsDietaryFiber: 0,
        carbsSugars: 12,
        protein: 2
    },
    {
        type: FoodType.DESSERT,
        brand: "Mars",
        name: "Almond M&Ms",
        servingSize: "42 g",
        servingsPerContainer: 7,
        calories: 220,
        caloriesFromFat: 110,
        fat: 12,
        fatSaturated: 4,
        fatTrans: 0,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 5,
        sodium: 20,
        potassium: undefined,
        carbs: 25,
        carbsDietaryFiber: 2,
        carbsSugars: 21,
        protein: 3
    },
    {
        type: FoodType.DESSERT,
        brand: "Mars",
        name: "Dark Chocolate Peanut M&Ms",
        servingSize: "42 g",
        servingsPerContainer: 7,
        calories: 220,
        caloriesFromFat: 110,
        fat: 12,
        fatSaturated: 4.5,
        fatTrans: 0,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 0,
        sodium: 10,
        potassium: undefined,
        carbs: 25,
        carbsDietaryFiber: 2,
        carbsSugars: 20,
        protein: 4
    },
    {
        type: FoodType.DESSERT,
        brand: "Mars",
        name: "Peanut M&Ms",
        servingSize: "42 g",
        servingsPerContainer: 28,
        calories: 220,
        caloriesFromFat: 100,
        fat: 11,
        fatSaturated: 4.5,
        fatTrans: 0,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 5,
        sodium: 20,
        potassium: undefined,
        carbs: 26,
        carbsDietaryFiber: 1,
        carbsSugars: 22,
        protein: 4
    },
    {
        type: FoodType.DESSERT,
        brand: "Mother's Cookies",
        name: "Iced Oatmeal",
        servingSize: "4 cookies",
        servingsPerContainer: 10,
        calories: 150,
        caloriesFromFat: 50,
        fat: 6,
        fatSaturated: 2,
        fatTrans: 0,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 0,
        sodium: 160,
        potassium: undefined,
        carbs: 23,
        carbsDietaryFiber: 1,
        carbsSugars: 12,
        protein: 2
    },
    {
        type: FoodType.DESSERT,
        brand: "Nabisco",
        name: "Birthday Cake Golden Oreo",
        servingSize: "2 cookies",
        servingsPerContainer: 15,
        calories: 150,
        caloriesFromFat: 60,
        fat: 7,
        fatSaturated: 2,
        fatTrans: 0,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 0,
        sodium: 80,
        potassium: 15,
        carbs: 21,
        carbsDietaryFiber: 0,
        carbsSugars: 12,
        protein: 1
    },
    {
        type: FoodType.DESSERT,
        brand: "Nabisco",
        name: "Chips Ahoy!",
        servingSize: "3 cookies",
        servingsPerContainer: 11,
        calories: 160,
        caloriesFromFat: 70,
        fat: 8,
        fatSaturated: undefined,
        fatTrans: undefined,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 0,
        sodium: 110,
        potassium: 45,
        carbs: 22,
        carbsDietaryFiber: 1,
        carbsSugars: 11,
        protein: 1
    },
    {
        type: FoodType.DESSERT,
        brand: "Nabisco",
        name: "Chips Ahoy! reduced fat",
        servingSize: "3 cookies",
        servingsPerContainer: 11,
        calories: 150,
        caloriesFromFat: 50,
        fat: 6,
        fatSaturated: undefined,
        fatTrans: undefined,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: undefined,
        sodium: 140,
        potassium: undefined,
        carbs: 24,
        carbsDietaryFiber: 1,
        carbsSugars: 11,
        protein: 2
    },
    {
        type: FoodType.DESSERT,
        brand: "Nabisco",
        name: "Golden Oreo",
        servingSize: "3 cookies",
        servingsPerContainer: 12,
        calories: 160,
        caloriesFromFat: 60,
        fat: 7,
        fatSaturated: undefined,
        fatTrans: undefined,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 0,
        sodium: 120,
        potassium: 15,
        carbs: 24,
        carbsDietaryFiber: 0,
        carbsSugars: 12,
        protein: 1
    },
    {
        type: FoodType.DESSERT,
        brand: "Nabisco",
        name: "Golden Double Stuf Oreo",
        servingSize: "2 cookies",
        servingsPerContainer: 15,
        calories: 150,
        caloriesFromFat: 60,
        fat: 7,
        fatSaturated: 2,
        fatTrans: 0,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 0,
        sodium: 80,
        potassium: 15,
        carbs: 21,
        carbsDietaryFiber: 0,
        carbsSugars: 12,
        protein: 1
    },
    {
        type: FoodType.DESSERT,
        brand: "Nabisco",
        name: "Mint Creme Oreo",
        servingSize: "2 cookies",
        servingsPerContainer: 15,
        calories: 140,
        caloriesFromFat: 60,
        fat: 7,
        fatSaturated: 2,
        fatTrans: 0,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 0,
        sodium: 90,
        potassium: 35,
        carbs: 21,
        carbsDietaryFiber: 1,
        carbsSugars: 13,
        protein: 1
    },
    {
        type: FoodType.DESSERT,
        brand: "Pepperidge Farm",
        name: "Double Chocolate Milano",
        servingSize: "2 cookies",
        servingsPerContainer: 8,
        calories: 140,
        caloriesFromFat: 70,
        fat: 8,
        fatSaturated: 3.5,
        fatTrans: 0,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 5,
        sodium: 45,
        potassium: undefined,
        carbs: 17,
        carbsDietaryFiber: 1,
        carbsSugars: 9,
        protein: 1
    },
    {
        type: FoodType.DESSERT,
        brand: "Pepperidge Farm",
        name: "Mint Chocolate Milano",
        servingSize: "2 cookies",
        servingsPerContainer: 8,
        calories: 130,
        caloriesFromFat: 70,
        fat: 7,
        fatSaturated: 4,
        fatTrans: 0,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 5,
        sodium: 35,
        potassium: undefined,
        carbs: 16,
        carbsDietaryFiber: 1,
        carbsSugars: 9,
        protein: 1
    },
    {
        type: FoodType.DESSERT,
        brand: "Peter Paul",
        name: "Almond Joy snack size",
        servingSize: "1 bar",
        servingsPerContainer: 19,
        calories: 80,
        caloriesFromFat: 40,
        fat: 5,
        fatSaturated: undefined,
        fatTrans: undefined,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: undefined,
        sodium: 20,
        potassium: undefined,
        carbs: 10,
        carbsDietaryFiber: 1,
        carbsSugars: 8,
        protein: 1
    },
    // /////////////////////////////////////////////////////////////////////////
    // Fish.
    {
        type: FoodType.FISH,
        brand: "Chicken of the Sea",
        name: "Pink Salmon",
        servingSize: "1/4 cup",
        servingsPerContainer: 7,
        calories: 90,
        caloriesFromFat: 45,
        fat: 5,
        fatSaturated: 1,
        fatTrans: 0,
        fatPolyunsat: 2,
        fatMonounsat: 1.5,
        cholesterol: 40,
        sodium: 270,
        potassium: undefined,
        carbs: 0,
        carbsDietaryFiber: 0,
        carbsSugars: 0,
        protein: 12
    },
    {
        type: FoodType.FISH,
        brand: "StarKist",
        name: "Solid White Albacore tuna in water",
        servingSize: "2 oz",
        servingsPerContainer: 4.5,
        calories: 60,
        caloriesFromFat: 5,
        fat: 0.5,
        fatSaturated: 0,
        fatTrans: 0,
        fatPolyunsat: 0.5,
        fatMonounsat: 0,
        cholesterol: 20,
        sodium: 190,
        potassium: 150,
        carbs: 0,
        carbsDietaryFiber: 0,
        carbsSugars: undefined,
        protein: 13
    },
    // /////////////////////////////////////////////////////////////////////////
    // Fruit.
    {
        type: FoodType.FRUIT,
        brand: "Generic",
        name: "Orange",
        servingSize: "1 medium",
        servingsPerContainer: 1,
        calories: 62,
        caloriesFromFat: 1,
        fat: 0,
        fatSaturated: undefined,
        fatTrans: undefined,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 0,
        sodium: 0,
        potassium: 237,
        carbs: 15,
        carbsDietaryFiber: 3,
        carbsSugars: 12,
        protein: 1
    },
    {
        type: FoodType.FRUIT,
        brand: "Generic",
        name: "Banana",
        servingSize: "1 medium",
        servingsPerContainer: 1,
        calories: 105,
        caloriesFromFat: 4,
        fat: 1,
        fatSaturated: undefined,
        fatTrans: undefined,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 0,
        sodium: 1,
        potassium: 422,
        carbs: 27,
        carbsDietaryFiber: 3,
        carbsSugars: 14,
        protein: 1
    },
    {
        type: FoodType.FRUIT,
        brand: "Generic",
        name: "Red Delicious Apple",
        servingSize: "1 medium",
        servingsPerContainer: 1,
        calories: 72,
        caloriesFromFat: 2,
        fat: 1,
        fatSaturated: undefined,
        fatTrans: undefined,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 0,
        sodium: 1,
        potassium: 148,
        carbs: 19,
        carbsDietaryFiber: 3,
        carbsSugars: 14,
        protein: 1
    },
    {
        type: FoodType.FRUIT,
        brand: "Del Monte",
        name: "Sliced Pears no sugar added",
        servingSize: "1/2 cup",
        servingsPerContainer: 3.5,
        calories: 40,
        caloriesFromFat: 0,
        fat: 0,
        fatSaturated: 0,
        fatTrans: 0,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 0,
        sodium: 5,
        potassium: 60,
        carbs: 10,
        carbsDietaryFiber: 2,
        carbsSugars: 7,
        protein: 0,
        useContainer: true
    },
    // /////////////////////////////////////////////////////////////////////////
    // Meat.
    {
        type: FoodType.MEAT,
        brand: "Generic",
        name: "Egg",
        servingSize: "1 large",
        servingsPerContainer: 12,
        calories: 70,
        caloriesFromFat: 45,
        fat: 5,
        fatSaturated: undefined,
        fatTrans: undefined,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 185,
        sodium: 70,
        potassium: 70,
        carbs: 0,
        carbsDietaryFiber: 0,
        carbsSugars: 0,
        protein: 6
    },
    {
        type: FoodType.MEAT,
        brand: "Kroger",
        name: "Real Bacon Bits",
        servingSize: "1 tbsp",
        servingsPerContainer: 12,
        calories: 25,
        caloriesFromFat: 10,
        fat: 1.5,
        fatSaturated: 0.5,
        fatTrans: 0,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 5,
        sodium: 220,
        potassium: undefined,
        carbs: 0,
        carbsDietaryFiber: 0,
        carbsSugars: 0,
        protein: 3
    },
    {
        type: FoodType.MEAT,
        brand: "Oscar Mayer",
        name: "Beef Franks",
        servingSize: "1 link",
        servingsPerContainer: 10,
        calories: 140,
        caloriesFromFat: 110,
        fat: 13,
        fatSaturated: undefined,
        fatTrans: undefined,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: undefined,
        sodium: 360,
        potassium: undefined,
        carbs: 1,
        carbsDietaryFiber: 0,
        carbsSugars: 1,
        protein: 5
    },
    {
        type: FoodType.MEAT,
        brand: "Oscar Mayer",
        name: "Lean Beef Franks",
        servingSize: "1 link",
        servingsPerContainer: 8,
        calories: 60,
        caloriesFromFat: 30,
        fat: 3.5,
        fatSaturated: 1.5,
        fatTrans: 0,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 20,
        sodium: 380,
        potassium: undefined,
        carbs: 1,
        carbsDietaryFiber: undefined,
        carbsSugars: 1,
        protein: 6
    },
    {
        type: FoodType.MEAT,
        brand: "Oscar Mayer Selects",
        name: "Hardwood Smoked Turkey Franks",
        servingSize: "1 link",
        servingsPerContainer: 8,
        calories: 120,
        caloriesFromFat: 80,
        fat: 9,
        fatSaturated: 2.5,
        fatTrans: 0,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 35,
        sodium: 480,
        potassium: undefined,
        carbs: 3,
        carbsDietaryFiber: undefined,
        carbsSugars: 1,
        protein: 6
    },
    // /////////////////////////////////////////////////////////////////////////
    // Nuts.
    {
        type: FoodType.NUTS,
        brand: "Kroger",
        name: "Peanuts lightly salted",
        servingSize: "28 g",
        servingsPerContainer: 16,
        calories: 160,
        caloriesFromFat: 130,
        fat: 14,
        fatSaturated: 2,
        fatTrans: 0,
        fatPolyunsat: 4.5,
        fatMonounsat: 7,
        cholesterol: 0,
        sodium: 85,
        potassium: 180,
        carbs: 6,
        carbsDietaryFiber: 2,
        carbsSugars: 1,
        protein: 6
    },
    {
        type: FoodType.NUTS,
        brand: "Kroger",
        name: "Peanuts unsalted",
        servingSize: "1 oz",
        servingsPerContainer: 16,
        calories: 160,
        caloriesFromFat: 130,
        fat: 14,
        fatSaturated: 2,
        fatTrans: 0,
        fatPolyunsat: 4.5,
        fatMonounsat: 7,
        cholesterol: 0,
        sodium: 0,
        potassium: 0,
        carbs: 6,
        carbsDietaryFiber: 2,
        carbsSugars: 1,
        protein: 7
    },
    {
        type: FoodType.NUTS,
        brand: "Blue Diamond",
        name: "Almonds Bold Habanero BBQ",
        servingSize: "1 oz",
        servingsPerContainer: 6,
        calories: 170,
        caloriesFromFat: 140,
        fat: 15,
        fatSaturated: 1,
        fatTrans: 0,
        fatPolyunsat: 0,
        fatMonounsat: 0,
        cholesterol: 0,
        sodium: 100,
        potassium: 180,
        carbs: 5,
        carbsDietaryFiber: 3,
        carbsSugars: 2,
        protein: 6
    },
    // /////////////////////////////////////////////////////////////////////////
    // Oil.
    {
        type: FoodType.OIL,
        brand: "Kroger",
        name: "Kansas City style BBQ sauce",
        servingSize: "2 tbsp",
        servingsPerContainer: 15,
        calories: 50,
        caloriesFromFat: 0,
        fat: 0,
        fatSaturated: 0,
        fatTrans: 0,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 0,
        sodium: 280,
        potassium: undefined,
        carbs: 12,
        carbsDietaryFiber: 0,
        carbsSugars: 11,
        protein: 1
    },
    {
        type: FoodType.OIL,
        brand: "Kroger",
        name: "Kansas City style Hickory Smoke BBQ sauce",
        servingSize: "2 tbsp",
        servingsPerContainer: 15,
        calories: 50,
        caloriesFromFat: 0,
        fat: 0,
        fatSaturated: 0,
        fatTrans: 0,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 0,
        sodium: 250,
        potassium: undefined,
        carbs: 12,
        carbsDietaryFiber: 0,
        carbsSugars: 6,
        protein: 1
    },
    {
        type: FoodType.OIL,
        brand: "Kroger",
        name: "Lite Soy sauce",
        servingSize: "1 tbsp",
        servingsPerContainer: 30,
        calories: 15,
        caloriesFromFat: undefined,
        fat: 0,
        fatSaturated: undefined,
        fatTrans: undefined,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: undefined,
        sodium: 530,
        potassium: undefined,
        carbs: 3,
        carbsDietaryFiber: undefined,
        carbsSugars: 2,
        protein: 1,
    },
    {
        type: FoodType.OIL,
        brand: "Mrs Dash",
        name: "Tomato Basil Garlic",
        servingSize: "1/4 tsp",
        servingsPerContainer: 96,
        calories: 0,
        caloriesFromFat: undefined,
        fat: 0,
        fatSaturated: undefined,
        fatTrans: 0,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: undefined,
        sodium: 0,
        potassium: 5,
        carbs: 0,
        carbsDietaryFiber: undefined,
        carbsSugars: undefined,
        protein: 0,
    },
    // /////////////////////////////////////////////////////////////////////////
    // Prepared.
    {
        type: FoodType.PREPARED,
        brand: "Banquet",
        name: "Beef Pot Pie",
        servingSize: "1",
        servingsPerContainer: 1,
        calories: 430,
        caloriesFromFat: 240,
        fat: 27,
        fatSaturated: 10,
        fatTrans: 0.5,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 30,
        sodium: 700,
        potassium: 210,
        carbs: 37,
        carbsDietaryFiber: 2,
        carbsSugars: 2,
        protein: 10,
    },
    {
        type: FoodType.PREPARED,
        brand: "Banquet",
        name: "Salisbury Steak Pot Pie",
        servingSize: "1",
        servingsPerContainer: 1,
        calories: 400,
        caloriesFromFat: 210,
        fat: 23,
        fatSaturated: 8,
        fatTrans: 0,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 30,
        sodium: 780,
        potassium: 190,
        carbs: 40,
        carbsDietaryFiber: 4,
        carbsSugars: 4,
        protein: 9,
    },
    {
        type: FoodType.PREPARED,
        brand: "Chef Boyardee",
        name: "Mini Ravioli",
        servingSize: "1 cup",
        servingsPerContainer: 2,
        calories: 220,
        caloriesFromFat: 60,
        fat: 7,
        fatSaturated: 3,
        fatTrans: 0,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 10,
        sodium: 750,
        potassium: 620,
        carbs: 32,
        carbsDietaryFiber: 3,
        carbsSugars: 6,
        protein: 7,
        useContainer: true
    },
    {
        type: FoodType.PREPARED,
        brand: "Chipotle",
        name: "Barbacoa Burrito Bowl",
        servingSize: "21 oz",
        servingsPerContainer: undefined,
        calories: 655,
        caloriesFromFat: 196.5,
        fat: 21,
        fatSaturated: 8.5,
        fatTrans: 0,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 95,
        sodium: 1885,
        potassium: undefined,
        carbs: 72,
        carbsDietaryFiber: 19,
        carbsSugars: 5,
        protein: 43
    },
    {
        type: FoodType.PREPARED,
        brand: "Chipotle",
        name: "Carnitas Burrito Bowl",
        servingSize: "21 oz",
        servingsPerContainer: undefined,
        calories: 700,
        caloriesFromFat: 241.5,
        fat: 26,
        fatSaturated: 12.5,
        fatTrans: 0,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 95,
        sodium: 1805,
        potassium: undefined,
        carbs: 70,
        carbsDietaryFiber: 18,
        carbsSugars: 5,
        protein: 42
    },
    {
        type: FoodType.PREPARED,
        brand: "Hormel",
        name: "Hot with Beans chili",
        servingSize: "1 cup",
        servingsPerContainer: 2,
        calories: 260,
        caloriesFromFat: 60,
        fat: 7,
        fatSaturated: 3,
        fatTrans: 0,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 30,
        sodium: 1060,
        potassium: undefined,
        carbs: 33,
        carbsDietaryFiber: 7,
        carbsSugars: 5,
        protein: 16,
        useContainer: true
    },
    {
        type: FoodType.PREPARED,
        brand: "Hormel",
        name: "Homestyle with Beans chili",
        servingSize: "1 cup",
        servingsPerContainer: 2,
        calories: 350,
        caloriesFromFat: 170,
        fat: 19,
        fatSaturated: 8,
        fatTrans: 1,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 40,
        sodium: 1020,
        potassium: undefined,
        carbs: 28,
        carbsDietaryFiber: 6,
        carbsSugars: 6,
        protein: 16,
        useContainer: true
    },
    {
        type: FoodType.PREPARED,
        brand: "Hormel",
        name: "Hot with Beans chili",
        servingSize: "1 cup",
        servingsPerContainer: 2,
        calories: 260,
        caloriesFromFat: 60,
        fat: 7,
        fatSaturated: 3,
        fatTrans: 0,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 30,
        sodium: 1060,
        potassium: undefined,
        carbs: 33,
        carbsDietaryFiber: 7,
        carbsSugars: 5,
        protein: 16,
        useContainer: true
    },
    {
        type: FoodType.PREPARED,
        brand: "Hormel",
        name: "Turkey with Beans chili",
        servingSize: "1 cup",
        servingsPerContainer: 2,
        calories: 210,
        caloriesFromFat: 25,
        fat: 3,
        fatSaturated: 1,
        fatTrans: 0,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 45,
        sodium: 1250,
        potassium: undefined,
        carbs: 28,
        carbsDietaryFiber: 6,
        carbsSugars: 6,
        protein: 17,
        useContainer: true
    },
    {
        type: FoodType.PREPARED,
        brand: "Lean Cuisine",
        name: "Deep Dish Spinach & Mushroom Pizza",
        servingSize: "1 package",
        servingsPerContainer: 1,
        calories: 350,
        caloriesFromFat: 60,
        fat: 7,
        fatSaturated: 3.5,
        fatTrans: 0,
        fatPolyunsat: 1.5,
        fatMonounsat: 1.5,
        cholesterol: 15,
        sodium: 420,
        potassium: 220,
        carbs: 54,
        carbsDietaryFiber: 3,
        carbsSugars: 5,
        protein: 17
    },
    {
        type: FoodType.PREPARED,
        brand: "Lean Cuisine",
        name: "Deep Dish Three Meat Pizza",
        servingSize: "1 package",
        servingsPerContainer: 1,
        calories: 390,
        caloriesFromFat: 80,
        fat: 9,
        fatSaturated: 3,
        fatTrans: 0,
        fatPolyunsat: 2,
        fatMonounsat: 3,
        cholesterol: 25,
        sodium: 630,
        potassium: 350,
        carbs: 56,
        carbsDietaryFiber: 3,
        carbsSugars: 6,
        protein: 22
    },
    {
        type: FoodType.PREPARED,
        brand: "Lean Cuisine",
        name: "Five Cheese Rigatoni",
        servingSize: "1 package",
        servingsPerContainer: 1,
        calories: 360,
        caloriesFromFat: 70,
        fat: 8,
        fatSaturated: 4,
        fatTrans: 0,
        fatPolyunsat: 2,
        fatMonounsat: 2,
        cholesterol: 15,
        sodium: 560,
        potassium: 320,
        carbs: 56,
        carbsDietaryFiber: 4,
        carbsSugars: 7,
        protein: 15
    },
    {
        type: FoodType.PREPARED,
        brand: "Lean Cuisine",
        name: "Lasagna with Meat Sauce",
        servingSize: "1 package",
        servingsPerContainer: 1,
        calories: 320,
        caloriesFromFat: 70,
        fat: 8,
        fatSaturated: 4,
        fatTrans: 0,
        fatPolyunsat: 1,
        fatMonounsat: 2,
        cholesterol: 25,
        sodium: 650,
        potassium: 650,
        carbs: 45,
        carbsDietaryFiber: 4,
        carbsSugars: 9,
        protein: 18
    },
    {
        type: FoodType.PREPARED,
        brand: "Lean Cuisine",
        name: "Margherita Pizza",
        servingSize: "1 package",
        servingsPerContainer: 1,
        calories: 320,
        caloriesFromFat: 60,
        fat: 7,
        fatSaturated: 3,
        fatTrans: 0,
        fatPolyunsat: 2,
        fatMonounsat: 2,
        cholesterol: 15,
        sodium: 525,
        potassium: 320,
        carbs: 48,
        carbsDietaryFiber: 3,
        carbsSugars: 7,
        protein: 16,
    },
    {
        type: FoodType.PREPARED,
        brand: "Lean Cuisine",
        name: "Mushroom & Spring Pea Risotto",
        servingSize: "1 package",
        servingsPerContainer: 1,
        calories: 240,
        caloriesFromFat: 70,
        fat: 7,
        fatSaturated: 4,
        fatTrans: 0,
        fatPolyunsat: 0.5,
        fatMonounsat: 2,
        cholesterol: 20,
        sodium: 640,
        potassium: 250,
        carbs: 37,
        carbsDietaryFiber: 3,
        carbsSugars: 1,
        protein: 7
    },
    {
        type: FoodType.PREPARED,
        brand: "Lean Cuisine",
        name: "Ricotta Cheese & Spinach Ravioli",
        servingSize: "1 package",
        servingsPerContainer: 1,
        calories: 310,
        caloriesFromFat: 60,
        fat: 7,
        fatSaturated: 3,
        fatTrans: 0,
        fatPolyunsat: 0.5,
        fatMonounsat: 2.5,
        cholesterol: 20,
        sodium: 690,
        potassium: 620,
        carbs: 51,
        carbsDietaryFiber: 4,
        carbsSugars: 11,
        protein: 10,
    },
    {
        type: FoodType.PREPARED,
        brand: "Lean Cuisine",
        name: "Salisbury Steak with Macaroni & Cheese",
        servingSize: "1 package",
        servingsPerContainer: 1,
        calories: 270,
        caloriesFromFat: 80,
        fat: 9,
        fatSaturated: 4,
        fatTrans: 0,
        fatPolyunsat: 1,
        fatMonounsat: 3,
        cholesterol: 40,
        sodium: 590,
        potassium: 740,
        carbs: 25,
        carbsDietaryFiber: 3,
        carbsSugars: 3,
        protein: 22
    },
    {
        type: FoodType.PREPARED,
        brand: "Lean Cuisine",
        name: "Santa Fe-Style Rice & Beans",
        servingSize: "1 package",
        servingsPerContainer: 1,
        calories: 290,
        caloriesFromFat: 40,
        fat: 4.5,
        fatSaturated: 2,
        fatTrans: 0,
        fatPolyunsat: 1,
        fatMonounsat: 1,
        cholesterol: 15,
        sodium: 490,
        potassium: 570,
        carbs: 52,
        carbsDietaryFiber: 4,
        carbsSugars: 8,
        protein: 10
    },
    {
        type: FoodType.PREPARED,
        brand: "Lean Cuisine",
        name: "Spaghetti with Meat Sauce",
        servingSize: "1 package",
        servingsPerContainer: 1,
        calories: 310,
        caloriesFromFat: 35,
        fat: 4,
        fatSaturated: 1.5,
        fatTrans: 0,
        fatPolyunsat: 1,
        fatMonounsat: 1,
        cholesterol: 10,
        sodium: 520,
        potassium: 450,
        carbs: 53,
        carbsDietaryFiber: 4,
        carbsSugars: 8,
        protein: 15
    },
    {
        type: FoodType.PREPARED,
        brand: "Lean Cuisine",
        name: "Spicy Mexican Black Beans & Rice",
        servingSize: "1 package",
        servingsPerContainer: 1,
        calories: 280,
        caloriesFromFat: 70,
        fat: 5,
        fatSaturated: 2,
        fatTrans: 0,
        fatPolyunsat: 0.5,
        fatMonounsat: 3,
        cholesterol: 10,
        sodium: 690,
        potassium: 460,
        carbs: 46,
        carbsDietaryFiber: 4,
        carbsSugars: 7,
        protein: 8
    },
    {
        type: FoodType.PREPARED,
        brand: "Lean Cuisine",
        name: "Spinach Artichoke Ravioli",
        servingSize: "1 package",
        servingsPerContainer: 1,
        calories: 280,
        caloriesFromFat: 60,
        fat: 5,
        fatSaturated: 3.5,
        fatTrans: 0,
        fatPolyunsat: 1.5,
        fatMonounsat: 1.5,
        cholesterol: 30,
        sodium: 690,
        potassium: 580,
        carbs: 41,
        carbsDietaryFiber: 4,
        carbsSugars: 9,
        protein: 12
    },
    {
        type: FoodType.PREPARED,
        brand: "Lean Cuisine",
        name: "Supreme Pizza",
        servingSize: "1 package",
        servingsPerContainer: 1,
        calories: 340,
        caloriesFromFat: 70,
        fat: 8,
        fatSaturated: 3,
        fatTrans: 0,
        fatPolyunsat: 2,
        fatMonounsat: 3,
        cholesterol: 20,
        sodium: 470,
        potassium: 480,
        carbs: 50,
        carbsDietaryFiber: 4,
        carbsSugars: 7,
        protein: 16
    },
    {
        type: FoodType.PREPARED,
        brand: "Lean Cuisine",
        name: "Sweet Sriracha Braised Beef",
        servingSize: "1 package",
        servingsPerContainer: 1,
        calories: 170,
        caloriesFromFat: 40,
        fat: 4.5,
        fatSaturated: 2,
        fatTrans: 0,
        fatPolyunsat: 0.5,
        fatMonounsat: 1.5,
        cholesterol: 30,
        sodium: 550,
        potassium: 430,
        carbs: 18,
        carbsDietaryFiber: 3,
        carbsSugars: 11,
        protein: 15
    },
    {
        type: FoodType.PREPARED,
        brand: "Lean Cuisine",
        name: "Tortilla Crusted Fish",
        servingSize: "1 package",
        servingsPerContainer: 1,
        calories: 300,
        caloriesFromFat: 80,
        fat: 9,
        fatSaturated: 2,
        fatTrans: 0,
        fatPolyunsat: 4.5,
        fatMonounsat: 2,
        cholesterol: 30,
        sodium: 490,
        potassium: 600,
        carbs: 41,
        carbsDietaryFiber: 2,
        carbsSugars: 6,
        protein: 14
    },
    {
        type: FoodType.PREPARED,
        brand: "Wolf",
        name: "Turkey with Beans chili",
        servingSize: "1 cup",
        servingsPerContainer: 2,
        calories: 250,
        caloriesFromFat: 50,
        fat: 5,
        fatSaturated: 1.5,
        fatTrans: 0,
        fatPolyunsat: 2,
        fatMonounsat: 2,
        cholesterol: 25,
        sodium: 910,
        potassium: 620,
        carbs: 33,
        carbsDietaryFiber: 8,
        carbsSugars: 3,
        protein: 17,
        useContainer: true
    },
    // /////////////////////////////////////////////////////////////////////////
    // Soup.
    {
        type: FoodType.SOUP,
        brand: "Campbell's",
        name: "Bean with Bacon",
        servingSize: "1/2 cup",
        servingsPerContainer: 2.5,
        calories: 160,
        caloriesFromFat: 30,
        fat: 3,
        fatSaturated: 1,
        fatTrans: 0,
        fatPolyunsat: 0.5,
        fatMonounsat: 1,
        cholesterol: 5,
        sodium: 870,
        potassium: 480,
        carbs: 26,
        carbsDietaryFiber: 8,
        carbsSugars: 4,
        protein: 7,
        useContainer: true
    },
    {
        type: FoodType.SOUP,
        brand: "Campbell's",
        name: "Vegetable Beef",
        servingSize: "1/2 cup",
        servingsPerContainer: 2.5,
        calories: 90,
        caloriesFromFat: 10,
        fat: 1,
        fatSaturated: 0.5,
        fatTrans: 0,
        fatPolyunsat: 0,
        fatMonounsat: 0,
        cholesterol: 5,
        sodium: 890,
        potassium: 260,
        carbs: 15,
        carbsDietaryFiber: 3,
        carbsSugars: 2,
        protein: 4,
        useContainer: true
    },
    {
        type: FoodType.SOUP,
        brand: "Campbell's Chunky",
        name: "Grilled Sirloin Steak",
        servingSize: "1 cup",
        servingsPerContainer: 2,
        calories: 120,
        caloriesFromFat: 20,
        fat: 2,
        fatSaturated: 1,
        fatTrans: 0,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 10,
        sodium: 890,
        potassium: undefined,
        carbs: 19,
        carbsDietaryFiber: 2,
        carbsSugars: 4,
        protein: 7,
        useContainer: true
    },
    {
        type: FoodType.SOUP,
        brand: "Campbell's Chunky",
        name: "Hearty Bean and Ham",
        servingSize: "1 cup",
        servingsPerContainer: 2,
        calories: 170,
        caloriesFromFat: 15,
        fat: 1.5,
        fatSaturated: 0.5,
        fatTrans: 0,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 10,
        sodium: 780,
        potassium: undefined,
        carbs: 30,
        carbsDietaryFiber: 8,
        carbsSugars: 6,
        protein: 8,
        useContainer: true
    },
    {
        type: FoodType.SOUP,
        brand: "Campbell's Chunky",
        name: "Philly-Style Cheesesteak",
        servingSize: "1 cup",
        servingsPerContainer: 2,
        calories: 150,
        caloriesFromFat: 80,
        fat: 9,
        fatSaturated: 2.5,
        fatTrans: 0,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 20,
        sodium: 790,
        potassium: undefined,
        carbs: 12,
        carbsDietaryFiber: 1,
        carbsSugars: 2,
        protein: 6,
        useContainer: true
    },
    {
        type: FoodType.SOUP,
        brand: "Campbell's Chunky",
        name: "Hearty Italian-Style Wedding",
        servingSize: "1 cup",
        servingsPerContainer: 2,
        calories: 120,
        caloriesFromFat: 30,
        fat: 3,
        fatSaturated: 1,
        fatTrans: 0,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 20,
        sodium: 790,
        potassium: undefined,
        carbs: 15,
        carbsDietaryFiber: 2,
        carbsSugars: 4,
        protein: 7,
        useContainer: true
    },
    {
        type: FoodType.SOUP,
        brand: "Campbell's Chunky Healthy Request",
        name: "Beef with Country Vegetables",
        servingSize: "1 cup",
        servingsPerContainer: 2,
        calories: 110,
        caloriesFromFat: 15,
        fat: 1.5,
        fatSaturated: 0.5,
        fatTrans: 0,
        fatPolyunsat: 0,
        fatMonounsat: 0,
        cholesterol: 10,
        sodium: 410,
        potassium: 1220,
        carbs: 17,
        carbsDietaryFiber: 3,
        carbsSugars: 4,
        protein: 6,
        useContainer: true
    },
    {
        type: FoodType.SOUP,
        brand: "Campbell's Chunky Healthy Request",
        name: "Grilled Chicken & Sausage Gumbo",
        servingSize: "1 cup",
        servingsPerContainer: 2,
        calories: 140,
        caloriesFromFat: 30,
        fat: 3,
        fatSaturated: 1,
        fatTrans: 0,
        fatPolyunsat: 0.5,
        fatMonounsat: 1.5,
        cholesterol: 15,
        sodium: 410,
        potassium: 720,
        carbs: 22,
        carbsDietaryFiber: 3,
        carbsSugars: 4,
        protein: 6,
        useContainer: true
    },
    {
        type: FoodType.SOUP,
        brand: "Campbell's Chunky Healthy Request",
        name: "Sirloin Burger",
        servingSize: "1 cup",
        servingsPerContainer: 2,
        calories: 130,
        caloriesFromFat: 20,
        fat: 2,
        fatSaturated: 1,
        fatTrans: 0,
        fatPolyunsat: 0,
        fatMonounsat: 1,
        cholesterol: 15,
        sodium: 410,
        potassium: 1080,
        carbs: 19,
        carbsDietaryFiber: 3,
        carbsSugars: 4,
        protein: 8,
        useContainer: true
    },
    {
        type: FoodType.SOUP,
        brand: "Campbell's Chunky Healthy Request",
        name: "Split Pea & Ham",
        servingSize: "1 cup",
        servingsPerContainer: 2,
        calories: 160,
        caloriesFromFat: 25,
        fat: 2.5,
        fatSaturated: 1,
        fatTrans: 0,
        fatPolyunsat: 0.5,
        fatMonounsat: 1,
        cholesterol: 10,
        sodium: 410,
        potassium: 1080,
        carbs: 22,
        carbsDietaryFiber: 5,
        carbsSugars: 4,
        protein: 12,
        useContainer: true
    },
    {
        type: FoodType.SOUP,
        brand: "Campbell's Chunky Healthy Request",
        name: "New England Clam Chowder",
        servingSize: "1 cup",
        servingsPerContainer: 2,
        calories: 130,
        caloriesFromFat: 30,
        fat: 3,
        fatSaturated: 1,
        fatTrans: 0,
        fatPolyunsat: 1,
        fatMonounsat: 0.5,
        cholesterol: 10,
        sodium: 410,
        potassium: 1000,
        carbs: 20,
        carbsDietaryFiber: 2,
        carbsSugars: 2,
        protein: 5,
        useContainer: true
    },
    {
        type: FoodType.SOUP,
        brand: "Campbell's Chunky Healthy Request",
        name: "Old Fashioned Vegetable Beef",
        servingSize: "1 cup",
        servingsPerContainer: 2,
        calories: 120,
        caloriesFromFat: 15,
        fat: 3,
        fatSaturated: undefined,
        fatTrans: undefined,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: undefined,
        sodium: 410,
        potassium: undefined,
        carbs: 19,
        carbsDietaryFiber: 3,
        carbsSugars: 4,
        protein: 6,
        useContainer: true
    },
    {
        type: FoodType.SOUP,
        brand: "Campbell's Chunky Healthy Request",
        name: "Hearty Italian-Style Wedding",
        servingSize: "1 cup",
        servingsPerContainer: 2,
        calories: 130,
        caloriesFromFat: 25,
        fat: 3,
        fatSaturated: undefined,
        fatTrans: undefined,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: undefined,
        sodium: 410,
        potassium: undefined,
        carbs: 20,
        carbsDietaryFiber: 3,
        carbsSugars: 7,
        protein: 7,
        useContainer: true
    },
    {
        type: FoodType.SOUP,
        brand: "Campbell's Chunky",
        name: "Hearty Beef Barley",
        servingSize: "1 cup",
        servingsPerContainer: 2,
        calories: 140,
        caloriesFromFat: 10,
        fat: 1,
        fatSaturated: 0.5,
        fatTrans: 0,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 10,
        sodium: 790,
        potassium: undefined,
        carbs: 24,
        carbsDietaryFiber: 4,
        carbsSugars: 6,
        protein: 8,
        useContainer: true
    },
    {
        type: FoodType.SOUP,
        brand: "Campbell's Chunky",
        name: "Hearty Tomato Pasta",
        servingSize: "1 cup",
        servingsPerContainer: 2,
        calories: 150,
        caloriesFromFat: 10,
        fat: 1,
        fatSaturated: undefined,
        fatTrans: undefined,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 5,
        sodium: 650,
        potassium: 0,
        carbs: 30,
        carbsDietaryFiber: 3,
        carbsSugars: 19,
        protein: 4,
        useContainer: true
    },
    {
        type: FoodType.SOUP,
        brand: "Campbell's Chunky",
        name: "Sausage & Pepper Rigatoni",
        servingSize: "1 cup",
        servingsPerContainer: 2,
        calories: 190,
        caloriesFromFat: 70,
        fat: 8,
        fatSaturated: 3,
        fatTrans: 0,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 15,
        sodium: 790,
        potassium: undefined,
        carbs: 22,
        carbsDietaryFiber: 3,
        carbsSugars: 8,
        protein: 8,
        useContainer: true
    },
    {
        type: FoodType.SOUP,
        brand: "Campbell's Chunky",
        name: "Slow Roasted Beef with Mushrooms",
        servingSize: "1 cup",
        servingsPerContainer: 2,
        calories: 110,
        caloriesFromFat: 10,
        fat: 1,
        fatSaturated: 0.5,
        fatTrans: 0,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 15,
        sodium: 790,
        potassium: undefined,
        carbs: 18,
        carbsDietaryFiber: 2,
        carbsSugars: 5,
        protein: 8,
        useContainer: true
    },
    {
        type: FoodType.SOUP,
        brand: "Campbell's",
        name: "Split Pea with Ham & Bacon",
        servingSize: "1/2 cup",
        servingsPerContainer: 2.5,
        calories: 180,
        caloriesFromFat: 20,
        fat: 2,
        fatSaturated: 0.5,
        fatTrans: 0,
        fatPolyunsat: 0.5,
        fatMonounsat: 1,
        cholesterol: 5,
        sodium: 850,
        potassium: 450,
        carbs: 29,
        carbsDietaryFiber: 5,
        carbsSugars: 4,
        protein: 11,
        useContainer: true
    },
    {
        type: FoodType.SOUP,
        brand: "Campbell's Healthy Request",
        name: "Bean with Bacon",
        servingSize: "1/2 cup",
        servingsPerContainer: 2.5,
        calories: 160,
        caloriesFromFat: 30,
        fat: 3,
        fatSaturated: 1,
        fatTrans: 0,
        fatPolyunsat: 1,
        fatMonounsat: 1,
        cholesterol: 5,
        sodium: 410,
        potassium: 950,
        carbs: 25,
        carbsDietaryFiber: 9,
        carbsSugars: 5,
        protein: 8,
        useContainer: true
    },
    {
        type: FoodType.SOUP,
        brand: "Campbell's Healthy Request",
        name: "Minestrone",
        servingSize: "1/2 cup",
        servingsPerContainer: 2.5,
        calories: 90,
        caloriesFromFat: 5,
        fat: 0.5,
        fatSaturated: 0,
        fatTrans: 0,
        fatPolyunsat: 0,
        fatMonounsat: 0,
        cholesterol: 0,
        sodium: 410,
        potassium: 1030,
        carbs: 19,
        carbsDietaryFiber: 3,
        carbsSugars: 5,
        protein: 4,
        useContainer: true
    },
    {
        type: FoodType.SOUP,
        brand: "Campbell's Healthy Request",
        name: "Southwest-style Bean & Barley",
        servingSize: "1/2 cup",
        servingsPerContainer: 2.5,
        calories: 90,
        caloriesFromFat: 5,
        fat: 0.5,
        fatSaturated: 0,
        fatTrans: 0,
        fatPolyunsat: 0,
        fatMonounsat: 0,
        cholesterol: 0,
        sodium: 410,
        potassium: 550,
        carbs: 18,
        carbsDietaryFiber: 3,
        carbsSugars: 2,
        protein: 3,
        useContainer: true
    },
    {
        type: FoodType.SOUP,
        brand: "Campbell's Healthy Request",
        name: "Tomato",
        servingSize: "1/2 cup",
        servingsPerContainer: 2.5,
        calories: 90,
        caloriesFromFat: 15,
        fat: 1.5,
        fatSaturated: 0.5,
        fatTrans: 0,
        fatPolyunsat: 0.5,
        fatMonounsat: 0,
        cholesterol: 0,
        sodium: 410,
        potassium: 700,
        carbs: 17,
        carbsDietaryFiber: 1,
        carbsSugars: 10,
        protein: 2,
        useContainer: true
    },
    {
        type: FoodType.SOUP,
        brand: "Campbell's Healthy Request",
        name: "Tuscan-Style Lentil",
        servingSize: "1/2 cup",
        servingsPerContainer: 2.5,
        calories: 140,
        caloriesFromFat: 5,
        fat: 0.5,
        fatSaturated: 0,
        fatTrans: 0,
        fatPolyunsat: 0,
        fatMonounsat: 0,
        cholesterol: 0,
        sodium: 410,
        potassium: 820,
        carbs: 25,
        carbsDietaryFiber: 4,
        carbsSugars: 3,
        protein: 8,
        useContainer: true
    },
    {
        type: FoodType.SOUP,
        brand: "Campbell's",
        name: "Manhattan Clam Chowder",
        servingSize: "1/2 cup",
        servingsPerContainer: 2.5,
        calories: 60,
        caloriesFromFat: 5,
        fat: 0.5,
        fatSaturated: 0,
        fatTrans: 0,
        fatPolyunsat: 0,
        fatMonounsat: 0,
        cholesterol: 0,
        sodium: 890,
        potassium: 210,
        carbs: 12,
        carbsDietaryFiber: 1,
        carbsSugars: 2,
        protein: 2,
        useContainer: true
    },
    {
        type: FoodType.SOUP,
        brand: "Campbell's",
        name: "Old Fashioned Vegetable",
        servingSize: "1/2 cup",
        servingsPerContainer: 2.5,
        calories: 80,
        caloriesFromFat: 15,
        fat: 1.5,
        fatSaturated: 0,
        fatTrans: 0,
        fatPolyunsat: 0.5,
        fatMonounsat: 0,
        cholesterol: 0,
        sodium: 890,
        potassium: 170,
        carbs: 14,
        carbsDietaryFiber: 2,
        carbsSugars: 2,
        protein: 2,
        useContainer: true
    },
    {
        type: FoodType.SOUP,
        brand: "Campbell's",
        name: "Beef with Vegetables & Barley",
        servingSize: "1/2 cup",
        servingsPerContainer: 2.5,
        calories: 80,
        caloriesFromFat: 10,
        fat: 1,
        fatSaturated: 0.5,
        fatTrans: 0,
        fatPolyunsat: 0,
        fatMonounsat: 0.5,
        cholesterol: 5,
        sodium: 890,
        potassium: 150,
        carbs: 15,
        carbsDietaryFiber: 3,
        carbsSugars: 2,
        protein: 3,
        useContainer: true
    },
    {
        type: FoodType.SOUP,
        brand: "Progresso",
        name: "Italian-Style Wedding",
        servingSize: "1 cup",
        servingsPerContainer: 2,
        calories: 120,
        caloriesFromFat: 35,
        fat: 4,
        fatSaturated: 1.5,
        fatTrans: 0,
        fatPolyunsat: 0.5,
        fatMonounsat: 1.5,
        cholesterol: 15,
        sodium: 690,
        potassium: 290,
        carbs: 15,
        carbsDietaryFiber: 2,
        carbsSugars: 1,
        protein: 7,
        useContainer: true
    },
    {
        type: FoodType.SOUP,
        brand: "Progresso",
        name: "Lentil",
        servingSize: "1 cup",
        servingsPerContainer: 2,
        calories: 160,
        caloriesFromFat: 20,
        fat: 2,
        fatSaturated: 0.5,
        fatTrans: 0,
        fatPolyunsat: 1,
        fatMonounsat: 0.5,
        cholesterol: 0,
        sodium: 810,
        potassium: undefined,
        carbs: 30,
        carbsDietaryFiber: 5,
        carbsSugars: 2,
        protein: 9,
        useContainer: true
    },
    {
        type: FoodType.SOUP,
        brand: "Progresso",
        name: "Minestrone",
        servingSize: "1 cup",
        servingsPerContainer: 2,
        calories: 100,
        caloriesFromFat: 15,
        fat: 2,
        fatSaturated: 0.5,
        fatTrans: 0,
        fatPolyunsat: 1,
        fatMonounsat: 0.5,
        cholesterol: 0,
        sodium: 690,
        potassium: 630,
        carbs: 20,
        carbsDietaryFiber: 4,
        carbsSugars: 3,
        protein: 4,
        useContainer: true
    },
    {
        type: FoodType.SOUP,
        brand: "Progresso",
        name: "New England Clam Chowder",
        servingSize: "1 cup",
        servingsPerContainer: 2,
        calories: 180,
        caloriesFromFat: 70,
        fat: 8,
        fatSaturated: 2,
        fatTrans: 0,
        fatPolyunsat: 4,
        fatMonounsat: 2,
        cholesterol: 15,
        sodium: 890,
        potassium: 600,
        carbs: 20,
        carbsDietaryFiber: 1,
        carbsSugars: 2,
        protein: 6,
        useContainer: true
    },
    {
        type: FoodType.SOUP,
        brand: "Progresso Heart Healthy",
        name: "Southwest Style Black Bean & Vegetable",
        servingSize: "1 cup",
        servingsPerContainer: 2,
        calories: 110,
        caloriesFromFat: 15,
        fat: 2,
        fatSaturated: 0.5,
        fatTrans: 0,
        fatPolyunsat: 0.5,
        fatMonounsat: 0.5,
        cholesterol: 0,
        sodium: 480,
        potassium: 710,
        carbs: 21,
        carbsDietaryFiber: 6,
        carbsSugars: 3,
        protein: 5,
        useContainer: true
    },
    {
        type: FoodType.SOUP,
        brand: "Progresso Light",
        name: "Creamy Potato with Bacon & Cheese",
        servingSize: "1 cup",
        servingsPerContainer: 2,
        calories: 100,
        caloriesFromFat: 25,
        fat: 3,
        fatSaturated: 1,
        fatTrans: 0,
        fatPolyunsat: 1,
        fatMonounsat: 0.5,
        cholesterol: 5,
        sodium: 690,
        potassium: undefined,
        carbs: 15,
        carbsDietaryFiber: 2,
        carbsSugars: 2,
        protein: 2,
        useContainer: true
    },
    {
        type: FoodType.SOUP,
        brand: "Progresso Light",
        name: "Italian Style Meatball",
        servingSize: "1 cup",
        servingsPerContainer: 2,
        calories: 80,
        caloriesFromFat: 20,
        fat: 3,
        fatSaturated: 1,
        fatTrans: 0,
        fatPolyunsat: 0,
        fatMonounsat: 0.5,
        cholesterol: 5,
        sodium: 480,
        potassium: 630,
        carbs: 13,
        carbsDietaryFiber: 2,
        carbsSugars: 5,
        protein: 3,
        useContainer: true
    },
    {
        type: FoodType.SOUP,
        brand: "Progresso Light",
        name: "Southwestern-Style Vegetable",
        servingSize: "1 cup",
        servingsPerContainer: 2,
        calories: 60,
        caloriesFromFat: 5,
        fat: 1,
        fatSaturated: 0,
        fatTrans: 0,
        fatPolyunsat: 0,
        fatMonounsat: 0,
        cholesterol: 0,
        sodium: 470,
        potassium: 500,
        carbs: 12,
        carbsDietaryFiber: 4,
        carbsSugars: 3,
        protein: 3,
        useContainer: true
    },
    // /////////////////////////////////////////////////////////////////////////
    // Supplement.
    {
        type: FoodType.SUPPLEMENT,
        brand: "Bausch + Lomb",
        name: "PreserVision AREDS 2",
        servingSize: "2 soft gels",
        servingsPerContainer: 60,
        calories: 10,
        caloriesFromFat: 5,
        fat: 0.5,
        fatSaturated: undefined,
        fatTrans: undefined,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: undefined,
        sodium: undefined,
        potassium: undefined,
        carbs: undefined,
        carbsDietaryFiber: undefined,
        carbsSugars: undefined,
        protein: undefined
    },
    {
        type: FoodType.SUPPLEMENT,
        brand: "Nature Made",
        name: "Burp-Less Fish Oil",
        servingSize: "2 soft gels",
        servingsPerContainer: 75,
        calories: 20,
        caloriesFromFat: 15,
        fat: 2,
        fatSaturated: undefined,
        fatTrans: undefined,
        fatPolyunsat: 0.5,
        fatMonounsat: undefined,
        cholesterol: 20,
        sodium: undefined,
        potassium: undefined,
        carbs: 1,
        carbsDietaryFiber: undefined,
        carbsSugars: undefined,
        protein: 1
    },
    // /////////////////////////////////////////////////////////////////////////
    // Vegetable.
    {
        type: FoodType.VEGETABLE,
        brand: "Deli Salsa",
        name: "Medium",
        servingSize: "2 Tbsp",
        servingsPerContainer: 15,
        calories: 5,
        caloriesFromFat: 0,
        fat: 0,
        fatSaturated: 0,
        fatTrans: 0,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 0,
        sodium: 140,
        potassium: undefined,
        carbs: 2,
        carbsDietaryFiber: 0,
        carbsSugars: 1,
        protein: 0,
    },
    {
        type: FoodType.VEGETABLE,
        brand: "Doritos",
        name: "Nacho Cheese",
        servingSize: "28 g",
        servingsPerContainer: 11,
        calories: 140,
        caloriesFromFat: 70,
        fat: 8,
        fatSaturated: 1,
        fatTrans: 0,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 0,
        sodium: 210,
        potassium: undefined,
        carbs: 16,
        carbsDietaryFiber: 1,
        carbsSugars: 0,
        protein: 2
    },
    {
        type: FoodType.VEGETABLE,
        brand: "Frito-Lay",
        name: "Nacho Cheese Doritos",
        servingSize: "1 oz",
        servingsPerContainer: 11,
        calories: 140,
        caloriesFromFat: 70,
        fat: 8,
        fatSaturated: undefined,
        fatTrans: undefined,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: undefined,
        sodium: 210,
        potassium: undefined,
        carbs: 16,
        carbsDietaryFiber: 1,
        carbsSugars: 0,
        protein: 2
    },
    {
        type: FoodType.VEGETABLE,
        brand: "Fritos",
        name: "Corn Chips",
        servingSize: "28 g",
        servingsPerContainer: 14,
        calories: 160,
        caloriesFromFat: 90,
        fat: 10,
        fatSaturated: 1.5,
        fatTrans: 0,
        fatPolyunsat: 6,
        fatMonounsat: 2.5,
        cholesterol: 0,
        sodium: 160,
        potassium: undefined,
        carbs: 16,
        carbsDietaryFiber: 1,
        carbsSugars: 0,
        protein: 2
    },
    {
        type: FoodType.VEGETABLE,
        brand: "Fritos",
        name: "Scoops Corn Chips",
        servingSize: "1 oz",
        servingsPerContainer: 18,
        calories: 160,
        caloriesFromFat: 90,
        fat: 10,
        fatSaturated: 1.5,
        fatTrans: 0,
        fatPolyunsat: 5,
        fatMonounsat: 3,
        cholesterol: 0,
        sodium: 110,
        potassium: undefined,
        carbs: 16,
        carbsDietaryFiber: 1,
        carbsSugars: 0,
        protein: 2
    },
    {
        type: FoodType.VEGETABLE,
        brand: "King Soopers",
        name: "Mustard Potato Salad",
        servingSize: "1/2 cup",
        servingsPerContainer: 3,
        calories: 170,
        caloriesFromFat: 60,
        fat: 7,
        fatSaturated: 1,
        fatTrans: 0,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 5,
        sodium: 810,
        potassium: undefined,
        carbs: 24,
        carbsDietaryFiber: 3,
        carbsSugars: 4,
        protein: 3,
    },
    {
        type: FoodType.VEGETABLE,
        brand: "Kroger",
        name: "Black beans",
        servingSize: "1/2 cup",
        servingsPerContainer: 3.5,
        calories: 110,
        caloriesFromFat: 10,
        fat: 1,
        fatSaturated: 0,
        fatTrans: 0,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 0,
        sodium: 300,
        potassium: undefined,
        carbs: 18,
        carbsDietaryFiber: 6,
        carbsSugars: 1,
        protein: 6
    },
    {
        type: FoodType.VEGETABLE,
        brand: "Kroger",
        name: "Dark Red Kidney beans",
        servingSize: "1/2 cup",
        servingsPerContainer: 3.5,
        calories: 100,
        caloriesFromFat: 5,
        fat: 0.5,
        fatSaturated: 0,
        fatTrans: 0,
        fatPolyunsat: 0,
        fatMonounsat: 0,
        cholesterol: 0,
        sodium: 260,
        potassium: 430,
        carbs: 21,
        carbsDietaryFiber: 7,
        carbsSugars: 2,
        protein: 7
    },
    {
        type: FoodType.VEGETABLE,
        brand: "Kroger",
        name: "Dark Red Kidney beans no salt added",
        servingSize: "1/2 cup",
        servingsPerContainer: 3.5,
        calories: 120,
        caloriesFromFat: 0,
        fat: 0,
        fatSaturated: 0,
        fatTrans: 0,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 0,
        sodium: 10,
        potassium: undefined,
        carbs: 20,
        carbsDietaryFiber: 7,
        carbsSugars: 2,
        protein: 7
    },
    {
        type: FoodType.VEGETABLE,
        brand: "Kroger",
        name: "French style Green Beans",
        servingSize: "1/2 cup",
        servingsPerContainer: 3.5,
        calories: 20,
        caloriesFromFat: 0,
        fat: 0,
        fatSaturated: 0,
        fatTrans: 0,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 0,
        sodium: 400,
        potassium: undefined,
        carbs: 4,
        carbsDietaryFiber: 2,
        carbsSugars: 2,
        protein: 1,
    },
    {
        type: FoodType.VEGETABLE,
        brand: "Kroger",
        name: "French style Green Beans no salt added",
        servingSize: "1/2 cup",
        servingsPerContainer: 3.5,
        calories: 20,
        caloriesFromFat: 0,
        fat: 0,
        fatSaturated: 0,
        fatTrans: 0,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 0,
        sodium: 15,
        potassium: undefined,
        carbs: 4,
        carbsDietaryFiber: 2,
        carbsSugars: 2,
        protein: 1
    },
    {
        type: FoodType.VEGETABLE,
        brand: "Kroger",
        name: "Italian style Green Beans",
        servingSize: "1/2 cup",
        servingsPerContainer: 3.5,
        calories: 35,
        caloriesFromFat: 0,
        fat: 0,
        fatSaturated: 0,
        fatTrans: 0,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 0,
        sodium: 400,
        potassium: undefined,
        carbs: 7,
        carbsDietaryFiber: 2,
        carbsSugars: 2,
        protein: 1
    },
    {
        type: FoodType.VEGETABLE,
        brand: "Kroger",
        name: "Lima Beans",
        servingSize: "1/2 cup",
        servingsPerContainer: 3.5,
        calories: 90,
        caloriesFromFat: 5,
        fat: 0.5,
        fatSaturated: 0,
        fatTrans: 0,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 0,
        sodium: 350,
        potassium: undefined,
        carbs: 17,
        carbsDietaryFiber: 4,
        carbsSugars: 1,
        protein: 4,
    },
    {
        type: FoodType.VEGETABLE,
        brand: "Kroger",
        name: "Pinto beans",
        servingSize: "1/2 cup",
        servingsPerContainer: 3.5,
        calories: 90,
        caloriesFromFat: 0,
        fat: 0,
        fatSaturated: 0,
        fatTrans: 0,
        fatPolyunsat: 0,
        fatMonounsat: 0,
        cholesterol: 0,
        sodium: 410,
        potassium: 300,
        carbs: 20,
        carbsDietaryFiber: 7,
        carbsSugars: 1,
        protein: 6
    },
    {
        type: FoodType.VEGETABLE,
        brand: "Kroger",
        name: "Red beans",
        servingSize: "1/2 cup",
        servingsPerContainer: 3.5,
        calories: 110,
        caloriesFromFat: 10,
        fat: 1,
        fatSaturated: 0,
        fatTrans: 0,
        fatPolyunsat: 0,
        fatMonounsat: 0,
        cholesterol: 0,
        sodium: 290,
        potassium: undefined,
        carbs: 20,
        carbsDietaryFiber: 7,
        carbsSugars: 1,
        protein: 6
    },
    {
        type: FoodType.VEGETABLE,
        brand: "Kroger",
        name: "Sweet Golden Corn",
        servingSize: "1/2 cup",
        servingsPerContainer: 3.5,
        calories: 80,
        caloriesFromFat: 10,
        fat: 1,
        fatSaturated: 0,
        fatTrans: 0,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 0,
        sodium: 300,
        potassium: undefined,
        carbs: 17,
        carbsDietaryFiber: 2,
        carbsSugars: 4,
        protein: 2
    },
    {
        type: FoodType.VEGETABLE,
        brand: "Kroger",
        name: "Sweet Golden Corn no salt added",
        servingSize: "1/2 cup",
        servingsPerContainer: 3.5,
        calories: 60,
        caloriesFromFat: 15,
        fat: 1.5,
        fatSaturated: 0,
        fatTrans: 0,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 0,
        sodium: 10,
        potassium: undefined,
        carbs: 9,
        carbsDietaryFiber: 2,
        carbsSugars: 7,
        protein: 2
    },
    {
        type: FoodType.VEGETABLE,
        brand: "Kroger",
        name: "Sweet Peas",
        servingSize: "1/2 cup",
        servingsPerContainer: 3.5,
        calories: 70,
        caloriesFromFat: 5,
        fat: 0.5,
        fatSaturated: 0,
        fatTrans: 0,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 0,
        sodium: 320,
        potassium: undefined,
        carbs: 12,
        carbsDietaryFiber: 3,
        carbsSugars: 6,
        protein: 4
    },
    {
        type: FoodType.VEGETABLE,
        brand: "Kroger",
        name: "Sweet Peas & Carrots",
        servingSize: "1/2 cup",
        servingsPerContainer: 3.5,
        calories: 60,
        caloriesFromFat: 0,
        fat: 0,
        fatSaturated: 0,
        fatTrans: 0,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 0,
        sodium: 320,
        potassium: undefined,
        carbs: 10,
        carbsDietaryFiber: 3,
        carbsSugars: 4,
        protein: 3
    },
    {
        type: FoodType.VEGETABLE,
        brand: "Kroger",
        name: "Stir-Fry vegetables",
        servingSize: "1/2 cup",
        servingsPerContainer: 7,
        calories: 15,
        caloriesFromFat: 0,
        fat: 0,
        fatSaturated: 0,
        fatTrans: 0,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 0,
        sodium: 180,
        potassium: undefined,
        carbs: 4,
        carbsDietaryFiber: 2,
        carbsSugars: 1,
        protein: 1
    },
    {
        type: FoodType.VEGETABLE,
        brand: "Private Selection",
        name: "Chipotle Chili Pepper salsa",
        servingSize: "2 tbsp",
        servingsPerContainer: 22,
        calories: 10,
        caloriesFromFat: 0,
        fat: 0,
        fatSaturated: 0,
        fatTrans: 0,
        fatPolyunsat: 0,
        fatMonounsat: 0,
        cholesterol: 0,
        sodium: 220,
        potassium: 0,
        carbs: 2,
        carbsDietaryFiber: 1,
        carbsSugars: 1,
        protein: 0
    },
    {
        type: FoodType.VEGETABLE,
        brand: "Private Selection",
        name: "Restaurant Style salsa",
        servingSize: "2 tbsp",
        servingsPerContainer: 22,
        calories: 10,
        caloriesFromFat: 0,
        fat: 0,
        fatSaturated: 0,
        fatTrans: 0,
        fatPolyunsat: 0,
        fatMonounsat: 0,
        cholesterol: 0,
        sodium: 220,
        potassium: 0,
        carbs: 1,
        carbsDietaryFiber: 0,
        carbsSugars: 1,
        protein: 0
    },
    {
        type: FoodType.VEGETABLE,
        brand: "P$$t",
        name: "Sweet Peas",
        servingSize: "1/2 cup",
        servingsPerContainer: 3.5,
        calories: 70,
        caloriesFromFat: 5,
        fat: 0.5,
        fatSaturated: 0,
        fatTrans: 0,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 0,
        sodium: 300,
        potassium: undefined,
        carbs: 12,
        carbsDietaryFiber: 3,
        carbsSugars: 6,
        protein: 4,
    },
    {
        type: FoodType.VEGETABLE,
        brand: "Ruffles",
        name: "Potato Chips",
        servingSize: "1 oz",
        servingsPerContainer: 8,
        calories: 160,
        caloriesFromFat: 90,
        fat: 10,
        fatSaturated: 1.5,
        fatTrans: 0,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 0,
        sodium: 160,
        potassium: 340,
        carbs: 15,
        carbsDietaryFiber: 1,
        carbsSugars: 1,
        protein: 2
    },
    {
        type: FoodType.VEGETABLE,
        brand: "Tostitos",
        name: "Restaurant Style Tortilla Chips",
        servingSize: "28 g",
        servingsPerContainer: 13,
        calories: 140,
        caloriesFromFat: 60,
        fat: 7,
        fatSaturated: 1,
        fatTrans: 0,
        fatPolyunsat: undefined,
        fatMonounsat: undefined,
        cholesterol: 0,
        sodium: 115,
        potassium: undefined,
        carbs: 19,
        carbsDietaryFiber: 1,
        carbsSugars: 0,
        protein: 2
    }, ];

    this.assignHealthRatings = function(goodProps, badProps)
    {
        InputValidator.validateNotNull("goodProps", goodProps);
        InputValidator.validateNotNull("badProps", badProps);

        foods.forEach(function(food)
        {
            food.healthRating = computeHealthRating(food, goodProps, badProps);
        });
    }

    this.getFoodByBrandName = function(brand, name)
    {
        var answer;

        for (var i = 0; i < foods.length; i++)
        {
            var food = foods[i];

            if (food.brand === brand && food.name === name)
            {
                answer = food;
                break;
            }
        }

        if (!answer)
        {
            LOGGER.warn("Didn't find food for brand, name = " + brand + ", " + name);
        }

        return answer;
    }

    this.getFoods = function()
    {
        return foods;
    }

    this.getRange = function(property)
    {
        var low = Number.MAX_VALUE;
        var high = Number.MIN_VALUE;

        var isLowSet = false;
        var isHighSet = false;

        foods.forEach(function(food)
        {
            var value = food[property];

            if (value < low)
            {
                low = value;
                isLowSet = true;
            }

            if (high < value)
            {
                high = value;
                isHighSet = true;
            }
        });

        if (!isLowSet)
        {
            low = 0.0;
        }

        if (!isHighSet)
        {
            high = 1.0;
        }

        var answer =
        {
            low: low,
            high: high
        };

        return answer;
    }

    foods.push(FoodUtilities.combine("JMT", "Bean, Veg & Tuna Bowl with Salsa", [
            this.getFoodByBrandName("Kroger", "Black beans"), this.getFoodByBrandName("Kroger", "Stir-Fry vegetables"),
            this.getFoodByBrandName("StarKist", "Solid White Albacore tuna in water"),
            this.getFoodByBrandName("Private Selection", "Restaurant Style salsa") ]));
    foods.push(FoodUtilities.combine("JMT", "Bean, Veg & Tuna Bowl with Soy Sauce", [
            this.getFoodByBrandName("Kroger", "Black beans"), this.getFoodByBrandName("Kroger", "Stir-Fry vegetables"),
            this.getFoodByBrandName("StarKist", "Solid White Albacore tuna in water"),
            this.getFoodByBrandName("Kroger", "Lite Soy sauce") ]));
    foods.push(FoodUtilities.combine("JMT", "Bean, Veg & Tuna Bowl with BBQ sauce", [
            this.getFoodByBrandName("Kroger", "Black beans"), this.getFoodByBrandName("Kroger", "Stir-Fry vegetables"),
            this.getFoodByBrandName("StarKist", "Solid White Albacore tuna in water"),
            this.getFoodByBrandName("Kroger", "Kansas City style BBQ sauce") ]));

    foods.push(FoodUtilities.combine("JMT", "Bean, Veg & Tuna Bowl with Salsa and Cheese", [
            this.getFoodByBrandName("Kroger", "Black beans"), this.getFoodByBrandName("Kroger", "Stir-Fry vegetables"),
            this.getFoodByBrandName("StarKist", "Solid White Albacore tuna in water"),
            this.getFoodByBrandName("Private Selection", "Restaurant Style salsa"),
            this.getFoodByBrandName("Kroger", "Pepper Jack cheese singles") ]));
    foods.push(FoodUtilities.combine("JMT", "Bean, Veg & Tuna Bowl with Soy Sauce", [
            this.getFoodByBrandName("Kroger", "Black beans"), this.getFoodByBrandName("Kroger", "Stir-Fry vegetables"),
            this.getFoodByBrandName("StarKist", "Solid White Albacore tuna in water"),
            this.getFoodByBrandName("Kroger", "Lite Soy sauce"),
            this.getFoodByBrandName("Kroger", "Pepper Jack cheese singles") ]));
    foods.push(FoodUtilities.combine("JMT", "Bean, Veg & Tuna Bowl with BBQ sauce and Cheese", [
            this.getFoodByBrandName("Kroger", "Black beans"), this.getFoodByBrandName("Kroger", "Stir-Fry vegetables"),
            this.getFoodByBrandName("StarKist", "Solid White Albacore tuna in water"),
            this.getFoodByBrandName("Kroger", "Kansas City style BBQ sauce"),
            this.getFoodByBrandName("Kroger", "Pepper Jack cheese singles") ]));

    // Assign derived data.
    var ranges = {};
    var numberValues = FoodProperty.numberValues();

    numberValues.forEach(function(property)
    {
        ranges[property] = that.getRange(property);
        LOGGER.info(property + ": " + ranges[property].low + " " + ranges[property].high);
    });

    foods.forEach(function(food)
    {
        if (food.useContainer)
        {
            FoodUtilities.multiply(food, food.servingsPerContainer);
        }
    });

    function computeHealthRating(food, goodProps, badProps)
    {
        // Good.
        var good = 0;
        goodProps.forEach(function(property)
        {
            good += FoodUtilities.normalize(food[property], ranges[property]);
        });

        // Bad.
        var bad = 0;
        badProps.forEach(function(property)
        {
            bad += FoodUtilities.normalize(food[property], ranges[property]);
        });

        return Math.vizziniRound4(good - bad);
    }

    var end = new Date().getTime();
    TimePrinter.printElapsedTime("FoodDatabase()", start, end);
}
