/*
 * Provides a ship state for Starfighter Squadrons.
 */
function ShipState(pilotSkillValue, primaryWeaponValue, agilityValue,
        hullValue, shieldValue)
{
    this.getAgilityValue = function()
    {
        return agilityValue;
    }

    this.getHullValue = function()
    {
        return hullValue;
    }

    this.getPilotSkillValue = function()
    {
        return pilotSkillValue;
    }

    this.getPrimaryWeaponValue = function()
    {
        return primaryWeaponValue;
    }

    this.getShieldValue = function()
    {
        return shieldValue;
    }
};

ShipState.ZERO = new ShipState(0, 0, 0, 0, 0);

/*
 * Provides an enumeration of pilots for Starfighter Squadrons.
 */
var Pilot =
{
    ACADEMY_PILOT: "academyPilot",
    AIREN_CRACKEN: "airenCracken",
    ALPHA_SQUADRON_PILOT: "alphaSquadronPilot",
    ARVEL_CRYNYD: "arvelCrynyd",
    AVENGER_SQUADRON_PILOT: "avengerSquadronPilot",
    BACKSTABBER: "backstabber",
    BANDIT_SQUADRON_PILOT: "banditSquadronPilot",
    BIGGS_DARKLIGHTER: "biggsDarklighter",
    BLACK_SQUADRON_PILOT: "blackSquadronPilot",
    BLACKMOON_SQUADRON_PILOT: "blackmoonSquadronPilot",
    BLUE_SQUADRON_PILOT: "blueSquadronPilot",
    BOBA_FETT: "bobaFett",
    BOUNTY_HUNTER: "bountyHunter",
    CAPTAIN_JONUS: "captainJonus",
    CAPTAIN_KAGI: "captainKagi",
    CAPTAIN_OICUNN: "captainOicunn",
    CAPTAIN_YORR: "captainYorr",
    CARNOR_JAX: "carnorJax",
    CHEWBACCA: "chewbacca",
    COLONEL_JENDON: "colonelJendon",
    COLONEL_VESSERY: "colonelVessery",
    COMMANDER_KENKIRK: "commanderKenkirk",
    CORRAN_HORN: "corranHorn",
    DAGGER_SQUADRON_PILOT: "daggerSquadronPilot",
    DARK_CURSE: "darkCurse",
    DARTH_VADER: "darthVader",
    DASH_RENDAR: "dashRendar",
    DELTA_SQUADRON_PILOT: "deltaSquadronPilot",
    DUTCH_VANDER: "dutchVander",
    EADEN_VRILL: "eadenVrill",
    ECHO: "echo",
    ETAHN_ABAHT: "etahnAbaht",
    FELS_WRATH: "felsWrath",
    GAMMA_SQUADRON_PILOT: "gammaSquadronPilot",
    GARVEN_DREIS: "garvenDreis",
    GOLD_SQUADRON_PILOT: "goldSquadronPilot",
    GRAY_SQUADRON_PILOT: "graySquadronPilot",
    GREEN_SQUADRON_PILOT: "greenSquadronPilot",
    HAN_SOLO: "hanSolo",
    HOBBIE_KLIVIAN: "hobbieKlivian",
    HORTON_SALM: "hortonSalm",
    HOWLRUNNER: "howlrunner",
    IBTISAM: "ibtisam",
    JAN_ORS: "janOrs",
    JEK_PORKINS: "jekPorkins",
    KATH_SCARLET: "kathScarlet",
    KIR_KANOS: "kirKanos",
    KNAVE_SQUADRON_PILOT: "knaveSquadronPilot",
    KRASSIS_TRELIX: "krassisTrelix",
    KYLE_KATARN: "kyleKatarn",
    LANDO_CALRISSIAN: "landoCalrissian",
    LEEBO: "leebo",
    LIEUTENANT_BLOUNT: "lieutenantBlount",
    LIEUTENANT_LORRIR: "lieutenantLorrir",
    LUKE_SKYWALKER: "lukeSkywalker",
    MAAREK_STELE: "maarekStele",
    MAJOR_RHYMER: "majorRhymer",
    MAULER_MITHEL: "maulerMithel",
    NIGHT_BEAST: "nightBeast",
    OBSIDIAN_SQUADRON_PILOT: "obsidianSquadronPilot",
    OMICRON_GROUP_PILOT: "omicronGroupPilot",
    ONYX_SQUADRON_PILOT: "onyxSquadronPilot",
    OUTER_RIM_SMUGGLER: "outerRimSmuggler",
    PATROL_LEADER: "patrolLeader",
    PROTOTYPE_PILOT: "prototypePilot",
    REAR_ADMIRAL_CHIRANEAU: "rearAdmiralChiraneau",
    REBEL_OPERATIVE: "rebelOperative",
    RED_SQUADRON_PILOT: "redSquadronPilot",
    REXLER_BRATH: "rexlerBrath",
    ROARK_GARNET: "roarkGarnet",
    ROOKIE_PILOT: "rookiePilot",
    ROYAL_GUARD_PILOT: "royalGuardPilot",
    SABER_SQUADRON_PILOT: "saberSquadronPilot",
    SABER_SQUADRON_PILOT: "saberSquadronPilot",
    SCIMITAR_SQUADRON_PILOT: "scimitarSquadronPilot",
    SHADOW_SQUADRON_PILOT: "shadowSquadronPilot",
    SIGMA_SQUADRON_PILOT: "sigmaSquadronPilot",
    SOONTIR_FEL: "soontirFel",
    STORM_SQUADRON_PILOT: "stormSquadronPilot",
    TALA_SQUADRON_PILOT: "talaSquadronPilot",
    TARN_MISON: "tarnMison",
    TEMPEST_SQUADRON_PILOT: "tempestSquadronPilot",
    TEN_NUMB: "tenNumb",
    TETRAN_COWALL: "tetranCowall",
    TURR_PHENNIR: "turrPhennir",
    TYCHO_CELCHU: "tychoCelchu",
    WEDGE_ANTILLES: "wedgeAntilles",
    WES_JANSON: "wesJanson",
    WHISPER: "whisper",
    WILD_SPACE_FRINGER: "wildSpaceFringer",
    WINGED_GUNDARK: "wingedGundark",
    properties:
    {
        "academyPilot":
        {
            name: "Academy Pilot",
            description: "Developed by Sienar Fleet Systems, the Empire used the fast and agile TIE/In as its primary starfighter throughout most of the Galactic Civil War.",
            isUnique: false,
            primaryWeapon: new Weapon("Primary Weapon", true, 2, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.TIE_FIGHTER,
            shipState: new ShipState(1, 2, 3, 3, 0),
            squadPointCost: 12,
            upgradeTypes: [],
            value: "academyPilot",
        },
        "airenCracken":
        {
            name: "Airen Cracken",
            description: "A Z-95 Headhunter pilot.",
            isUnique: true,
            primaryWeapon: new Weapon("Primary Weapon", true, 2, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.Z_95_HEADHUNTER,
            shipState: new ShipState(8, 2, 2, 2, 2),
            squadPointCost: 19,
            upgradeTypes: [ UpgradeType.ELITE, UpgradeType.MISSILE ],
            value: "airenCracken",
        },
        "alphaSquadronPilot":
        {
            name: "Alpha Squadron Pilot",
            description: "A TIE Interceptor pilot.",
            isUnique: false,
            primaryWeapon: new Weapon("Primary Weapon", true, 3, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.TIE_INTERCEPTOR,
            shipState: new ShipState(1, 3, 3, 3, 0),
            squadPointCost: 18,
            upgradeTypes: [],
            value: "alphaSquadronPilot",
        },
        "arvelCrynyd":
        {
            name: "Arvel Crynyd",
            description: "An A-Wing pilot.",
            isUnique: true,
            primaryWeapon: new Weapon("Primary Weapon", true, 2, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.A_WING,
            shipState: new ShipState(6, 2, 3, 2, 2),
            squadPointCost: 23,
            upgradeTypes: [ UpgradeType.MISSILE ],
            value: "arvelCrynyd",
        },
        "avengerSquadronPilot":
        {
            name: "Avenger Squadron Pilot",
            description: "A TIE Interceptor pilot.",
            isUnique: false,
            primaryWeapon: new Weapon("Primary Weapon", true, 3, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.TIE_INTERCEPTOR,
            shipState: new ShipState(3, 3, 3, 3, 0),
            squadPointCost: 20,
            upgradeTypes: [],
            value: "avengerSquadronPilot",
        },
        "backstabber":
        {
            name: "\"Backstabber\"",
            description: "A TIE Fighter pilot.",
            isUnique: true,
            primaryWeapon: new Weapon("Primary Weapon", true, 2, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.TIE_FIGHTER,
            shipState: new ShipState(6, 2, 3, 3, 0),
            squadPointCost: 16,
            upgradeTypes: [],
            value: "backstabber",
        },
        "banditSquadronPilot":
        {
            name: "Bandit Squadron Pilot",
            description: "A Z-95 Headhunter pilot.",
            isUnique: false,
            primaryWeapon: new Weapon("Primary Weapon", true, 2, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.Z_95_HEADHUNTER,
            shipState: new ShipState(2, 2, 2, 2, 2),
            squadPointCost: 12,
            upgradeTypes: [ UpgradeType.MISSILE ],
            value: "banditSquadronPilot",
        },
        "biggsDarklighter":
        {
            name: "Biggs Darklighter",
            description: "An X-Wing pilot.",
            isUnique: true,
            primaryWeapon: new Weapon("Primary Weapon", true, 3, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.X_WING,
            shipState: new ShipState(5, 3, 2, 3, 2),
            squadPointCost: 25,
            upgradeTypes: [ UpgradeType.TORPEDO, UpgradeType.ASTROMECH ],
            value: "biggsDarklighter",
        },
        "blackSquadronPilot":
        {
            name: "Black Squadron Pilot",
            description: "A TIE Fighter pilot.",
            isUnique: false,
            primaryWeapon: new Weapon("Primary Weapon", true, 2, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.TIE_FIGHTER,
            shipState: new ShipState(4, 2, 3, 3, 0),
            squadPointCost: 14,
            upgradeTypes: [ UpgradeType.ELITE ],
            value: "blackSquadronPilot",
        },
        "blackmoonSquadronPilot":
        {
            name: "Blackmoon Squadron Pilot",
            description: "An E-Wing pilot.",
            isUnique: false,
            primaryWeapon: new Weapon("Primary Weapon", true, 3, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.E_WING,
            shipState: new ShipState(3, 3, 3, 2, 3),
            squadPointCost: 29,
            upgradeTypes: [ UpgradeType.SENSOR, UpgradeType.TORPEDO,
                    UpgradeType.ASTROMECH ],
            value: "blackmoonSquadronPilot",
        },
        "blueSquadronPilot":
        {
            name: "Blue Squadron Pilot",
            description: "A B-Wing pilot.",
            isUnique: false,
            primaryWeapon: new Weapon("Primary Weapon", true, 3, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.B_WING,
            shipState: new ShipState(2, 3, 1, 3, 5),
            squadPointCost: 22,
            upgradeTypes: [ UpgradeType.SENSOR, UpgradeType.CANNON,
                    UpgradeType.TORPEDO, UpgradeType.TORPEDO ],
            value: "blueSquadronPilot",
        },
        "bobaFett":
        {
            name: "Boba Fett",
            description: "When you reveal a bank maneuver, you may rotate your dial to the other bank maneuver of the same speed.",
            isUnique: true,
            primaryWeapon: new Weapon("Primary Weapon", true, 3, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.FIRESPRAY_31,
            shipState: new ShipState(8, 3, 2, 6, 4),
            squadPointCost: 39,
            upgradeTypes: [ UpgradeType.ELITE, UpgradeType.CANNON,
                    UpgradeType.BOMB, UpgradeType.CREW, UpgradeType.MISSILE ],
            value: "bobaFett",
        },
        "bountyHunter":
        {
            name: "Bounty Hunter",
            description: "Originally intended as a prisoner transport, the Firespray patrol craft features a versatile weapons array and heavy armor plating.",
            isUnique: false,
            primaryWeapon: new Weapon("Primary Weapon", true, 3, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.FIRESPRAY_31,
            shipState: new ShipState(3, 3, 2, 6, 4),
            squadPointCost: 33,
            upgradeTypes: [ UpgradeType.CANNON, UpgradeType.BOMB,
                    UpgradeType.CREW, UpgradeType.MISSILE ],
            value: "bountyHunter",
        },
        "captainJonus":
        {
            name: "Captain Jonus",
            description: "A TIE Bomber pilot.",
            isUnique: true,
            primaryWeapon: new Weapon("Primary Weapon", true, 2, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.TIE_BOMBER,
            shipState: new ShipState(6, 2, 2, 6, 0),
            squadPointCost: 22,
            upgradeTypes: [ UpgradeType.ELITE, UpgradeType.TORPEDO,
                    UpgradeType.TORPEDO, UpgradeType.MISSILE,
                    UpgradeType.MISSILE, UpgradeType.BOMB ],
            value: "captainJonus",
        },
        "captainKagi":
        {
            name: "Captain Kagi",
            description: "A Lambda-class shuttle pilot.",
            isUnique: true,
            primaryWeapon: new Weapon("Primary Weapon", true, 3, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.LAMBDA_CLASS_SHUTTLE,
            shipState: new ShipState(8, 3, 1, 5, 5),
            squadPointCost: 27,
            upgradeTypes: [ UpgradeType.SENSOR, UpgradeType.CANNON,
                    UpgradeType.CREW, UpgradeType.CREW ],
            value: "captainKagi",
        },
        "captainOicunn":
        {
            name: "Captain Oicunn",
            description: "A VT-49 Decimator pilot.",
            isUnique: true,
            primaryWeapon: new TurretWeapon("Primary Weapon", true, 3, [
                    Range.ONE, Range.TWO, Range.THREE ]),
            ship: Ship.VT_49_DECIMATOR,
            shipState: new ShipState(4, 3, 0, 12, 4),
            squadPointCost: 42,
            upgradeTypes: [ UpgradeType.ELITE, UpgradeType.TORPEDO,
                    UpgradeType.CREW, UpgradeType.CREW, UpgradeType.CREW,
                    UpgradeType.BOMB ],
            value: "captainOicunn",
        },
        "captainYorr":
        {
            name: "Captain Yorr",
            description: "A Lambda-class shuttle pilot.",
            isUnique: true,
            primaryWeapon: new Weapon("Primary Weapon", true, 3, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.LAMBDA_CLASS_SHUTTLE,
            shipState: new ShipState(4, 3, 1, 5, 5),
            squadPointCost: 24,
            upgradeTypes: [ UpgradeType.SENSOR, UpgradeType.CANNON,
                    UpgradeType.CREW, UpgradeType.CREW ],
            value: "captainYorr",
        },
        "carnorJax":
        {
            name: "Carnor Jax",
            description: "A TIE Interceptor pilot.",
            isUnique: true,
            primaryWeapon: new Weapon("Primary Weapon", true, 3, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.ROYAL_GUARD_TIE,
            shipState: new ShipState(8, 3, 3, 3, 0),
            squadPointCost: 26,
            upgradeTypes: [ UpgradeType.ELITE ],
            value: "carnorJax",
        },
        "chewbacca":
        {
            name: "Chewbacca",
            description: "A YT-1300 pilot.",
            isUnique: true,
            primaryWeapon: new TurretWeapon("Primary Weapon", true, 3, [
                    Range.ONE, Range.TWO, Range.THREE ]),
            ship: Ship.YT_1300,
            shipState: new ShipState(5, 3, 1, 8, 5),
            squadPointCost: 42,
            upgradeTypes: [ UpgradeType.ELITE, UpgradeType.MISSILE,
                    UpgradeType.CREW, UpgradeType.CREW ],
            value: "chewbacca",
        },
        "colonelJendon":
        {
            name: "Colonel Jendon",
            description: "A Lambda-class shuttle pilot.",
            isUnique: true,
            primaryWeapon: new Weapon("Primary Weapon", true, 3, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.LAMBDA_CLASS_SHUTTLE,
            shipState: new ShipState(6, 3, 1, 5, 5),
            squadPointCost: 26,
            upgradeTypes: [ UpgradeType.SENSOR, UpgradeType.CANNON,
                    UpgradeType.CREW, UpgradeType.CREW ],
            value: "colonelJendon",
        },
        "colonelVessery":
        {
            name: "Colonel Vessery",
            description: "A TIE Defender pilot.",
            isUnique: false,
            primaryWeapon: new Weapon("Primary Weapon", true, 3, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.TIE_DEFENDER,
            shipState: new ShipState(6, 3, 3, 3, 3),
            squadPointCost: 35,
            upgradeTypes: [ UpgradeType.ELITE, UpgradeType.CANNON,
                    UpgradeType.MISSILE ],
            value: "colonelVessery",
        },
        "commanderKenkirk":
        {
            name: "Commander Kenkirk",
            description: "A VT-49 Decimator pilot.",
            isUnique: true,
            primaryWeapon: new TurretWeapon("Primary Weapon", true, 3, [
                    Range.ONE, Range.TWO, Range.THREE ]),
            ship: Ship.VT_49_DECIMATOR,
            shipState: new ShipState(6, 3, 0, 12, 4),
            squadPointCost: 44,
            upgradeTypes: [ UpgradeType.ELITE, UpgradeType.TORPEDO,
                    UpgradeType.CREW, UpgradeType.CREW, UpgradeType.CREW,
                    UpgradeType.BOMB ],
            value: "commanderKenkirk",
        },
        "corranHorn":
        {
            name: "Corran Horn",
            description: "An E-Wing pilot.",
            isUnique: true,
            primaryWeapon: new Weapon("Primary Weapon", true, 3, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.E_WING,
            shipState: new ShipState(8, 3, 3, 2, 3),
            squadPointCost: 35,
            upgradeTypes: [ UpgradeType.ELITE, UpgradeType.SENSOR,
                    UpgradeType.TORPEDO, UpgradeType.ASTROMECH ],
            value: "corranHorn",
        },
        "daggerSquadronPilot":
        {
            name: "Dagger Squadron Pilot",
            description: "A B-Wing pilot.",
            isUnique: false,
            primaryWeapon: new Weapon("Primary Weapon", true, 3, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.B_WING,
            shipState: new ShipState(4, 3, 1, 3, 5),
            squadPointCost: 24,
            upgradeTypes: [ UpgradeType.SENSOR, UpgradeType.CANNON,
                    UpgradeType.TORPEDO, UpgradeType.TORPEDO ],
            value: "daggerSquadronPilot",
        },
        "darkCurse":
        {
            name: "\"Dark Curse\"",
            description: "A TIE Fighter pilot.",
            isUnique: true,
            primaryWeapon: new Weapon("Primary Weapon", true, 2, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.TIE_FIGHTER,
            shipState: new ShipState(6, 2, 3, 3, 0),
            squadPointCost: 16,
            upgradeTypes: [],
            value: "darkCurse",
        },
        "darthVader":
        {
            name: "Darth Vader",
            description: "A TIE Advanced pilot.",
            isUnique: true,
            primaryWeapon: new Weapon("Primary Weapon", true, 2, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.TIE_ADVANCED,
            shipState: new ShipState(9, 2, 3, 3, 2),
            squadPointCost: 29,
            upgradeTypes: [ UpgradeType.ELITE, UpgradeType.MISSILE ],
            value: "darthVader",
        },
        "dashRendar":
        {
            name: "Dash Rendar",
            description: "A YT-2400 pilot.",
            isUnique: true,
            primaryWeapon: new TurretWeapon("Primary Weapon", true, 2, [
                    Range.ONE, Range.TWO, Range.THREE ]),
            ship: Ship.YT_2400,
            shipState: new ShipState(7, 2, 2, 5, 5),
            squadPointCost: 30,
            upgradeTypes: [ UpgradeType.ELITE, UpgradeType.CANNON,
                    UpgradeType.MISSILE, UpgradeType.CREW ],
            value: "dashRendar",
        },
        "deltaSquadronPilot":
        {
            name: "Delta Squadron Pilot",
            description: "A TIE Defender pilot.",
            isUnique: false,
            primaryWeapon: new Weapon("Primary Weapon", true, 3, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.TIE_DEFENDER,
            shipState: new ShipState(1, 3, 3, 3, 3),
            squadPointCost: 30,
            upgradeTypes: [ UpgradeType.CANNON, UpgradeType.MISSILE ],
            value: "deltaSquadronPilot",
        },
        "dutchVander":
        {
            name: "\"Dutch\" Vander",
            description: "A Y-Wing pilot.",
            isUnique: true,
            primaryWeapon: new Weapon("Primary Weapon", true, 2, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.Y_WING,
            shipState: new ShipState(6, 2, 1, 5, 3),
            squadPointCost: 23,
            upgradeTypes: [ UpgradeType.TURRET, UpgradeType.TORPEDO,
                    UpgradeType.TORPEDO, UpgradeType.ASTROMECH ],
            value: "dutchVander",
        },
        "eadenVrill":
        {
            name: "Eaden Vrill",
            description: "A YT-2400 pilot.",
            isUnique: true,
            primaryWeapon: new TurretWeapon("Primary Weapon", true, 2, [
                    Range.ONE, Range.TWO, Range.THREE ]),
            ship: Ship.YT_2400,
            shipState: new ShipState(3, 2, 2, 5, 5),
            squadPointCost: 30,
            upgradeTypes: [ UpgradeType.CANNON, UpgradeType.MISSILE,
                    UpgradeType.CREW ],
            value: "eadenVrill",
        },
        "echo":
        {
            name: "\"Echo\"",
            description: "A TIE Phantom pilot.",
            isUnique: true,
            primaryWeapon: new Weapon("Primary Weapon", true, 4, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.TIE_PHANTOM,
            shipState: new ShipState(6, 4, 2, 2, 2),
            squadPointCost: 30,
            upgradeTypes: [ UpgradeType.ELITE, UpgradeType.SENSOR,
                    UpgradeType.CREW ],
            value: "echo",
        },
        "etahnAbaht":
        {
            name: "Etahn A'baht",
            description: "An E-Wing pilot.",
            isUnique: true,
            primaryWeapon: new Weapon("Primary Weapon", true, 3, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.E_WING,
            shipState: new ShipState(5, 3, 3, 2, 3),
            squadPointCost: 32,
            upgradeTypes: [ UpgradeType.ELITE, UpgradeType.SENSOR,
                    UpgradeType.TORPEDO, UpgradeType.ASTROMECH ],
            value: "etahnAbaht",
        },
        "felsWrath":
        {
            name: "\"Fel's Wrath\"",
            description: "A TIE Interceptor pilot.",
            isUnique: true,
            primaryWeapon: new Weapon("Primary Weapon", true, 3, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.TIE_INTERCEPTOR,
            shipState: new ShipState(5, 3, 3, 3, 0),
            squadPointCost: 23,
            upgradeTypes: [],
            value: "felsWrath",
        },
        "gammaSquadronPilot":
        {
            name: "Gamma Squadron Pilot",
            description: "A TIE Bomber pilot.",
            isUnique: false,
            primaryWeapon: new Weapon("Primary Weapon", true, 2, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.TIE_BOMBER,
            shipState: new ShipState(4, 2, 2, 6, 0),
            squadPointCost: 18,
            upgradeTypes: [ UpgradeType.TORPEDO, UpgradeType.TORPEDO,
                    UpgradeType.MISSILE, UpgradeType.MISSILE, UpgradeType.BOMB ],
            value: "gammaSquadronPilot",
        },
        "garvenDreis":
        {
            name: "Garven Dreis",
            description: "An X-Wing pilot.",
            isUnique: true,
            primaryWeapon: new Weapon("Primary Weapon", true, 3, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.X_WING,
            shipState: new ShipState(6, 3, 2, 3, 2),
            squadPointCost: 26,
            upgradeTypes: [ UpgradeType.TORPEDO, UpgradeType.ASTROMECH ],
            value: "garvenDreis",
        },
        "goldSquadronPilot":
        {
            name: "Gold Squadron Pilot",
            description: "A Y-Wing pilot.",
            isUnique: false,
            primaryWeapon: new Weapon("Primary Weapon", true, 2, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.Y_WING,
            shipState: new ShipState(2, 2, 1, 5, 3),
            squadPointCost: 18,
            upgradeTypes: [ UpgradeType.TURRET, UpgradeType.TORPEDO,
                    UpgradeType.TORPEDO, UpgradeType.ASTROMECH ],
            value: "goldSquadronPilot",
        },
        "graySquadronPilot":
        {
            name: "Gray Squadron Pilot",
            description: "A Y-Wing pilot.",
            isUnique: false,
            primaryWeapon: new Weapon("Primary Weapon", true, 2, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.Y_WING,
            shipState: new ShipState(4, 2, 1, 5, 3),
            squadPointCost: 20,
            upgradeTypes: [ UpgradeType.TURRET, UpgradeType.TORPEDO,
                    UpgradeType.TORPEDO, UpgradeType.ASTROMECH ],
            value: "graySquadronPilot",
        },
        "greenSquadronPilot":
        {
            name: "Green Squadron Pilot",
            description: "An A-Wing pilot.",
            isUnique: false,
            primaryWeapon: new Weapon("Primary Weapon", true, 2, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.A_WING,
            shipState: new ShipState(3, 2, 3, 2, 2),
            squadPointCost: 19,
            upgradeTypes: [ UpgradeType.ELITE, UpgradeType.MISSILE ],
            value: "greenSquadronPilot",
        },
        "hanSolo":
        {
            name: "Han Solo",
            description: "A YT-1300 pilot.",
            isUnique: true,
            primaryWeapon: new TurretWeapon("Primary Weapon", true, 3, [
                    Range.ONE, Range.TWO, Range.THREE ]),
            ship: Ship.YT_1300,
            shipState: new ShipState(9, 3, 1, 8, 5),
            squadPointCost: 46,
            upgradeTypes: [ UpgradeType.ELITE, UpgradeType.MISSILE,
                    UpgradeType.CREW, UpgradeType.CREW ],
            value: "hanSolo",
        },
        "hobbieKlivian":
        {
            name: "\"Hobbie\" Klivian",
            description: "An X-Wing pilot.",
            isUnique: true,
            primaryWeapon: new Weapon("Primary Weapon", true, 3, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.X_WING,
            shipState: new ShipState(5, 3, 2, 3, 2),
            squadPointCost: 25,
            upgradeTypes: [ UpgradeType.TORPEDO, UpgradeType.ASTROMECH ],
            value: "hobbieKlivian",
        },
        "hortonSalm":
        {
            name: "Horton Salm",
            description: "A Y-Wing pilot.",
            isUnique: true,
            primaryWeapon: new Weapon("Primary Weapon", true, 2, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.Y_WING,
            shipState: new ShipState(8, 2, 1, 5, 3),
            squadPointCost: 25,
            upgradeTypes: [ UpgradeType.TURRET, UpgradeType.TORPEDO,
                    UpgradeType.TORPEDO, UpgradeType.ASTROMECH ],
            value: "hortonSalm",
        },
        "howlrunner":
        {
            name: "\"Howlrunner\"",
            description: "A TIE Fighter pilot.",
            isUnique: true,
            primaryWeapon: new Weapon("Primary Weapon", true, 2, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.TIE_FIGHTER,
            shipState: new ShipState(8, 2, 3, 3, 0),
            squadPointCost: 18,
            upgradeTypes: [ UpgradeType.ELITE ],
            value: "howlrunner",
        },
        "ibtisam":
        {
            name: "Ibtisam",
            description: "A B-Wing pilot.",
            isUnique: true,
            primaryWeapon: new Weapon("Primary Weapon", true, 3, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.B_WING,
            shipState: new ShipState(6, 3, 1, 3, 5),
            squadPointCost: 28,
            upgradeTypes: [ UpgradeType.ELITE, UpgradeType.SENSOR,
                    UpgradeType.CANNON, UpgradeType.TORPEDO,
                    UpgradeType.TORPEDO ],
            value: "ibtisam",
        },
        "janOrs":
        {
            name: "Jan Ors",
            description: "An HWK-290 pilot.",
            isUnique: true,
            primaryWeapon: new Weapon("Primary Weapon", true, 1, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.HWK_290,
            shipState: new ShipState(8, 1, 2, 4, 1),
            squadPointCost: 25,
            upgradeTypes: [ UpgradeType.ELITE, UpgradeType.TURRET,
                    UpgradeType.CREW ],
            value: "janOrs",
        },
        "jekPorkins":
        {
            name: "Jek Porkins",
            description: "An X-Wing pilot.",
            isUnique: true,
            primaryWeapon: new Weapon("Primary Weapon", true, 3, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.X_WING,
            shipState: new ShipState(7, 3, 2, 3, 2),
            squadPointCost: 26,
            upgradeTypes: [ UpgradeType.ELITE, UpgradeType.TORPEDO,
                    UpgradeType.ASTROMECH ],
            value: "jekPorkins",
        },
        "kathScarlet":
        {
            name: "Kath Scarlet",
            description: "When attacking, the defender receives 1 stress token if he cancels at least 1 Critical Hit result.",
            isUnique: true,
            primaryWeapon: new Weapon("Primary Weapon", true, 3, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.FIRESPRAY_31,
            shipState: new ShipState(7, 3, 2, 6, 4),
            squadPointCost: 38,
            upgradeTypes: [ UpgradeType.ELITE, UpgradeType.CANNON,
                    UpgradeType.BOMB, UpgradeType.CREW, UpgradeType.MISSILE ],
            value: "kathScarlet",
        },
        "kirKanos":
        {
            name: "Kir Kanos",
            description: "A TIE Interceptor pilot.",
            isUnique: true,
            primaryWeapon: new Weapon("Primary Weapon", true, 3, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.ROYAL_GUARD_TIE,
            shipState: new ShipState(6, 3, 3, 3, 0),
            squadPointCost: 24,
            upgradeTypes: [],
            value: "kirKanos",
        },
        "knaveSquadronPilot":
        {
            name: "Knave Squadron Pilot",
            description: "An E-Wing pilot.",
            isUnique: false,
            primaryWeapon: new Weapon("Primary Weapon", true, 3, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.E_WING,
            shipState: new ShipState(1, 3, 3, 2, 3),
            squadPointCost: 27,
            upgradeTypes: [ UpgradeType.SENSOR, UpgradeType.TORPEDO,
                    UpgradeType.ASTROMECH ],
            value: "knaveSquadronPilot",
        },
        "krassisTrelix":
        {
            name: "Krassis Trelix",
            description: "When attacking with a secondary weapon, you may reroll 1 attack die.",
            isUnique: true,
            primaryWeapon: new Weapon("Primary Weapon", true, 3, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.FIRESPRAY_31,
            shipState: new ShipState(5, 3, 2, 6, 4),
            squadPointCost: 36,
            upgradeTypes: [ UpgradeType.CANNON, UpgradeType.BOMB,
                    UpgradeType.CREW, UpgradeType.MISSILE ],
            value: "krassisTrelix",
        },
        "kyleKatarn":
        {
            name: "Kyle Katarn",
            description: "An HWK-290 pilot.",
            isUnique: true,
            primaryWeapon: new Weapon("Primary Weapon", true, 1, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.HWK_290,
            shipState: new ShipState(6, 1, 2, 4, 1),
            squadPointCost: 21,
            upgradeTypes: [ UpgradeType.ELITE, UpgradeType.TURRET,
                    UpgradeType.CREW ],
            value: "kyleKatarn",
        },
        "landoCalrissian":
        {
            name: "Lando Calrissian",
            description: "A YT-1300 pilot.",
            isUnique: true,
            primaryWeapon: new TurretWeapon("Primary Weapon", true, 3, [
                    Range.ONE, Range.TWO, Range.THREE ]),
            ship: Ship.YT_1300,
            shipState: new ShipState(7, 3, 1, 8, 5),
            squadPointCost: 44,
            upgradeTypes: [ UpgradeType.ELITE, UpgradeType.MISSILE,
                    UpgradeType.CREW, UpgradeType.CREW ],
            value: "landoCalrissian",
        },
        "leebo":
        {
            name: "Leebo",
            description: "A YT-2400 pilot.",
            isUnique: true,
            primaryWeapon: new TurretWeapon("Primary Weapon", true, 2, [
                    Range.ONE, Range.TWO, Range.THREE ]),
            ship: Ship.YT_2400,
            shipState: new ShipState(5, 2, 2, 5, 5),
            squadPointCost: 30,
            upgradeTypes: [ UpgradeType.ELITE, UpgradeType.CANNON,
                    UpgradeType.MISSILE, UpgradeType.CREW ],
            value: "leebo",
        },
        "lieutenantBlount":
        {
            name: "Lieutenant Blount",
            description: "A Z-95 Headhunter pilot.",
            isUnique: true,
            primaryWeapon: new Weapon("Primary Weapon", true, 2, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.Z_95_HEADHUNTER,
            shipState: new ShipState(6, 2, 2, 2, 2),
            squadPointCost: 17,
            upgradeTypes: [ UpgradeType.ELITE, UpgradeType.MISSILE ],
            value: "lieutenantBlount",
        },
        "lieutenantLorrir":
        {
            name: "Lieutenant Lorrir",
            description: "A TIE Interceptor pilot.",
            isUnique: true,
            primaryWeapon: new Weapon("Primary Weapon", true, 3, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.SABER_SQUADRON_TIE,
            shipState: new ShipState(5, 3, 3, 3, 0),
            squadPointCost: 23,
            upgradeTypes: [],
            value: "lieutenantLorrir",
        },
        "lukeSkywalker":
        {
            name: "Luke Skywalker",
            description: "An X-Wing pilot.",
            isUnique: true,
            primaryWeapon: new Weapon("Primary Weapon", true, 3, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.X_WING,
            shipState: new ShipState(8, 3, 2, 3, 2),
            squadPointCost: 28,
            upgradeTypes: [ UpgradeType.ELITE, UpgradeType.TORPEDO,
                    UpgradeType.ASTROMECH ],
            value: "lukeSkywalker",
        },
        "maarekStele":
        {
            name: "Maarek Stele",
            description: "A TIE Advanced pilot.",
            isUnique: true,
            primaryWeapon: new Weapon("Primary Weapon", true, 2, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.TIE_ADVANCED,
            shipState: new ShipState(7, 2, 3, 3, 2),
            squadPointCost: 27,
            upgradeTypes: [ UpgradeType.ELITE, UpgradeType.MISSILE ],
            value: "maarekStele",
        },
        "majorRhymer":
        {
            name: "Major Rhymer",
            description: "A TIE Bomber pilot.",
            isUnique: true,
            primaryWeapon: new Weapon("Primary Weapon", true, 2, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.TIE_BOMBER,
            shipState: new ShipState(7, 2, 2, 6, 0),
            squadPointCost: 26,
            upgradeTypes: [ UpgradeType.ELITE, UpgradeType.TORPEDO,
                    UpgradeType.TORPEDO, UpgradeType.MISSILE,
                    UpgradeType.MISSILE, UpgradeType.BOMB ],
            value: "majorRhymer",
        },
        "maulerMithel":
        {
            name: "\"Mauler Mithel\"",
            description: "A TIE Fighter pilot.",
            isUnique: true,
            primaryWeapon: new Weapon("Primary Weapon", true, 2, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.TIE_FIGHTER,
            shipState: new ShipState(7, 2, 3, 3, 0),
            squadPointCost: 17,
            upgradeTypes: [ UpgradeType.ELITE ],
            value: "maulerMithel",
        },
        "nightBeast":
        {
            name: "\"Night Beast\"",
            description: "A TIE Fighter pilot.",
            isUnique: true,
            primaryWeapon: new Weapon("Primary Weapon", true, 2, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.TIE_FIGHTER,
            shipState: new ShipState(5, 2, 3, 3, 0),
            squadPointCost: 15,
            upgradeTypes: [],
            value: "nightBeast",
        },
        "obsidianSquadronPilot":
        {
            name: "Obsidian Squadron Pilot",
            description: "A TIE Fighter pilot.",
            isUnique: false,
            primaryWeapon: new Weapon("Primary Weapon", true, 2, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.TIE_FIGHTER,
            shipState: new ShipState(3, 2, 3, 3, 0),
            squadPointCost: 13,
            upgradeTypes: [],
            value: "obsidianSquadronPilot",
        },
        "omicronGroupPilot":
        {
            name: "Omicron Group Pilot",
            description: "A Lambda-class shuttle pilot.",
            isUnique: false,
            primaryWeapon: new Weapon("Primary Weapon", true, 3, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.LAMBDA_CLASS_SHUTTLE,
            shipState: new ShipState(2, 3, 1, 5, 5),
            squadPointCost: 21,
            upgradeTypes: [ UpgradeType.SENSOR, UpgradeType.CANNON,
                    UpgradeType.CREW, UpgradeType.CREW ],
            value: "omicronGroupPilot",
        },
        "onyxSquadronPilot":
        {
            name: "Onyx Squadron Pilot",
            description: "A TIE Defender pilot.",
            isUnique: false,
            primaryWeapon: new Weapon("Primary Weapon", true, 3, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.TIE_DEFENDER,
            shipState: new ShipState(3, 3, 3, 3, 3),
            squadPointCost: 32,
            upgradeTypes: [ UpgradeType.CANNON, UpgradeType.MISSILE ],
            value: "onyxSquadronPilot",
        },
        "outerRimSmuggler":
        {
            name: "Outer Rim Smuggler",
            description: "A YT-1300 pilot.",
            isUnique: false,
            primaryWeapon: new TurretWeapon("Primary Weapon", true, 2, [
                    Range.ONE, Range.TWO, Range.THREE ]),
            ship: Ship.YT_1300,
            shipState: new ShipState(1, 2, 1, 6, 4),
            squadPointCost: 27,
            upgradeTypes: [ UpgradeType.CREW, UpgradeType.CREW ],
            value: "outerRimSmuggler",
        },
        "patrolLeader":
        {
            name: "Patrol Leader",
            description: "A VT-49 Decimator pilot.",
            isUnique: false,
            primaryWeapon: new TurretWeapon("Primary Weapon", true, 3, [
                    Range.ONE, Range.TWO, Range.THREE ]),
            ship: Ship.VT_49_DECIMATOR,
            shipState: new ShipState(3, 3, 0, 12, 4),
            squadPointCost: 40,
            upgradeTypes: [ UpgradeType.TORPEDO, UpgradeType.CREW,
                    UpgradeType.CREW, UpgradeType.CREW, UpgradeType.BOMB ],
            value: "patrolLeader",
        },
        "prototypePilot":
        {
            name: "Prototype Pilot",
            description: "An A-Wing pilot.",
            isUnique: false,
            primaryWeapon: new Weapon("Primary Weapon", true, 2, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.A_WING,
            shipState: new ShipState(1, 2, 3, 2, 2),
            squadPointCost: 17,
            upgradeTypes: [ UpgradeType.MISSILE ],
            value: "prototypePilot",
        },
        "rearAdmiralChiraneau":
        {
            name: "Rear Admiral Chiraneau",
            description: "A VT-49 Decimator pilot.",
            isUnique: true,
            primaryWeapon: new TurretWeapon("Primary Weapon", true, 3, [
                    Range.ONE, Range.TWO, Range.THREE ]),
            ship: Ship.VT_49_DECIMATOR,
            shipState: new ShipState(8, 3, 0, 12, 4),
            squadPointCost: 46,
            upgradeTypes: [ UpgradeType.ELITE, UpgradeType.TORPEDO,
                    UpgradeType.CREW, UpgradeType.CREW, UpgradeType.CREW,
                    UpgradeType.BOMB ],
            value: "rearAdmiralChiraneau",
        },
        "rebelOperative":
        {
            name: "Rebel Operative",
            description: "An HWK-290 pilot.",
            isUnique: false,
            primaryWeapon: new Weapon("Primary Weapon", true, 1, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.HWK_290,
            shipState: new ShipState(2, 1, 2, 4, 1),
            squadPointCost: 16,
            upgradeTypes: [ UpgradeType.TURRET, UpgradeType.CREW ],
            value: "rebelOperative",
        },
        "redSquadronPilot":
        {
            name: "Red Squadron Pilot",
            description: "An X-Wing pilot.",
            isUnique: false,
            primaryWeapon: new Weapon("Primary Weapon", true, 3, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.X_WING,
            shipState: new ShipState(4, 3, 2, 3, 2),
            squadPointCost: 23,
            upgradeTypes: [ UpgradeType.TORPEDO, UpgradeType.ASTROMECH ],
            value: "redSquadronPilot",
        },
        "rexlerBrath":
        {
            name: "Rexler Brath",
            description: "A TIE Defender pilot.",
            isUnique: false,
            primaryWeapon: new Weapon("Primary Weapon", true, 3, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.TIE_DEFENDER,
            shipState: new ShipState(8, 3, 3, 3, 3),
            squadPointCost: 37,
            upgradeTypes: [ UpgradeType.ELITE, UpgradeType.CANNON,
                    UpgradeType.MISSILE ],
            value: "rexlerBrath",
        },
        "roarkGarnet":
        {
            name: "Roark Garnet",
            description: "An HWK-290 pilot.",
            isUnique: true,
            primaryWeapon: new Weapon("Primary Weapon", true, 1, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.HWK_290,
            shipState: new ShipState(4, 1, 2, 4, 1),
            squadPointCost: 19,
            upgradeTypes: [ UpgradeType.TURRET, UpgradeType.CREW ],
            value: "roarkGarnet",
        },
        "rookiePilot":
        {
            name: "Rookie Pilot",
            description: "Designed by Incom Corporation, the T-65 X-wing quickly proved to be one of the most effective military vehicles in the galaxy and a boon to the Rebellion.",
            isUnique: false,
            primaryWeapon: new Weapon("Primary Weapon", true, 3, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.X_WING,
            shipState: new ShipState(2, 3, 2, 3, 2),
            squadPointCost: 21,
            upgradeTypes: [ UpgradeType.TORPEDO, UpgradeType.ASTROMECH ],
            value: "rookiePilot",
        },
        "royalGuardPilot":
        {
            name: "Royal Guard Pilot",
            description: "A TIE Interceptor pilot.",
            isUnique: false,
            primaryWeapon: new Weapon("Primary Weapon", true, 3, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.ROYAL_GUARD_TIE,
            shipState: new ShipState(6, 3, 3, 3, 0),
            squadPointCost: 22,
            upgradeTypes: [ UpgradeType.ELITE ],
            value: "royalGuardPilot",
        },
        "saberSquadronPilot":
        {
            name: "Saber Squadron Pilot",
            description: "A TIE Interceptor pilot.",
            isUnique: false,
            primaryWeapon: new Weapon("Primary Weapon", true, 3, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.TIE_INTERCEPTOR,
            shipState: new ShipState(4, 3, 3, 3, 0),
            squadPointCost: 21,
            upgradeTypes: [],
            value: "saberSquadronPilot",
        },
        "saberSquadronPilot":
        {
            name: "Saber Squadron Pilot",
            description: "A TIE Interceptor pilot.",
            isUnique: false,
            primaryWeapon: new Weapon("Primary Weapon", true, 3, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.SABER_SQUADRON_TIE,
            shipState: new ShipState(4, 3, 3, 3, 0),
            squadPointCost: 21,
            upgradeTypes: [ UpgradeType.ELITE ],
            value: "saberSquadronPilot",
        },
        "scimitarSquadronPilot":
        {
            name: "Scimitar Squadron Pilot",
            description: "A TIE Bomber pilot.",
            isUnique: false,
            primaryWeapon: new Weapon("Primary Weapon", true, 2, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.TIE_BOMBER,
            shipState: new ShipState(2, 2, 2, 6, 0),
            squadPointCost: 16,
            upgradeTypes: [ UpgradeType.TORPEDO, UpgradeType.TORPEDO,
                    UpgradeType.MISSILE, UpgradeType.MISSILE, UpgradeType.BOMB ],
            value: "scimitarSquadronPilot",
        },
        "shadowSquadronPilot":
        {
            name: "Shadow Squadron Pilot",
            description: "A TIE Phantom pilot.",
            isUnique: false,
            primaryWeapon: new Weapon("Primary Weapon", true, 4, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.TIE_PHANTOM,
            shipState: new ShipState(5, 4, 2, 2, 2),
            squadPointCost: 27,
            upgradeTypes: [ UpgradeType.SENSOR, UpgradeType.CREW ],
            value: "shadowSquadronPilot",
        },
        "sigmaSquadronPilot":
        {
            name: "Sigma Squadron Pilot",
            description: "A TIE Phantom pilot.",
            isUnique: false,
            primaryWeapon: new Weapon("Primary Weapon", true, 4, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.TIE_PHANTOM,
            shipState: new ShipState(3, 4, 2, 2, 2),
            squadPointCost: 25,
            upgradeTypes: [ UpgradeType.SENSOR, UpgradeType.CREW ],
            value: "sigmaSquadronPilot",
        },
        "soontirFel":
        {
            name: "Soontir Fel",
            description: "A TIE Interceptor pilot.",
            isUnique: true,
            primaryWeapon: new Weapon("Primary Weapon", true, 3, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.TIE_INTERCEPTOR,
            shipState: new ShipState(9, 3, 3, 3, 0),
            squadPointCost: 27,
            upgradeTypes: [ UpgradeType.ELITE ],
            value: "soontirFel",
        },
        "stormSquadronPilot":
        {
            name: "Storm Squadron Pilot",
            description: "A TIE Advanced pilot.",
            isUnique: false,
            primaryWeapon: new Weapon("Primary Weapon", true, 2, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.TIE_ADVANCED,
            shipState: new ShipState(4, 2, 3, 3, 2),
            squadPointCost: 23,
            upgradeTypes: [ UpgradeType.MISSILE ],
            value: "stormSquadronPilot",
        },
        "talaSquadronPilot":
        {
            name: "Tala Squadron Pilot",
            description: "A Z-95 Headhunter pilot.",
            isUnique: false,
            primaryWeapon: new Weapon("Primary Weapon", true, 2, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.Z_95_HEADHUNTER,
            shipState: new ShipState(4, 2, 2, 2, 2),
            squadPointCost: 13,
            upgradeTypes: [ UpgradeType.MISSILE ],
            value: "talaSquadronPilot",
        },
        "tarnMison":
        {
            name: "Tarn Mison",
            description: "An X-Wing pilot.",
            isUnique: true,
            primaryWeapon: new Weapon("Primary Weapon", true, 3, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.X_WING,
            shipState: new ShipState(3, 3, 2, 3, 2),
            squadPointCost: 23,
            upgradeTypes: [ UpgradeType.TORPEDO, UpgradeType.ASTROMECH ],
            value: "tarnMison",
        },
        "tempestSquadronPilot":
        {
            name: "Tempest Squadron Pilot",
            description: "A TIE Advanced pilot.",
            isUnique: false,
            primaryWeapon: new Weapon("Primary Weapon", true, 2, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.TIE_ADVANCED,
            shipState: new ShipState(2, 2, 3, 3, 2),
            squadPointCost: 21,
            upgradeTypes: [ UpgradeType.MISSILE ],
            value: "tempestSquadronPilot",
        },
        "tenNumb":
        {
            name: "Ten Numb",
            description: "A B-Wing pilot.",
            isUnique: true,
            primaryWeapon: new Weapon("Primary Weapon", true, 3, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.B_WING,
            shipState: new ShipState(8, 3, 1, 3, 5),
            squadPointCost: 31,
            upgradeTypes: [ UpgradeType.ELITE, UpgradeType.SENSOR,
                    UpgradeType.CANNON, UpgradeType.TORPEDO,
                    UpgradeType.TORPEDO ],
            value: "tenNumb",
        },
        "tetranCowall":
        {
            name: "Tetran Cowall",
            description: "A TIE Interceptor pilot.",
            isUnique: true,
            primaryWeapon: new Weapon("Primary Weapon", true, 3, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.SABER_SQUADRON_TIE,
            shipState: new ShipState(7, 3, 3, 3, 0),
            squadPointCost: 24,
            upgradeTypes: [ UpgradeType.ELITE ],
            value: "tetranCowall",
        },
        "turrPhennir":
        {
            name: "Turr Phennir",
            description: "A TIE Interceptor pilot.",
            isUnique: true,
            primaryWeapon: new Weapon("Primary Weapon", true, 3, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.TIE_INTERCEPTOR,
            shipState: new ShipState(7, 3, 3, 3, 0),
            squadPointCost: 25,
            upgradeTypes: [ UpgradeType.ELITE ],
            value: "turrPhennir",
        },
        "tychoCelchu":
        {
            name: "Tycho Celchu",
            description: "An A-Wing pilot.",
            isUnique: true,
            primaryWeapon: new Weapon("Primary Weapon", true, 2, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.A_WING,
            shipState: new ShipState(8, 2, 3, 2, 2),
            squadPointCost: 26,
            upgradeTypes: [ UpgradeType.ELITE, UpgradeType.MISSILE ],
            value: "tychoCelchu",
        },
        "wedgeAntilles":
        {
            name: "Wedge Antilles",
            description: "An X-Wing pilot.",
            isUnique: true,
            primaryWeapon: new Weapon("Primary Weapon", true, 3, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.X_WING,
            shipState: new ShipState(9, 3, 2, 3, 2),
            squadPointCost: 29,
            upgradeTypes: [ UpgradeType.ELITE, UpgradeType.TORPEDO,
                    UpgradeType.ASTROMECH ],
            value: "wedgeAntilles",
        },
        "wesJanson":
        {
            name: "Wes Janson",
            description: "An X-Wing pilot.",
            isUnique: true,
            primaryWeapon: new Weapon("Primary Weapon", true, 3, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.X_WING,
            shipState: new ShipState(8, 3, 2, 3, 2),
            squadPointCost: 29,
            upgradeTypes: [ UpgradeType.ELITE, UpgradeType.TORPEDO,
                    UpgradeType.ASTROMECH ],
            value: "wesJanson",
        },
        "whisper":
        {
            name: "\"Whisper\"",
            description: "A TIE Phantom pilot.",
            isUnique: true,
            primaryWeapon: new Weapon("Primary Weapon", true, 4, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.TIE_PHANTOM,
            shipState: new ShipState(7, 4, 2, 2, 2),
            squadPointCost: 32,
            upgradeTypes: [ UpgradeType.ELITE, UpgradeType.SENSOR,
                    UpgradeType.CREW ],
            value: "whisper",
        },
        "wildSpaceFringer":
        {
            name: "Wild Space Fringer",
            description: "A YT-2400 pilot.",
            isUnique: false,
            primaryWeapon: new TurretWeapon("Primary Weapon", true, 2, [
                    Range.ONE, Range.TWO, Range.THREE ]),
            ship: Ship.YT_2400,
            shipState: new ShipState(2, 2, 2, 5, 5),
            squadPointCost: 30,
            upgradeTypes: [ UpgradeType.CANNON, UpgradeType.MISSILE,
                    UpgradeType.CREW ],
            value: "wildSpaceFringer",
        },
        "wingedGundark":
        {
            name: "\"Winged Gundark\"",
            description: "A TIE Fighter pilot.",
            isUnique: true,
            primaryWeapon: new Weapon("Primary Weapon", true, 2, [ Range.ONE,
                    Range.TWO, Range.THREE ]),
            ship: Ship.TIE_FIGHTER,
            shipState: new ShipState(5, 2, 3, 3, 0),
            squadPointCost: 15,
            upgradeTypes: [],
            value: "wingedGundark",
        },
    },

    values: function()
    {
        return Object.getOwnPropertyNames(Pilot.properties);
    },

    valuesByShip: function(ship)
    {
        var answer = [];
        var values = this.values();
        var properties = this.properties;

        for (var i = 0; i < values.length; i++)
        {
            var value = values[i];

            if (properties[value].ship === ship)
            {
                answer[answer.length] = value;
            }
        }

        return answer;
    },
};

if (Object.freeze)
{
    Object.freeze(Pilot)
};
