define([ "CardSet", "CardType", "ImageNameCreator", "Sphere", "Trait" ], function(CardSet, CardType, ImageNameCreator,
        Sphere, Trait)
{
    "use strict";
    var AllyCard =
    {
        BEORN: "beorn",
        BOFUR: "bofur",
        BROK_IRONFIST: "brokIronfist",
        DAUGHTER_OF_THE_NIMRODEL: "daughterOfTheNimrodel",
        DORI: "dori",
        EREBOR_HAMMERSMITH: "ereborHammersmith",
        EREBOR_RECORD_KEEPER: "ereborRecordKeeper",
        FARAMIR: "faramir",
        FILI: "fili",
        GANDALF: "gandalf",
        GIMLI: "gimli",
        GLEOWINE: "gleowine",
        GONDORIAN_SPEARMAN: "gondorianSpearman",
        GUARD_OF_THE_CITADEL: "guardOfTheCitadel",
        HAMA: "hama",
        HENAMARTH_RIVERSONG: "henamarthRiversong",
        HORSEBACK_ARCHER: "horsebackArcher",
        KILI: "kili",
        LEGOLAS: "legolas",
        LINDON_NAVIGATOR: "lindonNavigator",
        LONGBEARD_ORC_SLAYER: "longbeardOrcSlayer",
        LORIEN_GUIDE: "lorienGuide",
        MINER_OF_THE_IRON_HILLS: "minerOfTheIronHills",
        MITHLOND_SEA_WATCHER: "mithlondSeaWatcher",
        NORTHERN_TRACKER: "northernTracker",
        QUICKBEAM: "quickbeam",
        RIVENDELL_MINSTREL: "rivendellMinstrel",
        SAILOR_OF_LUNE: "sailorOfLune",
        SILVERLOAD_ARCHER: "silverloadArcher",
        SNOWBOURN_SCOUT: "snowbournScout",
        SON_OF_ARNOR: "sonOfArnor",
        VETERAN_AXEHAND: "veteranAxehand",
        VETERAN_OF_NANDUHIRION: "veteranOfNanduhirion",
        WANDERING_TOOK: "wanderingTook",
        WARDEN_OF_THE_HAVENS: "wardenOfTheHavens",
        WESTFOLD_HORSE_BREAKER: "westfoldHorseBreaker",
        WINGED_GUARDIAN: "wingedGuardian",
        ZIGIL_MINER: "zigilMiner",

        properties:
        {
            "beorn":
            {
                name: "Beorn",
                isUnique: true,
                cost: 6,
                willpower: 1,
                attack: 3,
                defense: 3,
                hitPoints: 6,
                traitKeys: [ Trait.BEORNING, Trait.WARRIOR ],
                sphereKey: Sphere.TACTICS,
                cardSetKey: CardSet.CORE,
                value: "beorn",
            },
            "bofur":
            {
                name: "Bofur",
                isUnique: true,
                cost: 3,
                willpower: 2,
                attack: 2,
                defense: 0,
                hitPoints: 3,
                traitKeys: [ Trait.DWARF ],
                sphereKey: Sphere.TACTICS,
                cardSetKey: CardSet.OVER_HILL_AND_UNDER_HILL,
                value: "bofur",
            },
            "brokIronfist":
            {
                name: "Brok Ironfist",
                isUnique: true,
                cost: 6,
                willpower: 2,
                attack: 2,
                defense: 1,
                hitPoints: 4,
                traitKeys: [ Trait.DWARF, Trait.WARRIOR ],
                sphereKey: Sphere.LEADERSHIP,
                cardSetKey: CardSet.CORE,
                value: "brokIronfist",
            },
            "daughterOfTheNimrodel":
            {
                name: "Daughter of the Nimrodel",
                cost: 3,
                willpower: 1,
                attack: 0,
                defense: 0,
                hitPoints: 1,
                traitKeys: [ Trait.SILVAN ],
                sphereKey: Sphere.LORE,
                cardSetKey: CardSet.CORE,
                value: "daughterOfTheNimrodel",
            },
            "dori":
            {
                name: "Dori",
                isUnique: true,
                cost: 3,
                willpower: 1,
                attack: 2,
                defense: 1,
                hitPoints: 3,
                traitKeys: [ Trait.DWARF ],
                sphereKey: Sphere.LORE,
                cardSetKey: CardSet.OVER_HILL_AND_UNDER_HILL,
                value: "dori",
            },
            "ereborHammersmith":
            {
                name: "Erebor Hammersmith",
                cost: 2,
                willpower: 1,
                attack: 1,
                defense: 1,
                hitPoints: 3,
                traitKeys: [ Trait.DWARF, Trait.CRAFTSMAN ],
                sphereKey: Sphere.LORE,
                cardSetKey: CardSet.CORE,
                value: "ereborHammersmith",
            },
            "ereborRecordKeeper":
            {
                name: "Erebor Record Keeper",
                cost: 1,
                willpower: 1,
                attack: 0,
                defense: 0,
                hitPoints: 1,
                traitKeys: [ Trait.DWARF ],
                sphereKey: Sphere.LORE,
                cardSetKey: CardSet.KHAZAD_DUM,
                value: "ereborRecordKeeper",
            },
            "faramir":
            {
                name: "Faramir",
                isUnique: true,
                cost: 4,
                willpower: 2,
                attack: 1,
                defense: 2,
                hitPoints: 3,
                traitKeys: [ Trait.GONDOR, Trait.NOBLE, Trait.RANGER ],
                sphereKey: Sphere.LEADERSHIP,
                cardSetKey: CardSet.CORE,
                value: "faramir",
            },
            "fili":
            {
                name: "Fili",
                isUnique: true,
                cost: 3,
                willpower: 1,
                attack: 1,
                defense: 1,
                hitPoints: 2,
                traitKeys: [ Trait.DWARF ],
                sphereKey: Sphere.LEADERSHIP,
                cardSetKey: CardSet.OVER_HILL_AND_UNDER_HILL,
                value: "fili",
            },
            "gandalf":
            {
                name: "Gandalf",
                isUnique: true,
                cost: 5,
                willpower: 4,
                attack: 4,
                defense: 4,
                hitPoints: 4,
                traitKeys: [ Trait.ISTARI ],
                sphereKey: Sphere.NEUTRAL,
                cardSetKey: CardSet.CORE,
                value: "gandalf",
            },
            "gimli":
            {
                name: "Gimli",
                isUnique: true,
                cost: 4,
                willpower: 2,
                attack: 2,
                defense: 2,
                hitPoints: 3,
                traitKeys: [ Trait.DWARF, Trait.WARRIOR ],
                sphereKey: Sphere.LEADERSHIP,
                cardSetKey: CardSet.THE_TREASON_OF_SARUMAN,
                value: "gimli",
            },
            "gleowine":
            {
                name: "Gléowine",
                isUnique: true,
                cost: 2,
                willpower: 1,
                attack: 0,
                defense: 0,
                hitPoints: 2,
                traitKeys: [ Trait.MINSTREL, Trait.ROHAN ],
                sphereKey: Sphere.LORE,
                cardSetKey: CardSet.CORE,
                value: "gleowine",
            },
            "gondorianSpearman":
            {
                name: "Gondorian Spearman",
                cost: 2,
                willpower: 0,
                attack: 1,
                defense: 1,
                hitPoints: 1,
                traitKeys: [ Trait.GONDOR, Trait.WARRIOR ],
                sphereKey: Sphere.TACTICS,
                cardSetKey: CardSet.CORE,
                value: "gondorianSpearman",
            },
            "guardOfTheCitadel":
            {
                name: "Guard of the Citadel",
                cost: 2,
                willpower: 1,
                attack: 1,
                defense: 0,
                hitPoints: 2,
                traitKeys: [ Trait.GONDOR, Trait.WARRIOR ],
                sphereKey: Sphere.LEADERSHIP,
                cardSetKey: CardSet.CORE,
                value: "guardOfTheCitadel",
            },
            "hama":
            {
                name: "Hama",
                isUnique: true,
                cost: 3,
                willpower: 1,
                attack: 2,
                defense: 2,
                hitPoints: 2,
                traitKeys: [ Trait.ROHAN, Trait.WARRIOR ],
                sphereKey: Sphere.SPIRIT,
                cardSetKey: CardSet.THE_TREASON_OF_SARUMAN,
                value: "hama",
            },
            "henamarthRiversong":
            {
                name: "Henamarth Riversong",
                isUnique: true,
                cost: 1,
                willpower: 1,
                attack: 1,
                defense: 0,
                hitPoints: 1,
                traitKeys: [ Trait.SILVAN ],
                sphereKey: Sphere.LORE,
                cardSetKey: CardSet.CORE,
                value: "henamarthRiversong",
            },
            "horsebackArcher":
            {
                name: "Horseback Archer",
                cost: 3,
                willpower: 0,
                attack: 2,
                defense: 1,
                hitPoints: 2,
                traitKeys: [ Trait.ROHAN, Trait.ARCHER ],
                sphereKey: Sphere.TACTICS,
                cardSetKey: CardSet.CORE,
                value: "horsebackArcher",
            },
            "kili":
            {
                name: "Kili",
                isUnique: true,
                cost: 3,
                willpower: 1,
                attack: 1,
                defense: 1,
                hitPoints: 2,
                traitKeys: [ Trait.DWARF ],
                sphereKey: Sphere.SPIRIT,
                cardSetKey: CardSet.OVER_HILL_AND_UNDER_HILL,
                value: "kili",
            },
            "legolas":
            {
                name: "Legolas",
                isUnique: true,
                cost: 4,
                willpower: 1,
                attack: 3,
                defense: 1,
                hitPoints: 3,
                traitKeys: [ Trait.SILVAN, Trait.WARRIOR ],
                sphereKey: Sphere.TACTICS,
                cardSetKey: CardSet.THE_TREASON_OF_SARUMAN,
                value: "legolas",
            },
            "lindonNavigator":
            {
                name: "Lindon Navigator",
                cost: 2,
                willpower: 2,
                attack: 1,
                defense: 1,
                hitPoints: 2,
                traitKeys: [ Trait.NOLDOR, Trait.SCOUT ],
                sphereKey: Sphere.LORE,
                cardSetKey: CardSet.THE_GREY_HAVENS,
                value: "lindonNavigator",
            },
            "longbeardOrcSlayer":
            {
                name: "Longbeard Orc Slayer",
                cost: 4,
                willpower: 0,
                attack: 2,
                defense: 1,
                hitPoints: 3,
                traitKeys: [ Trait.DWARF, Trait.WARRIOR ],
                sphereKey: Sphere.LEADERSHIP,
                cardSetKey: CardSet.CORE,
                value: "longbeardOrcSlayer",
            },
            "lorienGuide":
            {
                name: "Lórien Guide",
                cost: 3,
                willpower: 1,
                attack: 1,
                defense: 0,
                hitPoints: 2,
                traitKeys: [ Trait.SILVAN, Trait.SCOUT ],
                sphereKey: Sphere.SPIRIT,
                cardSetKey: CardSet.CORE,
                value: "lorienGuide",
            },
            "minerOfTheIronHills":
            {
                name: "Miner of the Iron Hills",
                cost: 2,
                willpower: 0,
                attack: 1,
                defense: 1,
                hitPoints: 2,
                traitKeys: [ Trait.DWARF ],
                sphereKey: Sphere.LORE,
                cardSetKey: CardSet.CORE,
                value: "minerOfTheIronHills",
            },
            "mithlondSeaWatcher":
            {
                name: "Mithlond Sea-Watcher",
                cost: 2,
                willpower: 1,
                attack: 1,
                defense: 0,
                hitPoints: 2,
                traitKeys: [ Trait.NOLDOR, Trait.WARRIOR ],
                sphereKey: Sphere.TACTICS,
                cardSetKey: CardSet.THE_GREY_HAVENS,
                value: "mithlondSeaWatcher",
            },
            "northernTracker":
            {
                name: "Northern Tracker",
                cost: 4,
                willpower: 1,
                attack: 2,
                defense: 2,
                hitPoints: 3,
                traitKeys: [ Trait.DUNEDAIN, Trait.RANGER ],
                sphereKey: Sphere.SPIRIT,
                cardSetKey: CardSet.CORE,
                value: "northernTracker",
            },
            "quickbeam":
            {
                name: "Quickbeam",
                isUnique: true,
                cost: 2,
                willpower: 2,
                attack: 3,
                defense: 1,
                hitPoints: 3,
                traitKeys: [ Trait.ENT ],
                sphereKey: Sphere.LORE,
                cardSetKey: CardSet.THE_TREASON_OF_SARUMAN,
                value: "quickbeam",
            },
            "rivendellMinstrel":
            {
                name: "Rivendell Minstrel",
                cost: 3,
                willpower: 2,
                attack: 0,
                defense: 0,
                hitPoints: 1,
                traitKeys: [ Trait.NOLDOR ],
                sphereKey: Sphere.LORE,
                cardSetKey: CardSet.SOM1_THE_HUNT_FOR_GOLLUM,
                value: "rivendellMinstrel",
            },
            "sailorOfLune":
            {
                name: "Sailor of Lune",
                cost: 2,
                willpower: 1,
                attack: 1,
                defense: 0,
                hitPoints: 2,
                traitKeys: [ Trait.NOLDOR, Trait.SCOUT ],
                sphereKey: Sphere.SPIRIT,
                cardSetKey: CardSet.THE_GREY_HAVENS,
                value: "sailorOfLune",
            },
            "silverloadArcher":
            {
                name: "Silverload Archer",
                cost: 3,
                willpower: 1,
                attack: 2,
                defense: 0,
                hitPoints: 1,
                traitKeys: [ Trait.ARCHER, Trait.SILVAN ],
                sphereKey: Sphere.LEADERSHIP,
                cardSetKey: CardSet.CORE,
                value: "silverloadArcher",
            },
            "snowbournScout":
            {
                name: "Snowbourn Scout",
                cost: 1,
                willpower: 0,
                attack: 0,
                defense: 1,
                hitPoints: 1,
                traitKeys: [ Trait.ROHAN, Trait.SCOUT ],
                sphereKey: Sphere.LEADERSHIP,
                cardSetKey: CardSet.CORE,
                value: "snowbournScout",
            },
            "sonOfArnor":
            {
                name: "Son of Arnor",
                cost: 3,
                willpower: 0,
                attack: 2,
                defense: 0,
                hitPoints: 2,
                traitKeys: [ Trait.DUNEDAIN ],
                sphereKey: Sphere.LEADERSHIP,
                cardSetKey: CardSet.CORE,
                value: "sonOfArnor",
            },
            "veteranAxehand":
            {
                name: "Veteran Axehand",
                cost: 2,
                willpower: 0,
                attack: 2,
                defense: 1,
                hitPoints: 2,
                traitKeys: [ Trait.DWARF, Trait.WARRIOR ],
                sphereKey: Sphere.TACTICS,
                cardSetKey: CardSet.CORE,
                value: "veteranAxehand",
            },
            "veteranOfNanduhirion":
            {
                name: "Veteran of Nanduhirion",
                cost: 4,
                willpower: 0,
                attack: 3,
                defense: 2,
                hitPoints: 3,
                traitKeys: [ Trait.DWARF, Trait.WARRIOR ],
                sphereKey: Sphere.TACTICS,
                cardSetKey: CardSet.KHAZAD_DUM,
                value: "veteranOfNanduhirion",
            },
            "wanderingTook":
            {
                name: "Wandering Took",
                cost: 2,
                willpower: 1,
                attack: 1,
                defense: 1,
                hitPoints: 2,
                traitKeys: [ Trait.HOBBIT ],
                sphereKey: Sphere.SPIRIT,
                cardSetKey: CardSet.CORE,
                value: "wanderingTook",
            },
            "wardenOfTheHavens":
            {
                name: "Warden of the Havens",
                cost: 2,
                willpower: 0,
                attack: 1,
                defense: 1,
                hitPoints: 3,
                traitKeys: [ Trait.NOLDOR, Trait.WARRIOR ],
                sphereKey: Sphere.LEADERSHIP,
                cardSetKey: CardSet.THE_GREY_HAVENS,
                value: "wardenOfTheHavens",
            },
            "westfoldHorseBreaker":
            {
                name: "Westfold Horse-Breaker",
                cost: 2,
                willpower: 1,
                attack: 0,
                defense: 1,
                hitPoints: 1,
                traitKeys: [ Trait.ROHAN ],
                sphereKey: Sphere.LORE,
                cardSetKey: CardSet.SOM1_THE_HUNT_FOR_GOLLUM,
                value: "westfoldHorseBreaker",
            },
            "wingedGuardian":
            {
                name: "Winged Guardian",
                cost: 2,
                willpower: 0,
                attack: 0,
                defense: 4,
                hitPoints: 1,
                traitKeys: [ Trait.CREATURE, Trait.EAGLE ],
                sphereKey: Sphere.LORE,
                cardSetKey: CardSet.SOM1_THE_HUNT_FOR_GOLLUM,
                value: "wingedGuardian",
            },
            "zigilMiner":
            {
                name: "Zigil Miner",
                cost: 2,
                willpower: 1,
                attack: 1,
                defense: 1,
                hitPoints: 1,
                traitKeys: [ Trait.DWARF ],
                sphereKey: Sphere.SPIRIT,
                cardSetKey: CardSet.KHAZAD_DUM,
                value: "zigilMiner",
            },
        },

        values: function()
        {
            return Object.getOwnPropertyNames(AllyCard.properties);
        },
    };

    AllyCard.values().forEach(function(cardKey)
    {
        var card = AllyCard.properties[cardKey];
        card.cardSet = CardSet.properties[card.cardSetKey];
        card.cardType = CardType.ALLY;
        card.sphere = Sphere.properties[card.sphereKey];

        if (!card.image)
        {
            card.image = ImageNameCreator.create(card);
        }
    });

    if (Object.freeze)
    {
        Object.freeze(AllyCard);
    }

    return AllyCard;
});
