define(
        [ "CardSet", "CardSubset", "CardType", "ImageNameCreator", "Sphere", "Trait" ],
        function(CardSet, CardSubset, CardType, ImageNameCreator, Sphere, Trait)
        {
            "use strict";
            var HeroCard =
            {
                AMARTHIUL: "amarthiul",
                ARAGORN_CORE: "aragornCore",
                ARAGORN_TLR: "aragornTLR",
                ARAGORN_TTOS: "aragornTToS",
                ARAGORN_TWITW: "aragornTWitW",
                BALIN: "balin",
                BARD_THE_BOWMAN: "bardTheBowman",
                BEORN: "beorn",
                BERAVOR: "beravor",
                BEREGOND: "beregond",
                BIFUR: "bifur",
                BILBO_BAGGINS_OHAUH: "bilboBagginsOHaUH",
                BILBO_BAGGINS_OTD: "bilboBagginsOtD",
                BILBO_BAGGINS_THFG: "bilboBagginsTHfG",
                BOMBUR: "bombur",
                BOROMIR_HON: "boromirHoN",
                BOROMIR_SOM: "boromirSoM",
                BRAND_SON_OF_BAIN: "brandSonOfBain",
                CALDARA: "caldara",
                CELEBORN: "celeborn",
                CIRDAN_THE_SHIPWRIGHT: "cirdanTheShipwright",
                DAIN_IRONFOOT: "dainIronfoot",
                DAMROD: "damrod",
                DENETHOR: "denethor",
                DORI: "dori",
                DUNHERE: "dunhere",
                DWALIN: "dwalin",
                ELEANOR: "eleanor",
                ELLADAN: "elladan",
                ELROHIR: "elrohir",
                ELROND: "elrond",
                EOMER: "eomer",
                EOWYN: "eowyn",
                ERESTOR: "erestor",
                ERKENBRAND: "erkenbrand",
                FARAMIR_AOO: "faramirAoO",
                FARAMIR_TLOS: "faramirTLoS",
                FATTY_BOLGER: "fattyBolger",
                FRODO_BAGGINS_CATC: "frodoBagginsCatC",
                FRODO_BAGGINS_TBR: "frodoBagginsTBR",
                FRODO_BAGGINS_TLOS: "frodoBagginsTLoS",
                FRODO_BAGGINS_TRD: "frodoBagginsTRD",
                GALADRIEL: "galadriel",
                GALDOR_OF_THE_HAVENS: "galdorOfTheHavens",
                GANDALF: "gandalf",
                GIMLI: "gimli",
                GLOIN: "gloin",
                GLORFINDEL_CORE: "glorfindelCore",
                GLORFINEL_FOS: "glorfindelFoS",
                GRIMA: "grima",
                HALBARAD: "halbarad",
                HALDIR_OF_LORIEN: "haldirOfLorien",
                HAMA: "hama",
                HIRLUIN_THE_FAIR: "hirluinTheFair",
                IDRAEN: "idraen",
                LEGOLAS: "legolas",
                MABLUNG: "mablung",
                MERRY_TWOE: "merryTWoE",
                MERRY_TBR: "merryTBR",
                MIRLONDE: "mirlonde",
                NORI: "nori",
                OIN: "oin",
                ORI: "ori",
                PIPPIN_EAAD: "pippinEaAD",
                PIPPIN_TBR: "pippinTBR",
                PRINCE_IMRAHIL: "princeImrahil",
                ROSSIEL: "rossiel",
                SAM_GAMGEE: "samGamgee",
                THALIN: "thalin",
                THEODEN_TMV: "theodenTMV",
                THEODEN_TTOS: "theodenTToS",
                THEODRED: "theodred",
                THORIN_OAKENSHIELD: "thorinOakenshield",
                TREEBEARD: "treebeard",

                properties:
                {
                    "amarthiul":
                    {
                        name: "Amarthiúl",
                        threatCost: 10,
                        willpower: 1,
                        attack: 3,
                        defense: 3,
                        hitPoints: 3,
                        traitKeys: [ Trait.DUNEDAIN, Trait.RANGER, Trait.WARRIOR ],
                        sphereKey: Sphere.LEADERSHIP,
                        cardSetKey: CardSet.ANGMAR_AWAKENED,
                        cardSubsetKey: CardSubset.AA5_THE_BATTLE_OF_CARN_DUM,
                        cardSetNumber: 107,
                        // card missing from cardgamedb.com
                        image: "https://s3.amazonaws.com/hallofbeorn-resources/Images/Cards/The-Battle-of-Carn-Dum/Amarthiúl.jpg",
                        value: "amarthiul",
                    },
                    "aragornCore":
                    {
                        name: "Aragorn",
                        threatCost: 12,
                        willpower: 2,
                        attack: 3,
                        defense: 2,
                        hitPoints: 5,
                        traitKeys: [ Trait.DUNEDAIN, Trait.NOBLE, Trait.RANGER ],
                        sphereKey: Sphere.LEADERSHIP,
                        cardSetKey: CardSet.CORE,
                        cardSetNumber: 1,
                        value: "aragornCore",
                    },
                    "aragornTLR":
                    {
                        name: "Aragorn",
                        threatCost: 12,
                        willpower: 2,
                        attack: 3,
                        defense: 2,
                        hitPoints: 5,
                        traitKeys: [ Trait.DUNEDAIN, Trait.RANGER, Trait.WARRIOR ],
                        sphereKey: Sphere.TACTICS,
                        cardSetKey: CardSet.THE_LOST_REALM,
                        cardSetNumber: 1,
                        value: "aragornTLR",
                    },
                    "aragornTToS":
                    {
                        name: "Aragorn",
                        threatCost: 0,
                        willpower: 2,
                        attack: 3,
                        defense: 2,
                        hitPoints: 5,
                        traitKeys: [ Trait.DUNEDAIN, Trait.NOBLE, Trait.RANGER ],
                        sphereKey: Sphere.FELLOWSHIP,
                        cardSetKey: CardSet.THE_TREASON_OF_SARUMAN,
                        cardSetNumber: 1,
                        value: "aragornTToS",
                    },
                    "aragornTWitW":
                    {
                        name: "Aragorn",
                        threatCost: 12,
                        willpower: 2,
                        attack: 3,
                        defense: 2,
                        hitPoints: 5,
                        traitKeys: [ Trait.DUNEDAIN, Trait.RANGER ],
                        sphereKey: Sphere.LORE,
                        cardSetKey: CardSet.DWARROWDELF,
                        cardSubsetKey: CardSubset.D3_THE_WATCHER_IN_THE_WATER,
                        cardSetNumber: 53,
                        value: "aragornTWitW",
                    },
                    "balin":
                    {
                        name: "Balin",
                        threatCost: 9,
                        willpower: 2,
                        attack: 1,
                        defense: 2,
                        hitPoints: 4,
                        traitKeys: [ Trait.DWARF ],
                        sphereKey: Sphere.LEADERSHIP,
                        cardSetKey: CardSet.ON_THE_DOORSTEP,
                        cardSetNumber: 2,
                        value: "balin",
                    },
                    "bardTheBowman":
                    {
                        name: "Bard the Bowman",
                        threatCost: 11,
                        willpower: 2,
                        attack: 3,
                        defense: 2,
                        hitPoints: 4,
                        traitKeys: [ Trait.ESGAROTH, Trait.WARRIOR ],
                        sphereKey: Sphere.TACTICS,
                        cardSetKey: CardSet.ON_THE_DOORSTEP,
                        cardSetNumber: 3,
                        value: "bardTheBowman",
                    },
                    "beorn":
                    {
                        name: "Beorn",
                        threatCost: 12,
                        willpower: 0,
                        attack: 5,
                        defense: 1,
                        hitPoints: 10,
                        traitKeys: [ Trait.BEORNING, Trait.WARRIOR ],
                        sphereKey: Sphere.TACTICS,
                        cardSetKey: CardSet.OVER_HILL_AND_UNDER_HILL,
                        cardSetNumber: 5,
                        value: "beorn",
                    },
                    "beravor":
                    {
                        name: "Beravor",
                        threatCost: 10,
                        willpower: 2,
                        attack: 2,
                        defense: 2,
                        hitPoints: 4,
                        traitKeys: [ Trait.DUNEDAIN, Trait.RANGER ],
                        sphereKey: Sphere.LORE,
                        cardSetKey: CardSet.CORE,
                        cardSetNumber: 12,
                        value: "beravor",
                    },
                    "beregond":
                    {
                        name: "Beregond",
                        threatCost: 10,
                        willpower: 0,
                        attack: 1,
                        defense: 4,
                        hitPoints: 4,
                        traitKeys: [ Trait.GONDOR, Trait.WARRIOR ],
                        sphereKey: Sphere.TACTICS,
                        cardSetKey: CardSet.HEIRS_OF_NUMENOR,
                        cardSetNumber: 1,
                        value: "beregond",
                    },
                    "bifur":
                    {
                        name: "Bifur",
                        threatCost: 7,
                        willpower: 2,
                        attack: 1,
                        defense: 2,
                        hitPoints: 3,
                        traitKeys: [ Trait.DWARF ],
                        sphereKey: Sphere.LORE,
                        cardSetKey: CardSet.KHAZAD_DUM,
                        cardSetNumber: 2,
                        value: "bifur",
                    },
                    "bilboBagginsOHaUH":
                    {
                        name: "Bilbo Baggins",
                        threatCost: 0,
                        willpower: 1,
                        attack: 1,
                        defense: 1,
                        hitPoints: 3,
                        traitKeys: [ Trait.HOBBIT ],
                        sphereKey: Sphere.BAGGINS,
                        cardSetKey: CardSet.OVER_HILL_AND_UNDER_HILL,
                        cardSetNumber: 1,
                        value: "bilboBagginsOHaUH",
                    },
                    "bilboBagginsOtD":
                    {
                        name: "Bilbo Baggins",
                        threatCost: 0,
                        willpower: 1,
                        attack: 1,
                        defense: 1,
                        hitPoints: 3,
                        traitKeys: [ Trait.HOBBIT, Trait.BURGLAR ],
                        sphereKey: Sphere.BAGGINS,
                        cardSetKey: CardSet.ON_THE_DOORSTEP,
                        cardSetNumber: 1,
                        value: "bilboBagginsOtD",
                    },
                    "bilboBagginsTHfG":
                    {
                        name: "Bilbo Baggins",
                        threatCost: 9,
                        willpower: 1,
                        attack: 1,
                        defense: 2,
                        hitPoints: 2,
                        traitKeys: [ Trait.HOBBIT ],
                        sphereKey: Sphere.LORE,
                        cardSetKey: CardSet.SHADOWS_OF_MIRKWOOD,
                        cardSubsetKey: CardSubset.SOM1_THE_HUNT_FOR_GOLLUM,
                        cardSetNumber: 1,
                        value: "bilboBagginsTHfG",
                    },
                    "bombur":
                    {
                        name: "Bombur",
                        threatCost: 8,
                        willpower: 0,
                        attack: 1,
                        defense: 2,
                        hitPoints: 5,
                        traitKeys: [ Trait.DWARF ],
                        sphereKey: Sphere.LORE,
                        cardSetKey: CardSet.ON_THE_DOORSTEP,
                        cardSetNumber: 5,
                        value: "bombur",
                    },
                    "boromirHoN":
                    {
                        name: "Boromir",
                        threatCost: 11,
                        willpower: 1,
                        attack: 3,
                        defense: 2,
                        hitPoints: 5,
                        traitKeys: [ Trait.GONDOR, Trait.WARRIOR, Trait.NOBLE ],
                        sphereKey: Sphere.LEADERSHIP,
                        cardSetKey: CardSet.HEIRS_OF_NUMENOR,
                        cardSetNumber: 2,
                        value: "boromirHoN",
                    },
                    "boromirSoM":
                    {
                        name: "Boromir",
                        threatCost: 11,
                        willpower: 1,
                        attack: 3,
                        defense: 2,
                        hitPoints: 5,
                        traitKeys: [ Trait.GONDOR, Trait.NOBLE, Trait.WARRIOR ],
                        sphereKey: Sphere.TACTICS,
                        cardSetKey: CardSet.SHADOWS_OF_MIRKWOOD,
                        cardSubsetKey: CardSubset.SOM5_THE_DEAD_MARSHES,
                        cardSetNumber: 95,
                        value: "boromirSoM",
                    },
                    "brandSonOfBain":
                    {
                        name: "Brand Son of Bain",
                        threatCost: 10,
                        willpower: 2,
                        attack: 3,
                        defense: 2,
                        hitPoints: 3,
                        traitKeys: [ Trait.DALE ],
                        sphereKey: Sphere.LORE,
                        cardSetKey: CardSet.SHADOWS_OF_MIRKWOOD,
                        cardSubsetKey: CardSubset.SOM4_THE_HILLS_OF_EMYN_MUIL,
                        cardSetNumber: 72,
                        value: "brandSonOfBain",
                    },
                    "caldara":
                    {
                        name: "Caldara",
                        threatCost: 8,
                        willpower: 2,
                        attack: 1,
                        defense: 2,
                        hitPoints: 3,
                        traitKeys: [ Trait.GONDOR ],
                        sphereKey: Sphere.SPIRIT,
                        cardSetKey: CardSet.AGAINST_THE_SHADOW,
                        cardSubsetKey: CardSubset.ATS5_THE_BLOOD_OF_GONDOR,
                        cardSetNumber: 107,
                        value: "caldara",
                    },
                    "celeborn":
                    {
                        name: "Celeborn",
                        threatCost: 11,
                        willpower: 3,
                        attack: 2,
                        defense: 2,
                        hitPoints: 4,
                        traitKeys: [ Trait.SILVAN, Trait.NOBLE ],
                        sphereKey: Sphere.LEADERSHIP,
                        cardSetKey: CardSet.THE_RING_MAKER,
                        cardSubsetKey: CardSubset.TRM1_THE_DUNLAND_TRAP,
                        cardSetNumber: 1,
                        value: "celeborn",
                    },
                    "cirdanTheShipwright":
                    {
                        name: "Círdan the Shipwright",
                        threatCost: 12,
                        willpower: 4,
                        attack: 2,
                        defense: 2,
                        hitPoints: 4,
                        traitKeys: [ Trait.NOLDOR, Trait.NOBLE ],
                        sphereKey: Sphere.SPIRIT,
                        cardSetKey: CardSet.THE_GREY_HAVENS,
                        cardSetNumber: 1,
                        value: "cirdanTheShipwright",
                    },
                    "dainIronfoot":
                    {
                        name: "Dain Ironfoot",
                        threatCost: 11,
                        willpower: 1,
                        attack: 2,
                        defense: 3,
                        hitPoints: 5,
                        traitKeys: [ Trait.DWARF ],
                        sphereKey: Sphere.LEADERSHIP,
                        cardSetKey: CardSet.SHADOWS_OF_MIRKWOOD,
                        cardSubsetKey: CardSubset.SOM6_RETURN_TO_MIRKWOOD,
                        cardSetNumber: 116,
                        value: "dainIronfoot",
                    },
                    "damrod":
                    {
                        name: "Damrod",
                        threatCost: 9,
                        willpower: 2,
                        attack: 2,
                        defense: 1,
                        hitPoints: 4,
                        traitKeys: [ Trait.GONDOR, Trait.RANGER ],
                        sphereKey: Sphere.LORE,
                        cardSetKey: CardSet.THE_LAND_OF_SHADOW,
                        cardSetNumber: 3,
                        value: "damrod",
                    },
                    "denethor":
                    {
                        name: "Denethor",
                        threatCost: 8,
                        willpower: 1,
                        attack: 1,
                        defense: 3,
                        hitPoints: 3,
                        traitKeys: [ Trait.GONDOR, Trait.NOBLE, Trait.STEWARD ],
                        sphereKey: Sphere.LORE,
                        cardSetKey: CardSet.CORE,
                        cardSetNumber: 10,
                        value: "denethor",
                    },
                    "dori":
                    {
                        name: "Dori",
                        threatCost: 10,
                        willpower: 1,
                        attack: 2,
                        defense: 2,
                        hitPoints: 5,
                        traitKeys: [ Trait.DWARF ],
                        sphereKey: Sphere.TACTICS,
                        cardSetKey: CardSet.ANGMAR_AWAKENED,
                        cardSubsetKey: CardSubset.AA3_ACROSS_THE_ETTENMOORS,
                        cardSetNumber: 54,
                        value: "dori",
                    },
                    "dunhere":
                    {
                        name: "Dúnhere",
                        threatCost: 8,
                        willpower: 1,
                        attack: 2,
                        defense: 1,
                        hitPoints: 4,
                        traitKeys: [ Trait.ROHAN, Trait.WARRIOR ],
                        sphereKey: Sphere.SPIRIT,
                        cardSetKey: CardSet.CORE,
                        cardSetNumber: 9,
                        value: "dunhere",
                    },
                    "dwalin":
                    {
                        name: "Dwalin",
                        threatCost: 9,
                        willpower: 1,
                        attack: 2,
                        defense: 2,
                        hitPoints: 4,
                        traitKeys: [ Trait.DWARF ],
                        sphereKey: Sphere.SPIRIT,
                        cardSetKey: CardSet.KHAZAD_DUM,
                        cardSetNumber: 1,
                        value: "dwalin",
                    },
                    "eleanor":
                    {
                        name: "Eleanor",
                        threatCost: 7,
                        willpower: 1,
                        attack: 1,
                        defense: 2,
                        hitPoints: 3,
                        traitKeys: [ Trait.GONDOR, Trait.NOBLE ],
                        sphereKey: Sphere.SPIRIT,
                        cardSetKey: CardSet.CORE,
                        cardSetNumber: 8,
                        value: "eleanor",
                    },
                    "elladan":
                    {
                        name: "Elladan",
                        threatCost: 10,
                        willpower: 2,
                        attack: 1,
                        defense: 2,
                        hitPoints: 4,
                        traitKeys: [ Trait.NOLDOR, Trait.NOBLE, Trait.RANGER ],
                        sphereKey: Sphere.TACTICS,
                        cardSetKey: CardSet.DWARROWDELF,
                        cardSubsetKey: CardSubset.D2_ROAD_TO_RIVENDELL,
                        cardSetNumber: 28,
                        value: "elladan",
                    },
                    "elrohir":
                    {
                        name: "Elrohir",
                        threatCost: 10,
                        willpower: 2,
                        attack: 2,
                        defense: 1,
                        hitPoints: 4,
                        traitKeys: [ Trait.NOLDOR, Trait.NOBLE, Trait.RANGER ],
                        sphereKey: Sphere.LEADERSHIP,
                        cardSetKey: CardSet.DWARROWDELF,
                        cardSubsetKey: CardSubset.D1_THE_REDHORN_GATE,
                        cardSetNumber: 1,
                        value: "elrohir",
                    },
                    "elrond":
                    {
                        name: "Elrond",
                        threatCost: 13,
                        willpower: 3,
                        attack: 2,
                        defense: 3,
                        hitPoints: 4,
                        traitKeys: [ Trait.NOLDOR, Trait.NOBLE ],
                        sphereKey: Sphere.LORE,
                        cardSetKey: CardSet.SHADOWS_OF_MIRKWOOD,
                        cardSubsetKey: CardSubset.D6_SHADOW_AND_FLAME,
                        cardSetNumber: 128,
                        value: "elrond",
                    },
                    "eomer":
                    {
                        name: "Éomer",
                        threatCost: 10,
                        willpower: 1,
                        attack: 3,
                        defense: 2,
                        hitPoints: 4,
                        traitKeys: [ Trait.ROHAN, Trait.NOBLE, Trait.WARRIOR ],
                        sphereKey: Sphere.TACTICS,
                        cardSetKey: CardSet.THE_VOICE_OF_ISENGARD,
                        cardSetNumber: 1,
                        value: "eomer",
                    },
                    "eowyn":
                    {
                        name: "Éowyn",
                        threatCost: 9,
                        willpower: 4,
                        attack: 1,
                        defense: 1,
                        hitPoints: 3,
                        traitKeys: [ Trait.NOBLE, Trait.ROHAN ],
                        sphereKey: Sphere.SPIRIT,
                        cardSetKey: CardSet.CORE,
                        cardSetNumber: 7,
                        value: "eowyn",
                    },
                    "erestor":
                    {
                        name: "Erestor",
                        threatCost: 10,
                        willpower: 2,
                        attack: 2,
                        defense: 2,
                        hitPoints: 4,
                        traitKeys: [ Trait.NOLDOR ],
                        sphereKey: Sphere.LORE,
                        cardSetKey: CardSet.ANGMAR_AWAKENED,
                        cardSubsetKey: CardSubset.AA4_THE_TREACHERY_OF_RHUDAUR,
                        cardSetNumber: 84,
                        value: "erestor",
                    },
                    "erkenbrand":
                    {
                        name: "Erkenbrand",
                        threatCost: 10,
                        willpower: 1,
                        attack: 2,
                        defense: 3,
                        hitPoints: 4,
                        traitKeys: [ Trait.ROHAN, Trait.WARRIOR ],
                        sphereKey: Sphere.LEADERSHIP,
                        cardSetKey: CardSet.THE_RING_MAKER,
                        cardSubsetKey: CardSubset.TRM6_THE_ANTLERED_CROWN,
                        cardSetNumber: 137,
                        value: "erkenbrand",
                    },
                    "faramirAoO":
                    {
                        name: "Faramir",
                        threatCost: 11,
                        willpower: 2,
                        attack: 2,
                        defense: 2,
                        hitPoints: 5,
                        traitKeys: [ Trait.GONDOR, Trait.RANGER, Trait.NOBLE ],
                        sphereKey: Sphere.LORE,
                        cardSetKey: CardSet.AGAINST_THE_SHADOW,
                        cardSubsetKey: CardSubset.ATS4_ASSAULT_ON_OSGILIATH,
                        cardSetNumber: 81,
                        value: "faramirAoO",
                    },
                    "faramirTLoS":
                    {
                        name: "Faramir",
                        threatCost: 11,
                        willpower: 2,
                        attack: 2,
                        defense: 2,
                        hitPoints: 5,
                        traitKeys: [ Trait.GONDOR, Trait.NOBLE, Trait.RANGER ],
                        sphereKey: Sphere.LEADERSHIP,
                        cardSetKey: CardSet.THE_LAND_OF_SHADOW,
                        cardSetNumber: 2,
                        value: "faramirTLoS",
                    },
                    "fattyBolger":
                    {
                        name: "Fatty Bolger",
                        threatCost: 7,
                        willpower: 1,
                        attack: 1,
                        defense: 2,
                        hitPoints: 3,
                        traitKeys: [ Trait.HOBBIT ],
                        sphereKey: Sphere.SPIRIT,
                        cardSetKey: CardSet.THE_BLACK_RIDERS,
                        cardSetNumber: 5,
                        value: "fattyBolger",
                    },
                    "frodoBagginsCatC":
                    {
                        name: "Frodo Baggins",
                        threatCost: 7,
                        willpower: 2,
                        attack: 1,
                        defense: 2,
                        hitPoints: 2,
                        traitKeys: [ Trait.HOBBIT ],
                        sphereKey: Sphere.SPIRIT,
                        cardSetKey: CardSet.SHADOWS_OF_MIRKWOOD,
                        cardSubsetKey: CardSubset.SOM2_CONFLICT_AT_THE_CARROCK,
                        cardSetNumber: 25,
                        value: "frodoBagginsCatC",
                    },
                    "frodoBagginsTBR":
                    {
                        name: "Frodo Baggins",
                        threatCost: 0,
                        willpower: 2,
                        attack: 1,
                        defense: 2,
                        hitPoints: 2,
                        traitKeys: [ Trait.HOBBIT, Trait.RING_BEARER ],
                        sphereKey: Sphere.FELLOWSHIP,
                        cardSetKey: CardSet.THE_BLACK_RIDERS,
                        cardSetNumber: 1,
                        value: "frodoBagginsTBR",
                    },
                    "frodoBagginsTLoS":
                    {
                        name: "Frodo Baggins",
                        threatCost: 0,
                        willpower: 2,
                        attack: 1,
                        defense: 2,
                        hitPoints: 2,
                        traitKeys: [ Trait.HOBBIT, Trait.RING_BEARER ],
                        sphereKey: Sphere.FELLOWSHIP,
                        cardSetKey: CardSet.THE_LAND_OF_SHADOW,
                        cardSetNumber: 1,
                        value: "frodoBagginsTLoS",
                    },
                    "frodoBagginsTRD":
                    {
                        name: "Frodo Baggins",
                        threatCost: 0,
                        willpower: 2,
                        attack: 1,
                        defense: 2,
                        hitPoints: 2,
                        traitKeys: [ Trait.HOBBIT, Trait.RING_BEARER ],
                        sphereKey: Sphere.FELLOWSHIP,
                        cardSetKey: CardSet.THE_ROAD_DARKENS,
                        cardSetNumber: 1,
                        value: "frodoBagginsTRD",
                    },
                    "galadriel":
                    {
                        name: "Galadriel",
                        threatCost: 9,
                        willpower: 4,
                        attack: 0,
                        defense: 0,
                        hitPoints: 4,
                        traitKeys: [ Trait.NOLDOR, Trait.NOBLE ],
                        sphereKey: Sphere.SPIRIT,
                        cardSetKey: CardSet.THE_RING_MAKER,
                        cardSubsetKey: CardSubset.TRM5_CELEBRIMBORS_SECRET,
                        cardSetNumber: 112,
                        value: "galadriel",
                    },
                    "galdorOfTheHavens":
                    {
                        name: "Galdor of the Havens",
                        threatCost: 9,
                        willpower: 2,
                        attack: 2,
                        defense: 1,
                        hitPoints: 4,
                        traitKeys: [ Trait.NOLDOR ],
                        sphereKey: Sphere.LORE,
                        cardSetKey: CardSet.THE_GREY_HAVENS,
                        cardSetNumber: 2,
                        value: "galdorOfTheHavens",
                    },
                    "gandalf":
                    {
                        name: "Gandalf",
                        threatCost: 14,
                        willpower: 3,
                        attack: 3,
                        defense: 3,
                        hitPoints: 5,
                        traitKeys: [ Trait.ISTARI ],
                        sphereKey: Sphere.NEUTRAL,
                        cardSetKey: CardSet.THE_ROAD_DARKENS,
                        cardSetNumber: 2,
                        value: "gandalf",
                    },
                    "gimli":
                    {
                        name: "Gimli",
                        threatCost: 11,
                        willpower: 2,
                        attack: 2,
                        defense: 2,
                        hitPoints: 5,
                        traitKeys: [ Trait.DWARF, Trait.NOBLE, Trait.WARRIOR ],
                        sphereKey: Sphere.TACTICS,
                        cardSetKey: CardSet.CORE,
                        cardSetNumber: 4,
                        value: "gimli",
                    },
                    "gloin":
                    {
                        name: "Glóin",
                        threatCost: 9,
                        willpower: 2,
                        attack: 2,
                        defense: 1,
                        hitPoints: 4,
                        traitKeys: [ Trait.DWARF, Trait.NOBLE ],
                        sphereKey: Sphere.LEADERSHIP,
                        cardSetKey: CardSet.CORE,
                        cardSetNumber: 3,
                        value: "gloin",
                    },
                    "glorfindelCore":
                    {
                        name: "Glorfindel",
                        threatCost: 12,
                        willpower: 3,
                        attack: 3,
                        defense: 1,
                        hitPoints: 5,
                        traitKeys: [ Trait.NOBLE, Trait.NOLDOR, Trait.WARRIOR ],
                        sphereKey: Sphere.LORE,
                        cardSetKey: CardSet.CORE,
                        cardSetNumber: 11,
                        value: "glorfindelCore",
                    },
                    "glorfindelFoS":
                    {
                        name: "Glorfindel",
                        threatCost: 5,
                        willpower: 3,
                        attack: 3,
                        defense: 1,
                        hitPoints: 5,
                        traitKeys: [ Trait.NOLDOR, Trait.NOBLE, Trait.WARRIOR ],
                        sphereKey: Sphere.SPIRIT,
                        cardSetKey: CardSet.DWARROWDELF,
                        cardSubsetKey: CardSubset.D5_FOUNDATIONS_OF_STONE,
                        cardSetNumber: 101,
                        value: "glorfindelFoS",
                    },
                    "grima":
                    {
                        name: "Gríma",
                        threatCost: 9,
                        willpower: 2,
                        attack: 1,
                        defense: 2,
                        hitPoints: 3,
                        traitKeys: [ Trait.ROHAN, Trait.ISENGARD ],
                        sphereKey: Sphere.LORE,
                        cardSetKey: CardSet.THE_VOICE_OF_ISENGARD,
                        cardSetNumber: 2,
                        value: "grima",
                    },
                    "halbarad":
                    {
                        name: "Halbarad",
                        threatCost: 10,
                        willpower: 2,
                        attack: 2,
                        defense: 2,
                        hitPoints: 4,
                        traitKeys: [ Trait.DUNEDAIN, Trait.RANGER ],
                        sphereKey: Sphere.LEADERSHIP,
                        cardSetKey: CardSet.THE_LOST_REALM,
                        cardSetNumber: 2,
                        value: "halbarad",
                    },
                    "haldirOfLorien":
                    {
                        name: "Haldir of Lórien",
                        threatCost: 9,
                        willpower: 2,
                        attack: 3,
                        defense: 1,
                        hitPoints: 3,
                        traitKeys: [ Trait.SILVAN, Trait.RANGER, Trait.SCOUT ],
                        sphereKey: Sphere.LORE,
                        cardSetKey: CardSet.THE_RING_MAKER,
                        cardSubsetKey: CardSubset.TRM3_TROUBLE_IN_THARBAD,
                        cardSetNumber: 56,
                        value: "haldirOfLorien",
                    },
                    "hama":
                    {
                        name: "Háma",
                        threatCost: 9,
                        willpower: 1,
                        attack: 3,
                        defense: 1,
                        hitPoints: 4,
                        traitKeys: [ Trait.ROHAN, Trait.WARRIOR ],
                        sphereKey: Sphere.TACTICS,
                        cardSetKey: CardSet.SHADOWS_OF_MIRKWOOD,
                        cardSubsetKey: CardSubset.D4_THE_LONG_DARK,
                        cardSetNumber: 76,
                        value: "hama",
                    },
                    "hirluinTheFair":
                    {
                        name: "Hirluin the Fair",
                        threatCost: 8,
                        willpower: 1,
                        attack: 1,
                        defense: 1,
                        hitPoints: 4,
                        traitKeys: [ Trait.OUTLANDS ],
                        sphereKey: Sphere.LEADERSHIP,
                        cardSetKey: CardSet.AGAINST_THE_SHADOW,
                        cardSubsetKey: CardSubset.ATS1_THE_STEWARDS_FEAR,
                        cardSetNumber: 1,
                        value: "hirluinTheFair",
                    },
                    "idraen":
                    {
                        name: "Idraen",
                        threatCost: 11,
                        willpower: 2,
                        attack: 3,
                        defense: 2,
                        hitPoints: 4,
                        traitKeys: [ Trait.DUNEDAIN, Trait.RANGER, Trait.SCOUT ],
                        sphereKey: Sphere.SPIRIT,
                        cardSetKey: CardSet.THE_RING_MAKER,
                        cardSubsetKey: CardSubset.TRM2_THE_THREE_TRIALS,
                        cardSetNumber: 25,
                        value: "idraen",
                    },
                    "legolas":
                    {
                        name: "Legolas",
                        threatCost: 9,
                        willpower: 1,
                        attack: 3,
                        defense: 1,
                        hitPoints: 4,
                        traitKeys: [ Trait.NOBLE, Trait.SILVAN, Trait.WARRIOR ],
                        sphereKey: Sphere.TACTICS,
                        cardSetKey: CardSet.CORE,
                        cardSetNumber: 5,
                        value: "legolas",
                    },
                    "mablung":
                    {
                        name: "Mablung",
                        threatCost: 10,
                        willpower: 2,
                        attack: 2,
                        defense: 2,
                        hitPoints: 4,
                        traitKeys: [ Trait.GONDOR, Trait.RANGER ],
                        sphereKey: Sphere.TACTICS,
                        cardSetKey: CardSet.THE_RING_MAKER,
                        cardSubsetKey: CardSubset.TRM4_THE_NIN_IN_EILPH,
                        cardSetNumber: 84,
                        value: "mablung",
                    },
                    "merryTWoE":
                    {
                        name: "Merry",
                        threatCost: 6,
                        willpower: 2,
                        attack: 1,
                        defense: 1,
                        hitPoints: 2,
                        traitKeys: [ Trait.HOBBIT ],
                        sphereKey: Sphere.SPIRIT,
                        cardSetKey: CardSet.ANGMAR_AWAKENED,
                        cardSubsetKey: CardSubset.AA1_THE_WASTES_OF_ERIADOR,
                        cardSetNumber: 1,
                        value: "merryTWoE",
                    },
                    "merryTBR":
                    {
                        name: "Merry",
                        threatCost: 6,
                        willpower: 2,
                        attack: 0,
                        defense: 1,
                        hitPoints: 2,
                        traitKeys: [ Trait.HOBBIT ],
                        sphereKey: Sphere.TACTICS,
                        cardSetKey: CardSet.THE_BLACK_RIDERS,
                        cardSetNumber: 3,
                        value: "merryTBR",
                    },
                    "mirlonde":
                    {
                        name: "Mirlonde",
                        threatCost: 8,
                        willpower: 2,
                        attack: 2,
                        defense: 1,
                        hitPoints: 3,
                        traitKeys: [ Trait.SILVAN ],
                        sphereKey: Sphere.LORE,
                        cardSetKey: CardSet.AGAINST_THE_SHADOW,
                        cardSubsetKey: CardSubset.ATS2_THE_DRUADAN_FOREST,
                        cardSetNumber: 32,
                        value: "mirlonde",
                    },
                    "nori":
                    {
                        name: "Nori",
                        threatCost: 9,
                        willpower: 2,
                        attack: 1,
                        defense: 2,
                        hitPoints: 4,
                        traitKeys: [ Trait.DWARF ],
                        sphereKey: Sphere.SPIRIT,
                        cardSetKey: CardSet.OVER_HILL_AND_UNDER_HILL,
                        cardSetNumber: 3,
                        value: "nori",
                    },
                    "oin":
                    {
                        name: "Óin",
                        threatCost: 8,
                        willpower: 2,
                        attack: 1,
                        defense: 1,
                        hitPoints: 4,
                        traitKeys: [ Trait.DWARF ],
                        sphereKey: Sphere.SPIRIT,
                        cardSetKey: CardSet.ON_THE_DOORSTEP,
                        cardSetNumber: 4,
                        value: "oin",
                    },
                    "ori":
                    {
                        name: "Ori",
                        threatCost: 8,
                        willpower: 2,
                        attack: 2,
                        defense: 1,
                        hitPoints: 3,
                        traitKeys: [ Trait.DWARF ],
                        sphereKey: Sphere.LORE,
                        cardSetKey: CardSet.OVER_HILL_AND_UNDER_HILL,
                        cardSetNumber: 4,
                        value: "ori",
                    },
                    "pippinEaAD":
                    {
                        name: "Pippin",
                        threatCost: 6,
                        willpower: 2,
                        attack: 1,
                        defense: 1,
                        hitPoints: 2,
                        traitKeys: [ Trait.HOBBIT ],
                        sphereKey: Sphere.SPIRIT,
                        cardSetKey: CardSet.AGAINST_THE_SHADOW,
                        cardSubsetKey: CardSubset.ATS3_ENCOUNTER_AT_AMON_DIN,
                        cardSetNumber: 56,
                        value: "pippinEaAD",
                    },
                    "pippinTBR":
                    {
                        name: "Pippin",
                        threatCost: 6,
                        willpower: 2,
                        attack: 1,
                        defense: 1,
                        hitPoints: 2,
                        traitKeys: [ Trait.HOBBIT ],
                        sphereKey: Sphere.LORE,
                        cardSetKey: CardSet.THE_BLACK_RIDERS,
                        cardSetNumber: 4,
                        value: "pippinTBR",
                    },
                    "princeImrahil":
                    {
                        name: "Prince Imrahil",
                        threatCost: 11,
                        willpower: 2,
                        attack: 3,
                        defense: 2,
                        hitPoints: 4,
                        traitKeys: [ Trait.GONDOR, Trait.NOBLE ],
                        sphereKey: Sphere.LEADERSHIP,
                        cardSetKey: CardSet.SHADOWS_OF_MIRKWOOD,
                        cardSubsetKey: CardSubset.SOM3_A_JOURNEY_TO_RHOSGOBEL,
                        cardSetNumber: 50,
                        value: "princeImrahil",
                    },
                    "rossiel":
                    {
                        name: "Rossiel",
                        threatCost: 8,
                        willpower: 2,
                        attack: 1,
                        defense: 2,
                        hitPoints: 3,
                        traitKeys: [ Trait.SILVAN ],
                        sphereKey: Sphere.LORE,
                        cardSetKey: CardSet.ANGMAR_AWAKENED,
                        cardSubsetKey: CardSubset.AA2_ESCAPE_FROM_MOUNT_GRAM,
                        cardSetNumber: 28,
                        value: "rossiel",
                    },
                    "samGamgee":
                    {
                        name: "Sam Gamgee",
                        threatCost: 8,
                        willpower: 3,
                        attack: 1,
                        defense: 1,
                        hitPoints: 3,
                        traitKeys: [ Trait.HOBBIT ],
                        sphereKey: Sphere.LEADERSHIP,
                        cardSetKey: CardSet.THE_BLACK_RIDERS,
                        cardSetNumber: 2,
                        value: "samGamgee",
                    },
                    "thalin":
                    {
                        name: "Thalin",
                        threatCost: 9,
                        willpower: 1,
                        attack: 2,
                        defense: 2,
                        hitPoints: 4,
                        traitKeys: [ Trait.DWARF, Trait.WARRIOR ],
                        sphereKey: Sphere.TACTICS,
                        cardSetKey: CardSet.CORE,
                        cardSetNumber: 6,
                        value: "thalin",
                    },
                    "theodenTMV":
                    {
                        name: "Théoden",
                        threatCost: 12,
                        willpower: 2,
                        attack: 3,
                        defense: 2,
                        hitPoints: 4,
                        traitKeys: [ Trait.ROHAN, Trait.NOBLE, Trait.WARRIOR ],
                        sphereKey: Sphere.TACTICS,
                        cardSetKey: CardSet.AGAINST_THE_SHADOW,
                        cardSubsetKey: CardSubset.ATS6_THE_MORGUL_VALE,
                        cardSetNumber: 134,
                        value: "theodenTMV",
                    },
                    "theodenTToS":
                    {
                        name: "Théoden",
                        threatCost: 12,
                        willpower: 2,
                        attack: 3,
                        defense: 2,
                        hitPoints: 4,
                        traitKeys: [ Trait.ROHAN, Trait.NOBLE, Trait.WARRIOR ],
                        sphereKey: Sphere.SPIRIT,
                        cardSetKey: CardSet.THE_TREASON_OF_SARUMAN,
                        cardSetNumber: 2,
                        value: "theodenTToS",
                    },
                    "theodred":
                    {
                        name: "Théodred",
                        threatCost: 8,
                        willpower: 1,
                        attack: 2,
                        defense: 1,
                        hitPoints: 4,
                        traitKeys: [ Trait.NOBLE, Trait.ROHAN, Trait.WARRIOR ],
                        sphereKey: Sphere.LEADERSHIP,
                        cardSetKey: CardSet.CORE,
                        cardSetNumber: 2,
                        value: "theodred",
                    },
                    "thorinOakenshield":
                    {
                        name: "Thorin Oakenshield",
                        threatCost: 12,
                        willpower: 3,
                        attack: 3,
                        defense: 1,
                        hitPoints: 5,
                        traitKeys: [ Trait.DWARF, Trait.NOBLE, Trait.WARRIOR ],
                        sphereKey: Sphere.LEADERSHIP,
                        cardSetKey: CardSet.OVER_HILL_AND_UNDER_HILL,
                        cardSetNumber: 2,
                        value: "thorinOakenshield",
                    },
                    "treebeard":
                    {
                        name: "Treebeard",
                        threatCost: 13,
                        willpower: 2,
                        attack: 3,
                        defense: 3,
                        hitPoints: 5,
                        traitKeys: [ Trait.ENT ],
                        sphereKey: Sphere.LORE,
                        cardSetKey: CardSet.THE_TREASON_OF_SARUMAN,
                        cardSetNumber: 3,
                        value: "treebeard",
                    },
                },

                values: function()
                {
                    return Object.getOwnPropertyNames(HeroCard.properties);
                },
            };

            HeroCard.values().forEach(function(cardKey)
            {
                var card = HeroCard.properties[cardKey];
                card.isUnique = true;
                card.cardSet = CardSet.properties[card.cardSetKey];
                if (card.cardSubsetKey)
                {
                    card.cardSubset = CardSubset.properties[card.cardSubsetKey];
                }
                card.cardTypeKey = CardType.HERO;
                card.cardType = CardType.properties[card.cardTypeKey];
                card.sphere = Sphere.properties[card.sphereKey];

                if (!card.image)
                {
                    card.image = ImageNameCreator.create(card);
                }
            });

            if (Object.freeze)
            {
                Object.freeze(HeroCard);
            }

            return HeroCard;
        });
