define([ "CardSet", "CardSubset", "CardType", "ImageNameCreator", "Sphere", "Trait" ], function(CardSet, CardSubset,
        CardType, ImageNameCreator, Sphere, Trait)
{
    "use strict";
    var HeroCard =
    {
        ARAGORN_CORE: "aragornCore",
        ARAGORN_TTOS: "aragornTToS",
        BALIN: "balin",
        BARD_THE_BOWMAN: "bardTheBowman",
        BEORN: "beorn",
        BERAVOR: "beravor",
        BEREGOND: "beregond",
        BIFUR: "bifur",
        BILBO_BAGGINS_OHAUH: "bilboBagginsOHaUH",
        BILBO_BAGGINS_OTD: "bilboBagginsOtD",
        BILBO_BAGGINS_THFG: "bilboBagginsTHfG",
        BOMBUR: "bombur",
        BOROMIR_HON: "boromirHoN",
        BOROMIR_SOM: "boromirSoM",
        BRAND_SON_OF_BAIN: "brandSonOfBain",
        CALDARA: "caldara",
        CIRDAN_THE_SHIPWRIGHT: "cirdanTheShipwright",
        DAIN_IRONFOOT: "dainIronfoot",
        DENETHOR: "denethor",
        DWALIN: "dwalin",
        DUNHERE: "dunhere",
        ELEANOR: "eleanor",
        ELROHIR: "elrohir",
        ELROND: "elrond",
        EOWYN: "eowyn",
        FRODO_BAGGINS: "frodoBaggins",
        GALDOR_OF_THE_HAVENS: "galdorOfTheHavens",
        GIMLI: "gimli",
        GLOIN: "gloin",
        GLORFINDEL_CORE: "glorfindelCore",
        GLORFINEL_FOS: "glorfindelFoS",
        HAMA: "hama",
        LEGOLAS: "legolas",
        NORI: "nori",
        OIN: "oin",
        ORI: "ori",
        PRINCE_IMRAHIL: "princeImrahil",
        THALIN: "thalin",
        THEODEN: "theoden",
        THEODRED: "theodred",
        THORIN_OAKENSHIELD: "thorinOakenshield",
        TREEBEARD: "treebeard",

        properties:
        {
            "aragornCore":
            {
                name: "Aragorn",
                threatCost: 12,
                willpower: 2,
                attack: 3,
                defense: 2,
                hitPoints: 5,
                traitKeys: [ Trait.DUNEDAIN, Trait.NOBLE, Trait.RANGER ],
                sphereKey: Sphere.LEADERSHIP,
                cardSetKey: CardSet.CORE,
                cardSetNumber: 1,
                value: "aragornCore",
            },
            "aragornTToS":
            {
                name: "Aragorn",
                threatCost: 0,
                willpower: 2,
                attack: 3,
                defense: 2,
                hitPoints: 5,
                traitKeys: [ Trait.DUNEDAIN, Trait.NOBLE, Trait.RANGER ],
                sphereKey: Sphere.FELLOWSHIP,
                cardSetKey: CardSet.THE_TREASON_OF_SARUMAN,
                cardSetNumber: 1,
                value: "aragornTToS",
            },
            "balin":
            {
                name: "Balin",
                threatCost: 9,
                willpower: 2,
                attack: 1,
                defense: 2,
                hitPoints: 4,
                traitKeys: [ Trait.DWARF ],
                sphereKey: Sphere.LEADERSHIP,
                cardSetKey: CardSet.ON_THE_DOORSTEP,
                cardSetNumber: 2,
                value: "balin",
            },
            "bardTheBowman":
            {
                name: "Bard the Bowman",
                threatCost: 11,
                willpower: 2,
                attack: 3,
                defense: 2,
                hitPoints: 4,
                traitKeys: [ Trait.ESGAROTH, Trait.WARRIOR ],
                sphereKey: Sphere.TACTICS,
                cardSetKey: CardSet.ON_THE_DOORSTEP,
                cardSetNumber: 3,
                value: "bardTheBowman",
            },
            "beorn":
            {
                name: "Beorn",
                threatCost: 12,
                willpower: 0,
                attack: 5,
                defense: 1,
                hitPoints: 10,
                traitKeys: [ Trait.BEORNING, Trait.WARRIOR ],
                sphereKey: Sphere.TACTICS,
                cardSetKey: CardSet.OVER_HILL_AND_UNDER_HILL,
                cardSetNumber: 5,
                value: "beorn",
            },
            "beravor":
            {
                name: "Beravor",
                threatCost: 10,
                willpower: 2,
                attack: 2,
                defense: 2,
                hitPoints: 4,
                traitKeys: [ Trait.DUNEDAIN, Trait.RANGER ],
                sphereKey: Sphere.LORE,
                cardSetKey: CardSet.CORE,
                cardSetNumber: 12,
                value: "beravor",
            },
            "beregond":
            {
                name: "Beregond",
                threatCost: 10,
                willpower: 0,
                attack: 1,
                defense: 4,
                hitPoints: 4,
                traitKeys: [ Trait.GONDOR, Trait.WARRIOR ],
                sphereKey: Sphere.TACTICS,
                cardSetKey: CardSet.HEIRS_OF_NUMENOR,
                cardSetNumber: 1,
                value: "beregond",
            },
            "bifur":
            {
                name: "Bifur",
                threatCost: 7,
                willpower: 2,
                attack: 1,
                defense: 2,
                hitPoints: 3,
                traitKeys: [ Trait.DWARF ],
                sphereKey: Sphere.LORE,
                cardSetKey: CardSet.KHAZAD_DUM,
                cardSetNumber: 2,
                value: "bifur",
            },
            "bilboBagginsOHaUH":
            {
                name: "Bilbo Baggins",
                threatCost: 0,
                willpower: 1,
                attack: 1,
                defense: 1,
                hitPoints: 3,
                traitKeys: [ Trait.HOBBIT ],
                sphereKey: Sphere.BAGGINS,
                cardSetKey: CardSet.OVER_HILL_AND_UNDER_HILL,
                cardSetNumber: 1,
                value: "bilboBagginsOHaUH",
            },
            "bilboBagginsOtD":
            {
                name: "Bilbo Baggins",
                threatCost: 0,
                willpower: 1,
                attack: 1,
                defense: 1,
                hitPoints: 3,
                traitKeys: [ Trait.HOBBIT, Trait.BURGLAR ],
                sphereKey: Sphere.BAGGINS,
                cardSetKey: CardSet.ON_THE_DOORSTEP,
                cardSetNumber: 1,
                value: "bilboBagginsOtD",
            },
            "bilboBagginsTHfG":
            {
                name: "Bilbo Baggins",
                threatCost: 9,
                willpower: 1,
                attack: 1,
                defense: 2,
                hitPoints: 2,
                traitKeys: [ Trait.HOBBIT ],
                sphereKey: Sphere.LORE,
                cardSetKey: CardSet.SHADOWS_OF_MIRKWOOD,
                cardSubsetKey: CardSubset.SOM1_THE_HUNT_FOR_GOLLUM,
                cardSetNumber: 1,
                value: "bilboBagginsTHfG",
            },
            "bombur":
            {
                name: "Bombur",
                threatCost: 8,
                willpower: 0,
                attack: 1,
                defense: 2,
                hitPoints: 5,
                traitKeys: [ Trait.DWARF ],
                sphereKey: Sphere.LORE,
                cardSetKey: CardSet.ON_THE_DOORSTEP,
                cardSetNumber: 5,
                value: "bombur",
            },
            "boromirHoN":
            {
                name: "Boromir",
                threatCost: 11,
                willpower: 1,
                attack: 3,
                defense: 2,
                hitPoints: 5,
                traitKeys: [ Trait.GONDOR, Trait.WARRIOR, Trait.NOBLE ],
                sphereKey: Sphere.LEADERSHIP,
                cardSetKey: CardSet.HEIRS_OF_NUMENOR,
                cardSetNumber: 2,
                value: "boromirHoN",
            },
            "boromirSoM":
            {
                name: "Boromir",
                threatCost: 11,
                willpower: 1,
                attack: 3,
                defense: 2,
                hitPoints: 5,
                traitKeys: [ Trait.GONDOR, Trait.NOBLE, Trait.WARRIOR ],
                sphereKey: Sphere.TACTICS,
                cardSetKey: CardSet.SHADOWS_OF_MIRKWOOD,
                cardSubsetKey: CardSubset.SOM5_THE_DEAD_MARSHES,
                cardSetNumber: 95,
                value: "boromirSoM",
            },
            "brandSonOfBain":
            {
                name: "Brand Son of Bain",
                threatCost: 10,
                willpower: 2,
                attack: 3,
                defense: 2,
                hitPoints: 3,
                traitKeys: [ Trait.DALE ],
                sphereKey: Sphere.LORE,
                cardSetKey: CardSet.SHADOWS_OF_MIRKWOOD,
                cardSubsetKey: CardSubset.SOM4_THE_HILLS_OF_EMYN_MUIL,
                cardSetNumber: 72,
                value: "brandSonOfBain",
            },
            "caldara":
            {
                name: "Caldara",
                threatCost: 8,
                willpower: 2,
                attack: 1,
                defense: 2,
                hitPoints: 3,
                traitKeys: [ Trait.GONDOR ],
                sphereKey: Sphere.SPIRIT,
                cardSetKey: CardSet.AGAINST_THE_SHADOW,
                cardSubsetKey: CardSubset.ATS5_THE_BLOOD_OF_GONDOR,
                cardSetNumber: 107,
                value: "caldara",
            },
            "cirdanTheShipwright":
            {
                name: "Círdan the Shipwright",
                threatCost: 12,
                willpower: 4,
                attack: 2,
                defense: 2,
                hitPoints: 4,
                traitKeys: [ Trait.NOLDOR, Trait.NOBLE ],
                sphereKey: Sphere.SPIRIT,
                cardSetKey: CardSet.THE_GREY_HAVENS,
                cardSetNumber: 1,
                value: "cirdanTheShipwright",
            },
            "dainIronfoot":
            {
                name: "Dain Ironfoot",
                threatCost: 11,
                willpower: 1,
                attack: 2,
                defense: 3,
                hitPoints: 5,
                traitKeys: [ Trait.DWARF ],
                sphereKey: Sphere.LEADERSHIP,
                cardSetKey: CardSet.SHADOWS_OF_MIRKWOOD,
                cardSubsetKey: CardSubset.SOM6_RETURN_TO_MIRKWOOD,
                cardSetNumber: 116,
                value: "dainIronfoot",
            },
            "denethor":
            {
                name: "Denethor",
                threatCost: 8,
                willpower: 1,
                attack: 1,
                defense: 3,
                hitPoints: 3,
                traitKeys: [ Trait.GONDOR, Trait.NOBLE, Trait.STEWARD ],
                sphereKey: Sphere.LORE,
                cardSetKey: CardSet.CORE,
                cardSetNumber: 10,
                value: "denethor",
            },
            "dwalin":
            {
                name: "Dwalin",
                threatCost: 9,
                willpower: 1,
                attack: 2,
                defense: 2,
                hitPoints: 4,
                traitKeys: [ Trait.DWARF ],
                sphereKey: Sphere.SPIRIT,
                cardSetKey: CardSet.KHAZAD_DUM,
                cardSetNumber: 1,
                value: "dwalin",
            },
            "dunhere":
            {
                name: "Dúnhere",
                threatCost: 8,
                willpower: 1,
                attack: 2,
                defense: 1,
                hitPoints: 4,
                traitKeys: [ Trait.ROHAN, Trait.WARRIOR ],
                sphereKey: Sphere.SPIRIT,
                cardSetKey: CardSet.CORE,
                cardSetNumber: 9,
                value: "dunhere",
            },
            "eleanor":
            {
                name: "Eleanor",
                threatCost: 7,
                willpower: 1,
                attack: 1,
                defense: 2,
                hitPoints: 3,
                traitKeys: [ Trait.GONDOR, Trait.NOBLE ],
                sphereKey: Sphere.SPIRIT,
                cardSetKey: CardSet.CORE,
                cardSetNumber: 8,
                value: "eleanor",
            },
            "elrohir":
            {
                name: "Elrohir",
                threatCost: 10,
                willpower: 2,
                attack: 2,
                defense: 1,
                hitPoints: 4,
                traitKeys: [ Trait.NOLDOR, Trait.NOBLE, Trait.RANGER ],
                sphereKey: Sphere.LEADERSHIP,
                cardSetKey: CardSet.DWARROWDELF,
                cardSubsetKey: CardSubset.D1_THE_REDHORN_GATE,
                cardSetNumber: 1,
                value: "elrohir",
            },
            "elrond":
            {
                name: "Elrond",
                threatCost: 13,
                willpower: 3,
                attack: 2,
                defense: 3,
                hitPoints: 4,
                traitKeys: [ Trait.NOLDOR, Trait.NOBLE ],
                sphereKey: Sphere.LORE,
                cardSetKey: CardSet.SHADOWS_OF_MIRKWOOD,
                cardSubsetKey: CardSubset.D6_SHADOW_AND_FLAME,
                cardSetNumber: 128,
                value: "elrond",
            },
            "eowyn":
            {
                name: "Éowyn",
                threatCost: 9,
                willpower: 4,
                attack: 1,
                defense: 1,
                hitPoints: 3,
                traitKeys: [ Trait.NOBLE, Trait.ROHAN ],
                sphereKey: Sphere.SPIRIT,
                cardSetKey: CardSet.CORE,
                cardSetNumber: 7,
                value: "eowyn",
            },
            "frodoBaggins":
            {
                name: "Frodo Baggins",
                threatCost: 7,
                willpower: 2,
                attack: 1,
                defense: 2,
                hitPoints: 2,
                traitKeys: [ Trait.HOBBIT ],
                sphereKey: Sphere.SPIRIT,
                cardSetKey: CardSet.SHADOWS_OF_MIRKWOOD,
                cardSubsetKey: CardSubset.SOM2_CONFLICT_AT_THE_CARROCK,
                cardSetNumber: 25,
                value: "frodoBaggins",
            },
            "galdorOfTheHavens":
            {
                name: "Galdor of the Havens",
                threatCost: 9,
                willpower: 2,
                attack: 2,
                defense: 1,
                hitPoints: 4,
                traitKeys: [ Trait.NOLDOR ],
                sphereKey: Sphere.LORE,
                cardSetKey: CardSet.THE_GREY_HAVENS,
                cardSetNumber: 2,
                value: "galdorOfTheHavens",
            },
            "gimli":
            {
                name: "Gimli",
                threatCost: 11,
                willpower: 2,
                attack: 2,
                defense: 2,
                hitPoints: 5,
                traitKeys: [ Trait.DWARF, Trait.NOBLE, Trait.WARRIOR ],
                sphereKey: Sphere.TACTICS,
                cardSetKey: CardSet.CORE,
                cardSetNumber: 4,
                value: "gimli",
            },
            "gloin":
            {
                name: "Glóin",
                threatCost: 9,
                willpower: 2,
                attack: 2,
                defense: 1,
                hitPoints: 4,
                traitKeys: [ Trait.DWARF, Trait.NOBLE ],
                sphereKey: Sphere.LEADERSHIP,
                cardSetKey: CardSet.CORE,
                cardSetNumber: 3,
                value: "gloin",
            },
            "glorfindelCore":
            {
                name: "Glorfindel",
                threatCost: 12,
                willpower: 3,
                attack: 3,
                defense: 1,
                hitPoints: 5,
                traitKeys: [ Trait.NOBLE, Trait.NOLDOR, Trait.WARRIOR ],
                sphereKey: Sphere.LORE,
                cardSetKey: CardSet.CORE,
                cardSetNumber: 11,
                value: "glorfindelCore",
            },
            "glorfindelFoS":
            {
                name: "Glorfindel",
                threatCost: 5,
                willpower: 3,
                attack: 3,
                defense: 1,
                hitPoints: 5,
                traitKeys: [ Trait.NOLDOR, Trait.NOBLE, Trait.WARRIOR ],
                sphereKey: Sphere.SPIRIT,
                cardSetKey: CardSet.DWARROWDELF,
                cardSubsetKey: CardSubset.D5_FOUNDATIONS_OF_STONE,
                cardSetNumber: 101,
                value: "glorfindelFoS",
            },
            "hama":
            {
                name: "Háma",
                threatCost: 9,
                willpower: 1,
                attack: 3,
                defense: 1,
                hitPoints: 4,
                traitKeys: [ Trait.ROHAN, Trait.WARRIOR ],
                sphereKey: Sphere.TACTICS,
                cardSetKey: CardSet.SHADOWS_OF_MIRKWOOD,
                cardSubsetKey: CardSubset.D4_THE_LONG_DARK,
                cardSetNumber: 76,
                value: "hama",
            },
            "legolas":
            {
                name: "Legolas",
                threatCost: 9,
                willpower: 1,
                attack: 3,
                defense: 1,
                hitPoints: 4,
                traitKeys: [ Trait.NOBLE, Trait.SILVAN, Trait.WARRIOR ],
                sphereKey: Sphere.TACTICS,
                cardSetKey: CardSet.CORE,
                cardSetNumber: 5,
                value: "legolas",
            },
            "nori":
            {
                name: "Nori",
                threatCost: 9,
                willpower: 2,
                attack: 1,
                defense: 2,
                hitPoints: 4,
                traitKeys: [ Trait.DWARF ],
                sphereKey: Sphere.SPIRIT,
                cardSetKey: CardSet.OVER_HILL_AND_UNDER_HILL,
                cardSetNumber: 3,
                value: "nori",
            },
            "oin":
            {
                name: "Óin",
                threatCost: 8,
                willpower: 2,
                attack: 1,
                defense: 1,
                hitPoints: 4,
                traitKeys: [ Trait.DWARF ],
                sphereKey: Sphere.SPIRIT,
                cardSetKey: CardSet.ON_THE_DOORSTEP,
                cardSetNumber: 4,
                value: "oin",
            },
            "ori":
            {
                name: "Ori",
                threatCost: 8,
                willpower: 2,
                attack: 2,
                defense: 1,
                hitPoints: 3,
                traitKeys: [ Trait.DWARF ],
                sphereKey: Sphere.LORE,
                cardSetKey: CardSet.OVER_HILL_AND_UNDER_HILL,
                cardSetNumber: 4,
                value: "ori",
            },
            "princeImrahil":
            {
                name: "Prince Imrahil",
                threatCost: 11,
                willpower: 2,
                attack: 3,
                defense: 2,
                hitPoints: 4,
                traitKeys: [ Trait.GONDOR, Trait.NOBLE ],
                sphereKey: Sphere.LEADERSHIP,
                cardSetKey: CardSet.SHADOWS_OF_MIRKWOOD,
                cardSubsetKey: CardSubset.SOM3_A_JOURNEY_TO_RHOSGOBEL,
                cardSetNumber: 50,
                value: "princeImrahil",
            },
            "thalin":
            {
                name: "Thalin",
                threatCost: 9,
                willpower: 1,
                attack: 2,
                defense: 2,
                hitPoints: 4,
                traitKeys: [ Trait.DWARF, Trait.WARRIOR ],
                sphereKey: Sphere.TACTICS,
                cardSetKey: CardSet.CORE,
                cardSetNumber: 6,
                value: "thalin",
            },
            "theoden":
            {
                name: "Théoden",
                threatCost: 12,
                willpower: 2,
                attack: 3,
                defense: 2,
                hitPoints: 4,
                traitKeys: [ Trait.ROHAN, Trait.NOBLE, Trait.WARRIOR ],
                sphereKey: Sphere.SPIRIT,
                cardSetKey: CardSet.THE_TREASON_OF_SARUMAN,
                cardSetNumber: 2,
                value: "theoden",
            },
            "theodred":
            {
                name: "Théodred",
                threatCost: 8,
                willpower: 1,
                attack: 2,
                defense: 1,
                hitPoints: 4,
                traitKeys: [ Trait.NOBLE, Trait.ROHAN, Trait.WARRIOR ],
                sphereKey: Sphere.LEADERSHIP,
                cardSetKey: CardSet.CORE,
                cardSetNumber: 2,
                value: "theodred",
            },
            "thorinOakenshield":
            {
                name: "Thorin Oakenshield",
                threatCost: 12,
                willpower: 3,
                attack: 3,
                defense: 1,
                hitPoints: 5,
                traitKeys: [ Trait.DWARF, Trait.NOBLE, Trait.WARRIOR ],
                sphereKey: Sphere.LEADERSHIP,
                cardSetKey: CardSet.OVER_HILL_AND_UNDER_HILL,
                cardSetNumber: 2,
                value: "thorinOakenshield",
            },
            "treebeard":
            {
                name: "Treebeard",
                threatCost: 13,
                willpower: 2,
                attack: 3,
                defense: 3,
                hitPoints: 5,
                traitKeys: [ Trait.ENT ],
                sphereKey: Sphere.LORE,
                cardSetKey: CardSet.THE_TREASON_OF_SARUMAN,
                cardSetNumber: 3,
                value: "treebeard",
            },
        },

        values: function()
        {
            return Object.getOwnPropertyNames(HeroCard.properties);
        },
    };

    HeroCard.values().forEach(function(cardKey)
    {
        var card = HeroCard.properties[cardKey];
        card.isUnique = true;
        card.cardSet = CardSet.properties[card.cardSetKey];
        if (card.cardSubsetKey)
        {
            card.cardSubset = CardSubset.properties[card.cardSubsetKey];
        }
        card.cardTypeKey = CardType.HERO;
        card.cardType = CardType.properties[card.cardTypeKey];
        card.sphere = Sphere.properties[card.sphereKey];

        if (!card.image)
        {
            card.image = ImageNameCreator.create(card);
        }
    });

    if (Object.freeze)
    {
        Object.freeze(HeroCard);
    }

    return HeroCard;
});
