define(["Assessment", "SciFiAward", "Book", "Nomination", "UserSettings"],
   function(Assessment, Award, Book, Nomination, UserSettings)
   {
      "use strict";

      function SciFiInitialState()
      {
         this.winnerImage = "../resources/Rocketship14.png";
         this.books = [];
         this.bookToDclUrl = {};
         this.bookToNomination = {};
         this.bookToAssessment = {};

         var britishFantasy = Award.properties.britishFantasy;
         var britishSf = Award.properties.britishSf;
         var hugo = Award.properties.hugo;
         var locus = Award.properties.locus;
         var nebula = Award.properties.nebula;

         this.books.push(new Book("(tie): Artemis Awakening", "Jane Lindskold"));
         this.books.push(new Book("(tie): The Book of Strange New Things", "Michel Faber"));
         this.books.push(new Book("The Aeronaut's Windlass", "Jim Butcher"));
         this.books.push(new Book("Afterparty", "Daryl Gregory"));
         this.books.push(new Book("All Those Vanished Engines", "Paul Park"));
         this.books.push(new Book("All the Birds in the Sky", "Charlie Jane Anders"));
         this.books.push(new Book("Ancillary Mercy", "Ann Leckie"));
         this.books.push(new Book("Ancillary Sword", "Ann Leckie"));
         this.books.push(new Book("The Angel of Losses", "Stephanie Feldman"));
         this.books.push(new Book("Annihilation", "Jeff VanderMeer"));
         this.books.push(new Book("Annihilation/Authority/Acceptance", "Jeff VanderMeer"));
         this.books.push(new Book("Aurora", "Kim Stanley Robinson"));
         this.books.push(new Book("Azanian Bridges", "Nick Wood"));
         this.books.push(new Book("Barsk: The Elephants' Graveyard", "Lawrence M. Schoen"));
         this.books.push(new Book("Bathing the Lion", "Jonathan Carroll"));
         this.books.push(new Book("Beautiful Blood", "Lucius Shepard"));
         this.books.push(new Book("The Bees", "Laline Paull"));
         this.books.push(new Book("The Blood of Angels", "Johanna Sinisalo"));
         this.books.push(new Book("The Bone Clocks", "David Mitchell"));
         this.books.push(new Book("Borderline", "Mishell Baker"));
         this.books.push(new Book("A Borrowed Man", "Gene Wolfe"));
         this.books.push(new Book("The Boy Who Drew Monsters", "Keith Donohue"));
         this.books.push(new Book("Breed", "K. T. Davies"));
         this.books.push(new Book("Bête", "Adam Roberts"));
         this.books.push(new Book("California Bones", "Greg van Eekhout"));
         this.books.push(new Book("The Causal Angel", "Hannu Rajaniemi"));
         this.books.push(new Book("Cibola Burn", "James S. A. Corey"));
         this.books.push(new Book("City of Stairs", "Robert Jackson Bennett"));
         this.books.push(new Book("The Clockwork Dagger", "Beth Cato"));
         this.books.push(new Book("A Closed and Common Orbit", "Becky Chambers"));
         this.books.push(new Book("A Cold Silence", "Alison Littlewood"));
         this.books.push(new Book("Coming Home", "Jack McDevitt"));
         this.books.push(new Book("Cuckoo Song", "Frances Hardinge"));
         this.books.push(new Book("The Dark Between the Stars", "Kevin J. Anderson"));
         this.books.push(new Book("The Dark Defiles", "Richard K. Morgan"));
         this.books.push(new Book("Dark Lightning", "John Varley"));
         this.books.push(new Book("A Darkling Sea", "James L. Cambias"));
         this.books.push(new Book("Daughter of Eden", "Chris Beckett"));
         this.books.push(new Book("The Death House", "Sarah Pinborough"));
         this.books.push(new Book("Death's End", "Cixin Liu, translated by Ken Liu"));
         this.books.push(new Book("Echopraxia", "Peter Watts"));
         this.books.push(new Book("Elysium", "Jennifer Marie Brissett"));
         this.books.push(new Book("The Emperor's Blades", "Brian Staveley"));
         this.books.push(new Book("The End", "Gary McMahon"));
         this.books.push(new Book("Europe at Midnight", "Dave Hutchinson"));
         this.books.push(new Book("Europe in Autumn", "Dave Hutchinson"));
         this.books.push(new Book("Europe in Winter", "Dave Hutchinson"));
         this.books.push(new Book("Everfair", "Nisi Shawl"));
         this.books.push(new Book("The Fifth Season", "N. K. Jemisin"));
         this.books.push(new Book("The First Fifteen Lives of Harry August", "Claire North"));
         this.books.push(new Book("Full Fathom Five", "Max Gladstone"));
         this.books.push(new Book("The Girl In the Road", "Monica Byrne"));
         this.books.push(new Book("The Girl With All the Gifts", "M. R. Carey"));
         this.books.push(new Book("The Girls at the Kingfisher Club", "Genevieve Valentine"));
         this.books.push(new Book("Glorious Angels", "Justina Robson"));
         this.books.push(new Book("The Goblin Emperor", "Katherine Addison"));
         this.books.push(new Book("The Grace of Kings", "Ken Liu"));
         this.books.push(new Book("Guns of the Dawn", "Adrian Tchaikovsky"));
         this.books.push(new Book("Half a War", "Joe Abercrombie"));
         this.books.push(new Book("Hawk", "Steven Brust"));
         this.books.push(new Book("Heirs of Grace", "Tim Pratt"));
         this.books.push(new Book("The House of Shattered Wings", "Aliette de Bodard"));
         this.books.push(new Book("The Iron Ghost", "Jen Williams"));
         this.books.push(new Book("Karen Memory", "Elizabeth Bear"));
         this.books.push(new Book("Lagoon", "Nnedi Okorafor"));
         this.books.push(new Book("The Last Plague", "Rich Hawkins"));
         this.books.push(new Book("Lines of Departure", "Marko Kloos"));
         this.books.push(new Book("Lock In", "John Scalzi"));
         this.books.push(new Book("Lost Girl", "Adam Nevill"));
         this.books.push(new Book("Luna: New Moon", "Ian McDonald"));
         this.books.push(new Book("The Magician's Land", "Lev Grossman"));
         this.books.push(new Book("A Man Lies Dreaming", "Lavie Tidhar"));
         this.books.push(new Book("The Memory Garden", "Mary Rickert"));
         this.books.push(new Book("The Memory of Sky", "Robert Reed"));
         this.books.push(new Book("The Mirror Empire", "Kameron Hurley"));
         this.books.push(new Book("The Moon King", "Neil Williamson"));
         this.books.push(new Book("Mother of Eden", "Chris Beckett"));
         this.books.push(new Book("My Real Children", "Jo Walton"));
         this.books.push(new Book("Ninefox Gambit", "Yoon Ha Lee"));
         this.books.push(new Book("No One Gets Out Alive", "Adam Nevill"));
         this.books.push(new Book("The Obelisk Gate", "N. K. Jemisin"));
         this.books.push(new Book("Occupy Me", "Tricia Sullivan"));
         this.books.push(new Book("Otherbound", "Corinne Duyvis"));
         this.books.push(new Book("The Peripheral", "William Gibson"));
         this.books.push(new Book("The Race", "Nina Allan"));
         this.books.push(new Book("Raising Caine", "Charles E. Gannon"));
         this.books.push(new Book("Rawblood", "Catriona Ward"));
         this.books.push(new Book("The Relic Guild", "Edward Cox"));
         this.books.push(new Book("Resurrections", "Roz Kaveney"));
         this.books.push(new Book("Revival", "Stephen King"));
         this.books.push(new Book("Seveneves", "Neal Stephenson"));
         this.books.push(new Book("Shipstar", "Gregory Benford & Larry Niven"));
         this.books.push(new Book("Signal to Noise", "Silvia Moreno-Garcia"));
         this.books.push(new Book("The Silence", "Tim Lebbon"));
         this.books.push(new Book("Skin Game", "Jim Butcher"));
         this.books.push(new Book("The Sorcerer of the Wildeeps", "Kai Ashante Wilson"));
         this.books.push(new Book("Sorcerer to the Crown", "Zen Cho"));
         this.books.push(new Book("Station Eleven", "Emily St. John Mandel"));
         this.books.push(new Book("Steles of the Sky", "Elizabeth Bear"));
         this.books.push(new Book("The Stone Boatmen", "Sarah Tolmie"));
         this.books.push(new Book("The Three-Body Problem", "Cixin Liu"));
         this.books.push(new Book("The Three-Body Problem", "Cixin Liu, translated by Ken Liu"));
         this.books.push(new Book("Tigerman", "Nick Harkaway"));
         this.books.push(new Book("Too Like the Lightning", "Ada Palmer"));
         this.books.push(new Book("Trial by Fire", "Charles E. Gannon"));
         this.books.push(new Book("Ultima", "Stephen Baxter"));
         this.books.push(new Book("The Unquiet House", "Alison Littlewood"));
         this.books.push(new Book("Unwrapped Sky", "Rjurik Davidson"));
         this.books.push(new Book("Updraft", "Fran Wilde"));
         this.books.push(new Book("Uprooted", "Naomi Novik"));
         this.books.push(new Book("War Dogs", "Greg Bear"));
         this.books.push(new Book("The Watchmaker of Filigree Street", "Natasha Pulley"));
         this.books.push(new Book("The Water Knife", "Paolo Bacigalupi"));
         this.books.push(new Book("Welcome to Night Vale", "Joseph Fink & Jeffrey Cranor"));
         this.books.push(new Book("The Widow's House", "Daniel Abraham"));
         this.books.push(new Book("The Winter Boy", "Sally Wiener Grotta"));
         this.books.push(new Book("Wolves", "Simon Ings"));
         this.books.push(new Book("Words of Radiance", "Brandon Sanderson"));
         this.books.push(new Book("Work Done for Hire", "Joe Haldeman"));
         this.books.push(new Book("World of Trouble", "Ben H. Winters"));
         this.books.push(new Book("Wylding Hall", "Elizabeth Hand"));

         this.bookToDclUrl[this.books[2]] = "https://dcl.bibliocommons.com/item/show/1283248114_the_aeronauts_windlass";
         this.bookToDclUrl[this.books[3]] = "https://dcl.bibliocommons.com/item/show/1211027114_afterparty";
         this.bookToDclUrl[this.books[4]] = "https://dcl.bibliocommons.com/item/show/1221346114_all_those_vanished_engines";
         this.bookToDclUrl[this.books[5]] = "https://dcl.bibliocommons.com/item/show/1306204114_all_the_birds_in_the_sky";
         this.bookToDclUrl[this.books[6]] = "https://dcl.bibliocommons.com/item/show/1285414114_ancillary_mercy";
         this.bookToDclUrl[this.books[7]] = "https://dcl.bibliocommons.com/item/show/1236644114_ancillary_sword";
         this.bookToDclUrl[this.books[8]] = "https://dcl.bibliocommons.com/item/show/1226009114_the_angel_of_losses";
         this.bookToDclUrl[this.books[9]] = "https://dcl.bibliocommons.com/item/show/1176051114_annihilation";
         this.bookToDclUrl[this.books[11]] = "https://dcl.bibliocommons.com/item/show/1275871114_aurora";
         this.bookToDclUrl[this.books[14]] = "https://dcl.bibliocommons.com/item/show/1226233114_bathing_the_lion";
         this.bookToDclUrl[this.books[16]] = "https://dcl.bibliocommons.com/item/show/1211977114_the_bees";
         this.bookToDclUrl[this.books[17]] = "https://dcl.bibliocommons.com/item/show/1249867114_the_blood_of_angels";
         this.bookToDclUrl[this.books[18]] = "https://dcl.bibliocommons.com/item/show/1224405114_the_bone_clocks";
         this.bookToDclUrl[this.books[19]] = "https://dcl.bibliocommons.com/item/show/1313297114_borderline";
         this.bookToDclUrl[this.books[21]] = "https://dcl.bibliocommons.com/item/show/1228399114_the_boy_who_drew_monsters";
         this.bookToDclUrl[this.books[24]] = "https://dcl.bibliocommons.com/item/show/1218276114_california_bones";
         this.bookToDclUrl[this.books[25]] = "https://dcl.bibliocommons.com/item/show/1234154114_the_causal_angel";
         this.bookToDclUrl[this.books[26]] = "https://dcl.bibliocommons.com/item/show/1216736114_cibola_burn";
         this.bookToDclUrl[this.books[27]] = "https://dcl.bibliocommons.com/item/show/1216737114_city_of_stairs";
         this.bookToDclUrl[this.books[28]] = "https://dcl.bibliocommons.com/item/show/1235659114_the_clockwork_dagger";
         this.bookToDclUrl[this.books[29]] = "https://dcl.bibliocommons.com/item/show/1388021114_a_closed_and_common_orbit";
         this.bookToDclUrl[this.books[31]] = "https://dcl.bibliocommons.com/item/show/1241677114_coming_home";
         this.bookToDclUrl[this.books[32]] = "https://dcl.bibliocommons.com/item/show/1263796114_cuckoo_song";
         this.bookToDclUrl[this.books[33]] = "https://dcl.bibliocommons.com/item/show/1218192114_the_dark_between_the_stars";
         this.bookToDclUrl[this.books[34]] = "https://dcl.bibliocommons.com/item/show/1244766114_the_dark_defiles";
         this.bookToDclUrl[this.books[35]] = "https://dcl.bibliocommons.com/item/show/1228684114_dark_lightning";
         this.bookToDclUrl[this.books[36]] = "https://dcl.bibliocommons.com/item/show/1186943114_a_darkling_sea";
         this.bookToDclUrl[this.books[39]] = "https://dcl.bibliocommons.com/item/show/1357571114_deaths_end";
         this.bookToDclUrl[this.books[40]] = "https://dcl.bibliocommons.com/item/show/1226237114_echopraxia";
         this.bookToDclUrl[this.books[42]] = "https://dcl.bibliocommons.com/item/show/1185040114_the_emperors_blades";
         this.bookToDclUrl[this.books[47]] = "https://dcl.bibliocommons.com/item/show/1357853114_everfair";
         this.bookToDclUrl[this.books[48]] = "https://dcl.bibliocommons.com/item/show/1281167114_the_fifth_season";
         this.bookToDclUrl[this.books[49]] = "https://dcl.bibliocommons.com/item/show/1212567114_the_first_fifteen_lives_of_harry_august";
         this.bookToDclUrl[this.books[50]] = "https://dcl.bibliocommons.com/item/show/1220997114_full_fathom_five";
         this.bookToDclUrl[this.books[51]] = "https://dcl.bibliocommons.com/item/show/1212054114_the_girl_in_the_road";
         this.bookToDclUrl[this.books[52]] = "https://dcl.bibliocommons.com/item/show/1218985114_the_girl_with_all_the_gifts";
         this.bookToDclUrl[this.books[53]] = "https://dcl.bibliocommons.com/item/show/1214729114_the_girls_at_the_kingfisher_club";
         this.bookToDclUrl[this.books[55]] = "https://dcl.bibliocommons.com/item/show/1210976114_the_goblin_emperor";
         this.bookToDclUrl[this.books[56]] = "https://dcl.bibliocommons.com/item/show/1263769114_the_grace_of_kings";
         this.bookToDclUrl[this.books[58]] = "https://dcl.bibliocommons.com/item/show/1281023114_half_a_war";
         this.bookToDclUrl[this.books[59]] = "https://dcl.bibliocommons.com/item/show/1242644114_hawk";
         this.bookToDclUrl[this.books[61]] = "https://dcl.bibliocommons.com/item/show/1283849114_the_house_of_shattered_wings";
         this.bookToDclUrl[this.books[63]] = "https://dcl.bibliocommons.com/item/show/1249360114_karen_memory";
         this.bookToDclUrl[this.books[66]] = "https://dcl.bibliocommons.com/item/show/1213806114_lines_of_departure";
         this.bookToDclUrl[this.books[67]] = "https://dcl.bibliocommons.com/item/show/1228113114_lock_in";
         this.bookToDclUrl[this.books[70]] = "https://dcl.bibliocommons.com/item/show/1213964114_the_magicians_land";
         this.bookToDclUrl[this.books[71]] = "https://dcl.bibliocommons.com/item/show/1313275114_a_man_lies_dreaming";
         this.bookToDclUrl[this.books[72]] = "https://dcl.bibliocommons.com/item/show/1214405114_the_memory_garden";
         this.bookToDclUrl[this.books[74]] = "https://dcl.bibliocommons.com/item/show/1231399114_the_mirror_empire";
         this.bookToDclUrl[this.books[76]] = "https://dcl.bibliocommons.com/item/show/1264846114_mother_of_eden";
         this.bookToDclUrl[this.books[77]] = "https://dcl.bibliocommons.com/item/show/1214733114_my_real_children";
         this.bookToDclUrl[this.books[78]] = "https://dcl.bibliocommons.com/item/show/1357603114_ninefox_gambit";
         this.bookToDclUrl[this.books[79]] = "https://dcl.bibliocommons.com/item/show/1264084114_no_one_gets_out_alive";
         this.bookToDclUrl[this.books[80]] = "https://dcl.bibliocommons.com/item/show/1354400114_the_obelisk_gate";
         this.bookToDclUrl[this.books[82]] = "https://dcl.bibliocommons.com/item/show/1219335114_otherbound";
         this.bookToDclUrl[this.books[83]] = "https://dcl.bibliocommons.com/item/show/1232634114_the_peripheral";
         this.bookToDclUrl[this.books[84]] = "https://dcl.bibliocommons.com/item/show/1336258114_the_race";
         this.bookToDclUrl[this.books[85]] = "https://dcl.bibliocommons.com/item/show/1294767114_raising_caine";
         this.bookToDclUrl[this.books[86]] = "https://dcl.bibliocommons.com/item/show/1380027114_the_girl_from_rawblood";
         this.bookToDclUrl[this.books[89]] = "https://dcl.bibliocommons.com/item/show/1233153114_revival";
         this.bookToDclUrl[this.books[90]] = "https://dcl.bibliocommons.com/item/show/1262334114_seveneves";
         this.bookToDclUrl[this.books[91]] = "https://dcl.bibliocommons.com/item/show/1208099114_shipstar";
         this.bookToDclUrl[this.books[92]] = "https://dcl.bibliocommons.com/item/show/1275866114_signal_to_noise";
         this.bookToDclUrl[this.books[93]] = "https://dcl.bibliocommons.com/item/show/1269118114_the_silence";
         this.bookToDclUrl[this.books[94]] = "https://dcl.bibliocommons.com/item/show/1213971114_skin_game";
         this.bookToDclUrl[this.books[95]] = "https://dcl.bibliocommons.com/item/show/1288127114_the_sorcerer_of_the_wildeeps";
         this.bookToDclUrl[this.books[96]] = "https://dcl.bibliocommons.com/item/show/1281512114_sorcerer_to_the_crown";
         this.bookToDclUrl[this.books[97]] = "https://dcl.bibliocommons.com/item/show/1217291114_station_eleven";
         this.bookToDclUrl[this.books[98]] = "https://dcl.bibliocommons.com/item/show/1210987114_steles_of_the_sky";
         this.bookToDclUrl[this.books[100]] = "https://dcl.bibliocommons.com/item/show/1242658114_the_three-body_problem";
         this.bookToDclUrl[this.books[101]] = "https://dcl.bibliocommons.com/item/show/1242658114_the_three-body_problem";
         this.bookToDclUrl[this.books[102]] = "https://dcl.bibliocommons.com/item/show/1224269114_tigerman";
         this.bookToDclUrl[this.books[103]] = "https://dcl.bibliocommons.com/item/show/1336393114_too_like_the_lightning";
         this.bookToDclUrl[this.books[105]] = "https://dcl.bibliocommons.com/item/show/1284544114_ultima";
         this.bookToDclUrl[this.books[107]] = "https://dcl.bibliocommons.com/item/show/1213176114_unwrapped_sky";
         this.bookToDclUrl[this.books[108]] = "https://dcl.bibliocommons.com/item/show/1277391114_updraft";
         this.bookToDclUrl[this.books[109]] = "https://dcl.bibliocommons.com/item/show/1262337114_uprooted";
         this.bookToDclUrl[this.books[110]] = "https://dcl.bibliocommons.com/item/show/1232642114_war_dogs";
         this.bookToDclUrl[this.books[111]] = "https://dcl.bibliocommons.com/item/show/1262914114_the_watchmaker_of_filigree_street";
         this.bookToDclUrl[this.books[112]] = "https://dcl.bibliocommons.com/item/show/1256448114_the_water_knife";
         this.bookToDclUrl[this.books[113]] = "https://dcl.bibliocommons.com/item/show/1273614114_welcome_to_night_vale";
         this.bookToDclUrl[this.books[114]] = "https://dcl.bibliocommons.com/item/show/1228429114_the_widows_house";
         this.bookToDclUrl[this.books[117]] = "https://dcl.bibliocommons.com/item/show/1186308114_words_of_radiance";
         this.bookToDclUrl[this.books[118]] = "https://dcl.bibliocommons.com/item/show/1186756114_work_done_for_hire";
         this.bookToDclUrl[this.books[119]] = "https://dcl.bibliocommons.com/item/show/1214418114_world_of_trouble";

         this.initializeBookToNomination();

         this.bookToNomination[this.books[0]].push(new Nomination(locus, locus.categories.properties.sf, 2015, false));
         this.bookToNomination[this.books[1]].push(new Nomination(locus, locus.categories.properties.sf, 2015, false));
         this.bookToNomination[this.books[2]].push(new Nomination(hugo, hugo.categories.properties.novel, 2016, false));
         this.bookToNomination[this.books[3]].push(new Nomination(locus, locus.categories.properties.sf, 2015, false));
         this.bookToNomination[this.books[4]].push(new Nomination(locus, locus.categories.properties.sf, 2015, false));
         this.bookToNomination[this.books[5]].push(new Nomination(hugo, hugo.categories.properties.novel, 2017, false));
         this.bookToNomination[this.books[5]].push(new Nomination(nebula, nebula.categories.properties.novel, 2017, true));
         this.bookToNomination[this.books[6]].push(new Nomination(hugo, hugo.categories.properties.novel, 2016, false));
         this.bookToNomination[this.books[6]].push(new Nomination(locus, locus.categories.properties.sf, 2016, true));
         this.bookToNomination[this.books[6]].push(new Nomination(nebula, nebula.categories.properties.novel, 2016, false));
         this.bookToNomination[this.books[7]].push(new Nomination(britishSf, britishSf.categories.properties.novel, 2015, true));
         this.bookToNomination[this.books[7]].push(new Nomination(hugo, hugo.categories.properties.novel, 2015, false));
         this.bookToNomination[this.books[7]].push(new Nomination(locus, locus.categories.properties.sf, 2015, true));
         this.bookToNomination[this.books[7]].push(new Nomination(nebula, nebula.categories.properties.novel, 2015, false));
         this.bookToNomination[this.books[8]].push(new Nomination(locus, locus.categories.properties.first, 2015, false));
         this.bookToNomination[this.books[9]].push(new Nomination(nebula, nebula.categories.properties.novel, 2015, true));
         this.bookToNomination[this.books[10]].push(new Nomination(locus, locus.categories.properties.sf, 2015, false));
         this.bookToNomination[this.books[11]].push(new Nomination(locus, locus.categories.properties.sf, 2016, false));
         this.bookToNomination[this.books[12]].push(new Nomination(britishSf, britishSf.categories.properties.novel, 2017, false));
         this.bookToNomination[this.books[13]].push(new Nomination(nebula, nebula.categories.properties.novel, 2016, false));
         this.bookToNomination[this.books[14]].push(new Nomination(locus, locus.categories.properties.fantasy, 2015, false));
         this.bookToNomination[this.books[15]].push(new Nomination(locus, locus.categories.properties.fantasy, 2015, false));
         this.bookToNomination[this.books[16]].push(new Nomination(locus, locus.categories.properties.fantasy, 2015, false));
         this.bookToNomination[this.books[17]].push(new Nomination(locus, locus.categories.properties.sf, 2015, false));
         this.bookToNomination[this.books[18]].push(new Nomination(locus, locus.categories.properties.sf, 2015, false));
         this.bookToNomination[this.books[19]].push(new Nomination(nebula, nebula.categories.properties.novel, 2017, false));
         this.bookToNomination[this.books[20]].push(new Nomination(locus, locus.categories.properties.sf, 2016, false));
         this.bookToNomination[this.books[21]].push(new Nomination(locus, locus.categories.properties.fantasy, 2015, false));
         this.bookToNomination[this.books[22]].push(new Nomination(britishFantasy, britishFantasy.categories.properties.fantasy, 2015, false));
         this.bookToNomination[this.books[23]].push(new Nomination(locus, locus.categories.properties.sf, 2015, false));
         this.bookToNomination[this.books[24]].push(new Nomination(locus, locus.categories.properties.fantasy, 2015, false));
         this.bookToNomination[this.books[25]].push(new Nomination(locus, locus.categories.properties.sf, 2015, false));
         this.bookToNomination[this.books[26]].push(new Nomination(locus, locus.categories.properties.sf, 2015, false));
         this.bookToNomination[this.books[27]].push(new Nomination(britishFantasy, britishFantasy.categories.properties.fantasy, 2015, false));
         this.bookToNomination[this.books[27]].push(new Nomination(locus, locus.categories.properties.fantasy, 2015, false));
         this.bookToNomination[this.books[28]].push(new Nomination(locus, locus.categories.properties.first, 2015, false));
         this.bookToNomination[this.books[29]].push(new Nomination(britishSf, britishSf.categories.properties.novel, 2017, false));
         this.bookToNomination[this.books[29]].push(new Nomination(hugo, hugo.categories.properties.novel, 2017, false));
         this.bookToNomination[this.books[30]].push(new Nomination(britishFantasy, britishFantasy.categories.properties.horror, 2016, false));
         this.bookToNomination[this.books[31]].push(new Nomination(nebula, nebula.categories.properties.novel, 2015, false));
         this.bookToNomination[this.books[32]].push(new Nomination(britishFantasy, britishFantasy.categories.properties.fantasy, 2015, true));
         this.bookToNomination[this.books[32]].push(new Nomination(britishSf, britishSf.categories.properties.novel, 2015, false));
         this.bookToNomination[this.books[33]].push(new Nomination(hugo, hugo.categories.properties.novel, 2015, false));
         this.bookToNomination[this.books[34]].push(new Nomination(locus, locus.categories.properties.fantasy, 2015, false));
         this.bookToNomination[this.books[35]].push(new Nomination(locus, locus.categories.properties.sf, 2015, false));
         this.bookToNomination[this.books[36]].push(new Nomination(locus, locus.categories.properties.first, 2015, false));
         this.bookToNomination[this.books[37]].push(new Nomination(britishSf, britishSf.categories.properties.novel, 2017, false));
         this.bookToNomination[this.books[38]].push(new Nomination(britishFantasy, britishFantasy.categories.properties.horror, 2016, false));
         this.bookToNomination[this.books[39]].push(new Nomination(hugo, hugo.categories.properties.novel, 2017, false));
         this.bookToNomination[this.books[40]].push(new Nomination(locus, locus.categories.properties.sf, 2015, false));
         this.bookToNomination[this.books[41]].push(new Nomination(locus, locus.categories.properties.first, 2015, false));
         this.bookToNomination[this.books[42]].push(new Nomination(locus, locus.categories.properties.first, 2015, false));
         this.bookToNomination[this.books[43]].push(new Nomination(britishFantasy, britishFantasy.categories.properties.horror, 2015, false));
         this.bookToNomination[this.books[44]].push(new Nomination(britishSf, britishSf.categories.properties.novel, 2016, false));
         this.bookToNomination[this.books[45]].push(new Nomination(britishSf, britishSf.categories.properties.novel, 2015, false));
         this.bookToNomination[this.books[45]].push(new Nomination(locus, locus.categories.properties.sf, 2015, false));
         this.bookToNomination[this.books[46]].push(new Nomination(britishSf, britishSf.categories.properties.novel, 2017, true));
         this.bookToNomination[this.books[47]].push(new Nomination(nebula, nebula.categories.properties.novel, 2017, false));
         this.bookToNomination[this.books[48]].push(new Nomination(hugo, hugo.categories.properties.novel, 2016, true));
         this.bookToNomination[this.books[48]].push(new Nomination(locus, locus.categories.properties.fantasy, 2016, false));
         this.bookToNomination[this.books[48]].push(new Nomination(nebula, nebula.categories.properties.novel, 2016, false));
         this.bookToNomination[this.books[49]].push(new Nomination(britishSf, britishSf.categories.properties.novel, 2015, false));
         this.bookToNomination[this.books[50]].push(new Nomination(locus, locus.categories.properties.fantasy, 2015, false));
         this.bookToNomination[this.books[51]].push(new Nomination(locus, locus.categories.properties.first, 2015, false));
         this.bookToNomination[this.books[52]].push(new Nomination(britishFantasy, britishFantasy.categories.properties.horror, 2015, false));
         this.bookToNomination[this.books[53]].push(new Nomination(locus, locus.categories.properties.fantasy, 2015, false));
         this.bookToNomination[this.books[54]].push(new Nomination(britishSf, britishSf.categories.properties.novel, 2016, false));
         this.bookToNomination[this.books[55]].push(new Nomination(hugo, hugo.categories.properties.novel, 2015, false));
         this.bookToNomination[this.books[55]].push(new Nomination(locus, locus.categories.properties.fantasy, 2015, true));
         this.bookToNomination[this.books[55]].push(new Nomination(nebula, nebula.categories.properties.novel, 2015, false));
         this.bookToNomination[this.books[56]].push(new Nomination(locus, locus.categories.properties.first, 2016, true));
         this.bookToNomination[this.books[56]].push(new Nomination(nebula, nebula.categories.properties.novel, 2016, false));
         this.bookToNomination[this.books[57]].push(new Nomination(britishFantasy, britishFantasy.categories.properties.fantasy, 2016, false));
         this.bookToNomination[this.books[58]].push(new Nomination(britishFantasy, britishFantasy.categories.properties.fantasy, 2016, false));
         this.bookToNomination[this.books[59]].push(new Nomination(locus, locus.categories.properties.fantasy, 2015, false));
         this.bookToNomination[this.books[60]].push(new Nomination(locus, locus.categories.properties.fantasy, 2015, false));
         this.bookToNomination[this.books[61]].push(new Nomination(britishSf, britishSf.categories.properties.novel, 2016, true));
         this.bookToNomination[this.books[61]].push(new Nomination(locus, locus.categories.properties.fantasy, 2016, false));
         this.bookToNomination[this.books[62]].push(new Nomination(britishFantasy, britishFantasy.categories.properties.fantasy, 2016, false));
         this.bookToNomination[this.books[63]].push(new Nomination(locus, locus.categories.properties.fantasy, 2016, false));
         this.bookToNomination[this.books[64]].push(new Nomination(britishSf, britishSf.categories.properties.novel, 2015, false));
         this.bookToNomination[this.books[64]].push(new Nomination(locus, locus.categories.properties.sf, 2015, false));
         this.bookToNomination[this.books[65]].push(new Nomination(britishFantasy, britishFantasy.categories.properties.horror, 2015, false));
         this.bookToNomination[this.books[66]].push(new Nomination(hugo, hugo.categories.properties.novel, 2015, false));
         this.bookToNomination[this.books[67]].push(new Nomination(locus, locus.categories.properties.sf, 2015, false));
         this.bookToNomination[this.books[68]].push(new Nomination(britishFantasy, britishFantasy.categories.properties.horror, 2016, false));
         this.bookToNomination[this.books[69]].push(new Nomination(britishSf, britishSf.categories.properties.novel, 2016, false));
         this.bookToNomination[this.books[70]].push(new Nomination(locus, locus.categories.properties.fantasy, 2015, false));
         this.bookToNomination[this.books[71]].push(new Nomination(britishFantasy, britishFantasy.categories.properties.fantasy, 2015, false));
         this.bookToNomination[this.books[71]].push(new Nomination(locus, locus.categories.properties.fantasy, 2015, false));
         this.bookToNomination[this.books[72]].push(new Nomination(locus, locus.categories.properties.first, 2015, true));
         this.bookToNomination[this.books[73]].push(new Nomination(locus, locus.categories.properties.sf, 2015, false));
         this.bookToNomination[this.books[74]].push(new Nomination(locus, locus.categories.properties.fantasy, 2015, false));
         this.bookToNomination[this.books[75]].push(new Nomination(britishFantasy, britishFantasy.categories.properties.fantasy, 2015, false));
         this.bookToNomination[this.books[75]].push(new Nomination(britishSf, britishSf.categories.properties.novel, 2015, false));
         this.bookToNomination[this.books[76]].push(new Nomination(britishSf, britishSf.categories.properties.novel, 2016, false));
         this.bookToNomination[this.books[77]].push(new Nomination(locus, locus.categories.properties.sf, 2015, false));
         this.bookToNomination[this.books[78]].push(new Nomination(hugo, hugo.categories.properties.novel, 2017, false));
         this.bookToNomination[this.books[78]].push(new Nomination(nebula, nebula.categories.properties.novel, 2017, false));
         this.bookToNomination[this.books[79]].push(new Nomination(britishFantasy, britishFantasy.categories.properties.horror, 2015, true));
         this.bookToNomination[this.books[80]].push(new Nomination(hugo, hugo.categories.properties.novel, 2017, false));
         this.bookToNomination[this.books[80]].push(new Nomination(nebula, nebula.categories.properties.novel, 2017, false));
         this.bookToNomination[this.books[81]].push(new Nomination(britishSf, britishSf.categories.properties.novel, 2017, false));
         this.bookToNomination[this.books[82]].push(new Nomination(locus, locus.categories.properties.first, 2015, false));
         this.bookToNomination[this.books[83]].push(new Nomination(locus, locus.categories.properties.sf, 2015, false));
         this.bookToNomination[this.books[84]].push(new Nomination(britishSf, britishSf.categories.properties.novel, 2015, false));
         this.bookToNomination[this.books[84]].push(new Nomination(locus, locus.categories.properties.first, 2015, false));
         this.bookToNomination[this.books[85]].push(new Nomination(nebula, nebula.categories.properties.novel, 2016, false));
         this.bookToNomination[this.books[86]].push(new Nomination(britishFantasy, britishFantasy.categories.properties.horror, 2016, true));
         this.bookToNomination[this.books[87]].push(new Nomination(britishFantasy, britishFantasy.categories.properties.fantasy, 2015, false));
         this.bookToNomination[this.books[88]].push(new Nomination(locus, locus.categories.properties.fantasy, 2015, false));
         this.bookToNomination[this.books[89]].push(new Nomination(locus, locus.categories.properties.fantasy, 2015, false));
         this.bookToNomination[this.books[90]].push(new Nomination(hugo, hugo.categories.properties.novel, 2016, false));
         this.bookToNomination[this.books[90]].push(new Nomination(locus, locus.categories.properties.sf, 2016, false));
         this.bookToNomination[this.books[91]].push(new Nomination(locus, locus.categories.properties.sf, 2015, false));
         this.bookToNomination[this.books[92]].push(new Nomination(britishFantasy, britishFantasy.categories.properties.fantasy, 2016, false));
         this.bookToNomination[this.books[92]].push(new Nomination(locus, locus.categories.properties.first, 2016, false));
         this.bookToNomination[this.books[93]].push(new Nomination(britishFantasy, britishFantasy.categories.properties.horror, 2016, false));
         this.bookToNomination[this.books[94]].push(new Nomination(hugo, hugo.categories.properties.novel, 2015, false));
         this.bookToNomination[this.books[95]].push(new Nomination(locus, locus.categories.properties.first, 2016, false));
         this.bookToNomination[this.books[96]].push(new Nomination(britishFantasy, britishFantasy.categories.properties.fantasy, 2016, false));
         this.bookToNomination[this.books[96]].push(new Nomination(locus, locus.categories.properties.first, 2016, false));
         this.bookToNomination[this.books[97]].push(new Nomination(britishFantasy, britishFantasy.categories.properties.horror, 2015, false));
         this.bookToNomination[this.books[97]].push(new Nomination(locus, locus.categories.properties.sf, 2015, false));
         this.bookToNomination[this.books[98]].push(new Nomination(locus, locus.categories.properties.fantasy, 2015, false));
         this.bookToNomination[this.books[99]].push(new Nomination(locus, locus.categories.properties.first, 2015, false));
         this.bookToNomination[this.books[100]].push(new Nomination(locus, locus.categories.properties.sf, 2015, false));
         this.bookToNomination[this.books[101]].push(new Nomination(hugo, hugo.categories.properties.novel, 2015, true));
         this.bookToNomination[this.books[101]].push(new Nomination(nebula, nebula.categories.properties.novel, 2015, false));
         this.bookToNomination[this.books[102]].push(new Nomination(locus, locus.categories.properties.sf, 2015, false));
         this.bookToNomination[this.books[103]].push(new Nomination(hugo, hugo.categories.properties.novel, 2017, false));
         this.bookToNomination[this.books[104]].push(new Nomination(nebula, nebula.categories.properties.novel, 2015, false));
         this.bookToNomination[this.books[105]].push(new Nomination(locus, locus.categories.properties.sf, 2015, false));
         this.bookToNomination[this.books[106]].push(new Nomination(britishFantasy, britishFantasy.categories.properties.horror, 2015, false));
         this.bookToNomination[this.books[107]].push(new Nomination(locus, locus.categories.properties.first, 2015, false));
         this.bookToNomination[this.books[108]].push(new Nomination(nebula, nebula.categories.properties.novel, 2016, false));
         this.bookToNomination[this.books[109]].push(new Nomination(britishFantasy, britishFantasy.categories.properties.fantasy, 2016, true));
         this.bookToNomination[this.books[109]].push(new Nomination(hugo, hugo.categories.properties.novel, 2016, false));
         this.bookToNomination[this.books[109]].push(new Nomination(locus, locus.categories.properties.fantasy, 2016, true));
         this.bookToNomination[this.books[109]].push(new Nomination(nebula, nebula.categories.properties.novel, 2016, true));
         this.bookToNomination[this.books[110]].push(new Nomination(locus, locus.categories.properties.sf, 2015, false));
         this.bookToNomination[this.books[111]].push(new Nomination(locus, locus.categories.properties.first, 2016, false));
         this.bookToNomination[this.books[112]].push(new Nomination(locus, locus.categories.properties.sf, 2016, false));
         this.bookToNomination[this.books[113]].push(new Nomination(britishFantasy, britishFantasy.categories.properties.horror, 2016, false));
         this.bookToNomination[this.books[114]].push(new Nomination(locus, locus.categories.properties.fantasy, 2015, false));
         this.bookToNomination[this.books[115]].push(new Nomination(locus, locus.categories.properties.fantasy, 2015, false));
         this.bookToNomination[this.books[116]].push(new Nomination(britishSf, britishSf.categories.properties.novel, 2015, false));
         this.bookToNomination[this.books[116]].push(new Nomination(locus, locus.categories.properties.sf, 2015, false));
         this.bookToNomination[this.books[117]].push(new Nomination(locus, locus.categories.properties.fantasy, 2015, false));
         this.bookToNomination[this.books[118]].push(new Nomination(locus, locus.categories.properties.sf, 2015, false));
         this.bookToNomination[this.books[119]].push(new Nomination(locus, locus.categories.properties.sf, 2015, false));
         this.bookToNomination[this.books[120]].push(new Nomination(locus, locus.categories.properties.fantasy, 2016, false));

         this.initializeBookToAssessment();
         this.loadBookToAssessment();
      }

      SciFiInitialState.prototype.initializeBookToAssessment = function()
      {
         this.bookToAssessment = UserSettings.resetBookToAssessment(this.bookToAssessment, this.books, this.bookToDclUrl, this.bookToNomination);
      };

      SciFiInitialState.prototype.initializeBookToNomination = function()
      {
         this.books.forEach(function(book)
         {
            this.bookToNomination[book] = [];
         }, this);
      };

      SciFiInitialState.prototype.loadBookToAssessment = function()
      {
         var myBookToAssessment = UserSettings.loadBookToAssessment();
         Object.vizziniMerge(this.bookToAssessment, myBookToAssessment);
      };

      if (Object.freeze)
      {
         Object.freeze(SciFiInitialState);
      }

      return SciFiInitialState;
   });
